// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/vkr/auth/internal/services/auth_service.SessionStorage -o session_storage_mock.go -n SessionStorageMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/vkr/auth/internal/domain"
)

// SessionStorageMock implements mm_auth_service.SessionStorage
type SessionStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteAllUserTokens          func(ctx context.Context, userID string) (err error)
	funcDeleteAllUserTokensOrigin    string
	inspectFuncDeleteAllUserTokens   func(ctx context.Context, userID string)
	afterDeleteAllUserTokensCounter  uint64
	beforeDeleteAllUserTokensCounter uint64
	DeleteAllUserTokensMock          mSessionStorageMockDeleteAllUserTokens

	funcDeleteRefreshToken          func(ctx context.Context, jti string) (err error)
	funcDeleteRefreshTokenOrigin    string
	inspectFuncDeleteRefreshToken   func(ctx context.Context, jti string)
	afterDeleteRefreshTokenCounter  uint64
	beforeDeleteRefreshTokenCounter uint64
	DeleteRefreshTokenMock          mSessionStorageMockDeleteRefreshToken

	funcDeleteTokenFamily          func(ctx context.Context, family string, userID string) (err error)
	funcDeleteTokenFamilyOrigin    string
	inspectFuncDeleteTokenFamily   func(ctx context.Context, family string, userID string)
	afterDeleteTokenFamilyCounter  uint64
	beforeDeleteTokenFamilyCounter uint64
	DeleteTokenFamilyMock          mSessionStorageMockDeleteTokenFamily

	funcGetRefreshToken          func(ctx context.Context, jti string) (rp1 *domain.RefreshTokenData, err error)
	funcGetRefreshTokenOrigin    string
	inspectFuncGetRefreshToken   func(ctx context.Context, jti string)
	afterGetRefreshTokenCounter  uint64
	beforeGetRefreshTokenCounter uint64
	GetRefreshTokenMock          mSessionStorageMockGetRefreshToken

	funcStoreRefreshToken          func(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration) (err error)
	funcStoreRefreshTokenOrigin    string
	inspectFuncStoreRefreshToken   func(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration)
	afterStoreRefreshTokenCounter  uint64
	beforeStoreRefreshTokenCounter uint64
	StoreRefreshTokenMock          mSessionStorageMockStoreRefreshToken
}

// NewSessionStorageMock returns a mock for mm_auth_service.SessionStorage
func NewSessionStorageMock(t minimock.Tester) *SessionStorageMock {
	m := &SessionStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteAllUserTokensMock = mSessionStorageMockDeleteAllUserTokens{mock: m}
	m.DeleteAllUserTokensMock.callArgs = []*SessionStorageMockDeleteAllUserTokensParams{}

	m.DeleteRefreshTokenMock = mSessionStorageMockDeleteRefreshToken{mock: m}
	m.DeleteRefreshTokenMock.callArgs = []*SessionStorageMockDeleteRefreshTokenParams{}

	m.DeleteTokenFamilyMock = mSessionStorageMockDeleteTokenFamily{mock: m}
	m.DeleteTokenFamilyMock.callArgs = []*SessionStorageMockDeleteTokenFamilyParams{}

	m.GetRefreshTokenMock = mSessionStorageMockGetRefreshToken{mock: m}
	m.GetRefreshTokenMock.callArgs = []*SessionStorageMockGetRefreshTokenParams{}

	m.StoreRefreshTokenMock = mSessionStorageMockStoreRefreshToken{mock: m}
	m.StoreRefreshTokenMock.callArgs = []*SessionStorageMockStoreRefreshTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSessionStorageMockDeleteAllUserTokens struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockDeleteAllUserTokensExpectation
	expectations       []*SessionStorageMockDeleteAllUserTokensExpectation

	callArgs []*SessionStorageMockDeleteAllUserTokensParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockDeleteAllUserTokensExpectation specifies expectation struct of the SessionStorage.DeleteAllUserTokens
type SessionStorageMockDeleteAllUserTokensExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockDeleteAllUserTokensParams
	paramPtrs          *SessionStorageMockDeleteAllUserTokensParamPtrs
	expectationOrigins SessionStorageMockDeleteAllUserTokensExpectationOrigins
	results            *SessionStorageMockDeleteAllUserTokensResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockDeleteAllUserTokensParams contains parameters of the SessionStorage.DeleteAllUserTokens
type SessionStorageMockDeleteAllUserTokensParams struct {
	ctx    context.Context
	userID string
}

// SessionStorageMockDeleteAllUserTokensParamPtrs contains pointers to parameters of the SessionStorage.DeleteAllUserTokens
type SessionStorageMockDeleteAllUserTokensParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// SessionStorageMockDeleteAllUserTokensResults contains results of the SessionStorage.DeleteAllUserTokens
type SessionStorageMockDeleteAllUserTokensResults struct {
	err error
}

// SessionStorageMockDeleteAllUserTokensOrigins contains origins of expectations of the SessionStorage.DeleteAllUserTokens
type SessionStorageMockDeleteAllUserTokensExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Optional() *mSessionStorageMockDeleteAllUserTokens {
	mmDeleteAllUserTokens.optional = true
	return mmDeleteAllUserTokens
}

// Expect sets up expected params for SessionStorage.DeleteAllUserTokens
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Expect(ctx context.Context, userID string) *mSessionStorageMockDeleteAllUserTokens {
	if mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Set")
	}

	if mmDeleteAllUserTokens.defaultExpectation == nil {
		mmDeleteAllUserTokens.defaultExpectation = &SessionStorageMockDeleteAllUserTokensExpectation{}
	}

	if mmDeleteAllUserTokens.defaultExpectation.paramPtrs != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by ExpectParams functions")
	}

	mmDeleteAllUserTokens.defaultExpectation.params = &SessionStorageMockDeleteAllUserTokensParams{ctx, userID}
	mmDeleteAllUserTokens.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteAllUserTokens.expectations {
		if minimock.Equal(e.params, mmDeleteAllUserTokens.defaultExpectation.params) {
			mmDeleteAllUserTokens.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteAllUserTokens.defaultExpectation.params)
		}
	}

	return mmDeleteAllUserTokens
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.DeleteAllUserTokens
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockDeleteAllUserTokens {
	if mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Set")
	}

	if mmDeleteAllUserTokens.defaultExpectation == nil {
		mmDeleteAllUserTokens.defaultExpectation = &SessionStorageMockDeleteAllUserTokensExpectation{}
	}

	if mmDeleteAllUserTokens.defaultExpectation.params != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Expect")
	}

	if mmDeleteAllUserTokens.defaultExpectation.paramPtrs == nil {
		mmDeleteAllUserTokens.defaultExpectation.paramPtrs = &SessionStorageMockDeleteAllUserTokensParamPtrs{}
	}
	mmDeleteAllUserTokens.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteAllUserTokens.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteAllUserTokens
}

// ExpectUserIDParam2 sets up expected param userID for SessionStorage.DeleteAllUserTokens
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) ExpectUserIDParam2(userID string) *mSessionStorageMockDeleteAllUserTokens {
	if mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Set")
	}

	if mmDeleteAllUserTokens.defaultExpectation == nil {
		mmDeleteAllUserTokens.defaultExpectation = &SessionStorageMockDeleteAllUserTokensExpectation{}
	}

	if mmDeleteAllUserTokens.defaultExpectation.params != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Expect")
	}

	if mmDeleteAllUserTokens.defaultExpectation.paramPtrs == nil {
		mmDeleteAllUserTokens.defaultExpectation.paramPtrs = &SessionStorageMockDeleteAllUserTokensParamPtrs{}
	}
	mmDeleteAllUserTokens.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteAllUserTokens.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteAllUserTokens
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.DeleteAllUserTokens
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Inspect(f func(ctx context.Context, userID string)) *mSessionStorageMockDeleteAllUserTokens {
	if mmDeleteAllUserTokens.mock.inspectFuncDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.DeleteAllUserTokens")
	}

	mmDeleteAllUserTokens.mock.inspectFuncDeleteAllUserTokens = f

	return mmDeleteAllUserTokens
}

// Return sets up results that will be returned by SessionStorage.DeleteAllUserTokens
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Return(err error) *SessionStorageMock {
	if mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Set")
	}

	if mmDeleteAllUserTokens.defaultExpectation == nil {
		mmDeleteAllUserTokens.defaultExpectation = &SessionStorageMockDeleteAllUserTokensExpectation{mock: mmDeleteAllUserTokens.mock}
	}
	mmDeleteAllUserTokens.defaultExpectation.results = &SessionStorageMockDeleteAllUserTokensResults{err}
	mmDeleteAllUserTokens.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteAllUserTokens.mock
}

// Set uses given function f to mock the SessionStorage.DeleteAllUserTokens method
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Set(f func(ctx context.Context, userID string) (err error)) *SessionStorageMock {
	if mmDeleteAllUserTokens.defaultExpectation != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("Default expectation is already set for the SessionStorage.DeleteAllUserTokens method")
	}

	if len(mmDeleteAllUserTokens.expectations) > 0 {
		mmDeleteAllUserTokens.mock.t.Fatalf("Some expectations are already set for the SessionStorage.DeleteAllUserTokens method")
	}

	mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens = f
	mmDeleteAllUserTokens.mock.funcDeleteAllUserTokensOrigin = minimock.CallerInfo(1)
	return mmDeleteAllUserTokens.mock
}

// When sets expectation for the SessionStorage.DeleteAllUserTokens which will trigger the result defined by the following
// Then helper
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) When(ctx context.Context, userID string) *SessionStorageMockDeleteAllUserTokensExpectation {
	if mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.mock.t.Fatalf("SessionStorageMock.DeleteAllUserTokens mock is already set by Set")
	}

	expectation := &SessionStorageMockDeleteAllUserTokensExpectation{
		mock:               mmDeleteAllUserTokens.mock,
		params:             &SessionStorageMockDeleteAllUserTokensParams{ctx, userID},
		expectationOrigins: SessionStorageMockDeleteAllUserTokensExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteAllUserTokens.expectations = append(mmDeleteAllUserTokens.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.DeleteAllUserTokens return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockDeleteAllUserTokensExpectation) Then(err error) *SessionStorageMock {
	e.results = &SessionStorageMockDeleteAllUserTokensResults{err}
	return e.mock
}

// Times sets number of times SessionStorage.DeleteAllUserTokens should be invoked
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Times(n uint64) *mSessionStorageMockDeleteAllUserTokens {
	if n == 0 {
		mmDeleteAllUserTokens.mock.t.Fatalf("Times of SessionStorageMock.DeleteAllUserTokens mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteAllUserTokens.expectedInvocations, n)
	mmDeleteAllUserTokens.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteAllUserTokens
}

func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) invocationsDone() bool {
	if len(mmDeleteAllUserTokens.expectations) == 0 && mmDeleteAllUserTokens.defaultExpectation == nil && mmDeleteAllUserTokens.mock.funcDeleteAllUserTokens == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteAllUserTokens.mock.afterDeleteAllUserTokensCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteAllUserTokens.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteAllUserTokens implements mm_auth_service.SessionStorage
func (mmDeleteAllUserTokens *SessionStorageMock) DeleteAllUserTokens(ctx context.Context, userID string) (err error) {
	mm_atomic.AddUint64(&mmDeleteAllUserTokens.beforeDeleteAllUserTokensCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteAllUserTokens.afterDeleteAllUserTokensCounter, 1)

	mmDeleteAllUserTokens.t.Helper()

	if mmDeleteAllUserTokens.inspectFuncDeleteAllUserTokens != nil {
		mmDeleteAllUserTokens.inspectFuncDeleteAllUserTokens(ctx, userID)
	}

	mm_params := SessionStorageMockDeleteAllUserTokensParams{ctx, userID}

	// Record call args
	mmDeleteAllUserTokens.DeleteAllUserTokensMock.mutex.Lock()
	mmDeleteAllUserTokens.DeleteAllUserTokensMock.callArgs = append(mmDeleteAllUserTokens.DeleteAllUserTokensMock.callArgs, &mm_params)
	mmDeleteAllUserTokens.DeleteAllUserTokensMock.mutex.Unlock()

	for _, e := range mmDeleteAllUserTokens.DeleteAllUserTokensMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockDeleteAllUserTokensParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteAllUserTokens.t.Errorf("SessionStorageMock.DeleteAllUserTokens got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteAllUserTokens.t.Errorf("SessionStorageMock.DeleteAllUserTokens got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteAllUserTokens.t.Errorf("SessionStorageMock.DeleteAllUserTokens got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteAllUserTokens.DeleteAllUserTokensMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteAllUserTokens.t.Fatal("No results are set for the SessionStorageMock.DeleteAllUserTokens")
		}
		return (*mm_results).err
	}
	if mmDeleteAllUserTokens.funcDeleteAllUserTokens != nil {
		return mmDeleteAllUserTokens.funcDeleteAllUserTokens(ctx, userID)
	}
	mmDeleteAllUserTokens.t.Fatalf("Unexpected call to SessionStorageMock.DeleteAllUserTokens. %v %v", ctx, userID)
	return
}

// DeleteAllUserTokensAfterCounter returns a count of finished SessionStorageMock.DeleteAllUserTokens invocations
func (mmDeleteAllUserTokens *SessionStorageMock) DeleteAllUserTokensAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAllUserTokens.afterDeleteAllUserTokensCounter)
}

// DeleteAllUserTokensBeforeCounter returns a count of SessionStorageMock.DeleteAllUserTokens invocations
func (mmDeleteAllUserTokens *SessionStorageMock) DeleteAllUserTokensBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAllUserTokens.beforeDeleteAllUserTokensCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.DeleteAllUserTokens.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteAllUserTokens *mSessionStorageMockDeleteAllUserTokens) Calls() []*SessionStorageMockDeleteAllUserTokensParams {
	mmDeleteAllUserTokens.mutex.RLock()

	argCopy := make([]*SessionStorageMockDeleteAllUserTokensParams, len(mmDeleteAllUserTokens.callArgs))
	copy(argCopy, mmDeleteAllUserTokens.callArgs)

	mmDeleteAllUserTokens.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteAllUserTokensDone returns true if the count of the DeleteAllUserTokens invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockDeleteAllUserTokensDone() bool {
	if m.DeleteAllUserTokensMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteAllUserTokensMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteAllUserTokensMock.invocationsDone()
}

// MinimockDeleteAllUserTokensInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockDeleteAllUserTokensInspect() {
	for _, e := range m.DeleteAllUserTokensMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteAllUserTokens at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteAllUserTokensCounter := mm_atomic.LoadUint64(&m.afterDeleteAllUserTokensCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteAllUserTokensMock.defaultExpectation != nil && afterDeleteAllUserTokensCounter < 1 {
		if m.DeleteAllUserTokensMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteAllUserTokens at\n%s", m.DeleteAllUserTokensMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteAllUserTokens at\n%s with params: %#v", m.DeleteAllUserTokensMock.defaultExpectation.expectationOrigins.origin, *m.DeleteAllUserTokensMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteAllUserTokens != nil && afterDeleteAllUserTokensCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.DeleteAllUserTokens at\n%s", m.funcDeleteAllUserTokensOrigin)
	}

	if !m.DeleteAllUserTokensMock.invocationsDone() && afterDeleteAllUserTokensCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.DeleteAllUserTokens at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteAllUserTokensMock.expectedInvocations), m.DeleteAllUserTokensMock.expectedInvocationsOrigin, afterDeleteAllUserTokensCounter)
	}
}

type mSessionStorageMockDeleteRefreshToken struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockDeleteRefreshTokenExpectation
	expectations       []*SessionStorageMockDeleteRefreshTokenExpectation

	callArgs []*SessionStorageMockDeleteRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockDeleteRefreshTokenExpectation specifies expectation struct of the SessionStorage.DeleteRefreshToken
type SessionStorageMockDeleteRefreshTokenExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockDeleteRefreshTokenParams
	paramPtrs          *SessionStorageMockDeleteRefreshTokenParamPtrs
	expectationOrigins SessionStorageMockDeleteRefreshTokenExpectationOrigins
	results            *SessionStorageMockDeleteRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockDeleteRefreshTokenParams contains parameters of the SessionStorage.DeleteRefreshToken
type SessionStorageMockDeleteRefreshTokenParams struct {
	ctx context.Context
	jti string
}

// SessionStorageMockDeleteRefreshTokenParamPtrs contains pointers to parameters of the SessionStorage.DeleteRefreshToken
type SessionStorageMockDeleteRefreshTokenParamPtrs struct {
	ctx *context.Context
	jti *string
}

// SessionStorageMockDeleteRefreshTokenResults contains results of the SessionStorage.DeleteRefreshToken
type SessionStorageMockDeleteRefreshTokenResults struct {
	err error
}

// SessionStorageMockDeleteRefreshTokenOrigins contains origins of expectations of the SessionStorage.DeleteRefreshToken
type SessionStorageMockDeleteRefreshTokenExpectationOrigins struct {
	origin    string
	originCtx string
	originJti string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Optional() *mSessionStorageMockDeleteRefreshToken {
	mmDeleteRefreshToken.optional = true
	return mmDeleteRefreshToken
}

// Expect sets up expected params for SessionStorage.DeleteRefreshToken
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Expect(ctx context.Context, jti string) *mSessionStorageMockDeleteRefreshToken {
	if mmDeleteRefreshToken.mock.funcDeleteRefreshToken != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Set")
	}

	if mmDeleteRefreshToken.defaultExpectation == nil {
		mmDeleteRefreshToken.defaultExpectation = &SessionStorageMockDeleteRefreshTokenExpectation{}
	}

	if mmDeleteRefreshToken.defaultExpectation.paramPtrs != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by ExpectParams functions")
	}

	mmDeleteRefreshToken.defaultExpectation.params = &SessionStorageMockDeleteRefreshTokenParams{ctx, jti}
	mmDeleteRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteRefreshToken.expectations {
		if minimock.Equal(e.params, mmDeleteRefreshToken.defaultExpectation.params) {
			mmDeleteRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteRefreshToken.defaultExpectation.params)
		}
	}

	return mmDeleteRefreshToken
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.DeleteRefreshToken
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockDeleteRefreshToken {
	if mmDeleteRefreshToken.mock.funcDeleteRefreshToken != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Set")
	}

	if mmDeleteRefreshToken.defaultExpectation == nil {
		mmDeleteRefreshToken.defaultExpectation = &SessionStorageMockDeleteRefreshTokenExpectation{}
	}

	if mmDeleteRefreshToken.defaultExpectation.params != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Expect")
	}

	if mmDeleteRefreshToken.defaultExpectation.paramPtrs == nil {
		mmDeleteRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockDeleteRefreshTokenParamPtrs{}
	}
	mmDeleteRefreshToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteRefreshToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteRefreshToken
}

// ExpectJtiParam2 sets up expected param jti for SessionStorage.DeleteRefreshToken
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) ExpectJtiParam2(jti string) *mSessionStorageMockDeleteRefreshToken {
	if mmDeleteRefreshToken.mock.funcDeleteRefreshToken != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Set")
	}

	if mmDeleteRefreshToken.defaultExpectation == nil {
		mmDeleteRefreshToken.defaultExpectation = &SessionStorageMockDeleteRefreshTokenExpectation{}
	}

	if mmDeleteRefreshToken.defaultExpectation.params != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Expect")
	}

	if mmDeleteRefreshToken.defaultExpectation.paramPtrs == nil {
		mmDeleteRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockDeleteRefreshTokenParamPtrs{}
	}
	mmDeleteRefreshToken.defaultExpectation.paramPtrs.jti = &jti
	mmDeleteRefreshToken.defaultExpectation.expectationOrigins.originJti = minimock.CallerInfo(1)

	return mmDeleteRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.DeleteRefreshToken
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Inspect(f func(ctx context.Context, jti string)) *mSessionStorageMockDeleteRefreshToken {
	if mmDeleteRefreshToken.mock.inspectFuncDeleteRefreshToken != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.DeleteRefreshToken")
	}

	mmDeleteRefreshToken.mock.inspectFuncDeleteRefreshToken = f

	return mmDeleteRefreshToken
}

// Return sets up results that will be returned by SessionStorage.DeleteRefreshToken
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Return(err error) *SessionStorageMock {
	if mmDeleteRefreshToken.mock.funcDeleteRefreshToken != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Set")
	}

	if mmDeleteRefreshToken.defaultExpectation == nil {
		mmDeleteRefreshToken.defaultExpectation = &SessionStorageMockDeleteRefreshTokenExpectation{mock: mmDeleteRefreshToken.mock}
	}
	mmDeleteRefreshToken.defaultExpectation.results = &SessionStorageMockDeleteRefreshTokenResults{err}
	mmDeleteRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteRefreshToken.mock
}

// Set uses given function f to mock the SessionStorage.DeleteRefreshToken method
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Set(f func(ctx context.Context, jti string) (err error)) *SessionStorageMock {
	if mmDeleteRefreshToken.defaultExpectation != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("Default expectation is already set for the SessionStorage.DeleteRefreshToken method")
	}

	if len(mmDeleteRefreshToken.expectations) > 0 {
		mmDeleteRefreshToken.mock.t.Fatalf("Some expectations are already set for the SessionStorage.DeleteRefreshToken method")
	}

	mmDeleteRefreshToken.mock.funcDeleteRefreshToken = f
	mmDeleteRefreshToken.mock.funcDeleteRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmDeleteRefreshToken.mock
}

// When sets expectation for the SessionStorage.DeleteRefreshToken which will trigger the result defined by the following
// Then helper
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) When(ctx context.Context, jti string) *SessionStorageMockDeleteRefreshTokenExpectation {
	if mmDeleteRefreshToken.mock.funcDeleteRefreshToken != nil {
		mmDeleteRefreshToken.mock.t.Fatalf("SessionStorageMock.DeleteRefreshToken mock is already set by Set")
	}

	expectation := &SessionStorageMockDeleteRefreshTokenExpectation{
		mock:               mmDeleteRefreshToken.mock,
		params:             &SessionStorageMockDeleteRefreshTokenParams{ctx, jti},
		expectationOrigins: SessionStorageMockDeleteRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteRefreshToken.expectations = append(mmDeleteRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.DeleteRefreshToken return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockDeleteRefreshTokenExpectation) Then(err error) *SessionStorageMock {
	e.results = &SessionStorageMockDeleteRefreshTokenResults{err}
	return e.mock
}

// Times sets number of times SessionStorage.DeleteRefreshToken should be invoked
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Times(n uint64) *mSessionStorageMockDeleteRefreshToken {
	if n == 0 {
		mmDeleteRefreshToken.mock.t.Fatalf("Times of SessionStorageMock.DeleteRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteRefreshToken.expectedInvocations, n)
	mmDeleteRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteRefreshToken
}

func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) invocationsDone() bool {
	if len(mmDeleteRefreshToken.expectations) == 0 && mmDeleteRefreshToken.defaultExpectation == nil && mmDeleteRefreshToken.mock.funcDeleteRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteRefreshToken.mock.afterDeleteRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteRefreshToken implements mm_auth_service.SessionStorage
func (mmDeleteRefreshToken *SessionStorageMock) DeleteRefreshToken(ctx context.Context, jti string) (err error) {
	mm_atomic.AddUint64(&mmDeleteRefreshToken.beforeDeleteRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteRefreshToken.afterDeleteRefreshTokenCounter, 1)

	mmDeleteRefreshToken.t.Helper()

	if mmDeleteRefreshToken.inspectFuncDeleteRefreshToken != nil {
		mmDeleteRefreshToken.inspectFuncDeleteRefreshToken(ctx, jti)
	}

	mm_params := SessionStorageMockDeleteRefreshTokenParams{ctx, jti}

	// Record call args
	mmDeleteRefreshToken.DeleteRefreshTokenMock.mutex.Lock()
	mmDeleteRefreshToken.DeleteRefreshTokenMock.callArgs = append(mmDeleteRefreshToken.DeleteRefreshTokenMock.callArgs, &mm_params)
	mmDeleteRefreshToken.DeleteRefreshTokenMock.mutex.Unlock()

	for _, e := range mmDeleteRefreshToken.DeleteRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockDeleteRefreshTokenParams{ctx, jti}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteRefreshToken.t.Errorf("SessionStorageMock.DeleteRefreshToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.jti != nil && !minimock.Equal(*mm_want_ptrs.jti, mm_got.jti) {
				mmDeleteRefreshToken.t.Errorf("SessionStorageMock.DeleteRefreshToken got unexpected parameter jti, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.expectationOrigins.originJti, *mm_want_ptrs.jti, mm_got.jti, minimock.Diff(*mm_want_ptrs.jti, mm_got.jti))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteRefreshToken.t.Errorf("SessionStorageMock.DeleteRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteRefreshToken.DeleteRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteRefreshToken.t.Fatal("No results are set for the SessionStorageMock.DeleteRefreshToken")
		}
		return (*mm_results).err
	}
	if mmDeleteRefreshToken.funcDeleteRefreshToken != nil {
		return mmDeleteRefreshToken.funcDeleteRefreshToken(ctx, jti)
	}
	mmDeleteRefreshToken.t.Fatalf("Unexpected call to SessionStorageMock.DeleteRefreshToken. %v %v", ctx, jti)
	return
}

// DeleteRefreshTokenAfterCounter returns a count of finished SessionStorageMock.DeleteRefreshToken invocations
func (mmDeleteRefreshToken *SessionStorageMock) DeleteRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteRefreshToken.afterDeleteRefreshTokenCounter)
}

// DeleteRefreshTokenBeforeCounter returns a count of SessionStorageMock.DeleteRefreshToken invocations
func (mmDeleteRefreshToken *SessionStorageMock) DeleteRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteRefreshToken.beforeDeleteRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.DeleteRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteRefreshToken *mSessionStorageMockDeleteRefreshToken) Calls() []*SessionStorageMockDeleteRefreshTokenParams {
	mmDeleteRefreshToken.mutex.RLock()

	argCopy := make([]*SessionStorageMockDeleteRefreshTokenParams, len(mmDeleteRefreshToken.callArgs))
	copy(argCopy, mmDeleteRefreshToken.callArgs)

	mmDeleteRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteRefreshTokenDone returns true if the count of the DeleteRefreshToken invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockDeleteRefreshTokenDone() bool {
	if m.DeleteRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteRefreshTokenMock.invocationsDone()
}

// MinimockDeleteRefreshTokenInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockDeleteRefreshTokenInspect() {
	for _, e := range m.DeleteRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterDeleteRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteRefreshTokenMock.defaultExpectation != nil && afterDeleteRefreshTokenCounter < 1 {
		if m.DeleteRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteRefreshToken at\n%s", m.DeleteRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteRefreshToken at\n%s with params: %#v", m.DeleteRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.DeleteRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteRefreshToken != nil && afterDeleteRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.DeleteRefreshToken at\n%s", m.funcDeleteRefreshTokenOrigin)
	}

	if !m.DeleteRefreshTokenMock.invocationsDone() && afterDeleteRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.DeleteRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteRefreshTokenMock.expectedInvocations), m.DeleteRefreshTokenMock.expectedInvocationsOrigin, afterDeleteRefreshTokenCounter)
	}
}

type mSessionStorageMockDeleteTokenFamily struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockDeleteTokenFamilyExpectation
	expectations       []*SessionStorageMockDeleteTokenFamilyExpectation

	callArgs []*SessionStorageMockDeleteTokenFamilyParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockDeleteTokenFamilyExpectation specifies expectation struct of the SessionStorage.DeleteTokenFamily
type SessionStorageMockDeleteTokenFamilyExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockDeleteTokenFamilyParams
	paramPtrs          *SessionStorageMockDeleteTokenFamilyParamPtrs
	expectationOrigins SessionStorageMockDeleteTokenFamilyExpectationOrigins
	results            *SessionStorageMockDeleteTokenFamilyResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockDeleteTokenFamilyParams contains parameters of the SessionStorage.DeleteTokenFamily
type SessionStorageMockDeleteTokenFamilyParams struct {
	ctx    context.Context
	family string
	userID string
}

// SessionStorageMockDeleteTokenFamilyParamPtrs contains pointers to parameters of the SessionStorage.DeleteTokenFamily
type SessionStorageMockDeleteTokenFamilyParamPtrs struct {
	ctx    *context.Context
	family *string
	userID *string
}

// SessionStorageMockDeleteTokenFamilyResults contains results of the SessionStorage.DeleteTokenFamily
type SessionStorageMockDeleteTokenFamilyResults struct {
	err error
}

// SessionStorageMockDeleteTokenFamilyOrigins contains origins of expectations of the SessionStorage.DeleteTokenFamily
type SessionStorageMockDeleteTokenFamilyExpectationOrigins struct {
	origin       string
	originCtx    string
	originFamily string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Optional() *mSessionStorageMockDeleteTokenFamily {
	mmDeleteTokenFamily.optional = true
	return mmDeleteTokenFamily
}

// Expect sets up expected params for SessionStorage.DeleteTokenFamily
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Expect(ctx context.Context, family string, userID string) *mSessionStorageMockDeleteTokenFamily {
	if mmDeleteTokenFamily.mock.funcDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Set")
	}

	if mmDeleteTokenFamily.defaultExpectation == nil {
		mmDeleteTokenFamily.defaultExpectation = &SessionStorageMockDeleteTokenFamilyExpectation{}
	}

	if mmDeleteTokenFamily.defaultExpectation.paramPtrs != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by ExpectParams functions")
	}

	mmDeleteTokenFamily.defaultExpectation.params = &SessionStorageMockDeleteTokenFamilyParams{ctx, family, userID}
	mmDeleteTokenFamily.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteTokenFamily.expectations {
		if minimock.Equal(e.params, mmDeleteTokenFamily.defaultExpectation.params) {
			mmDeleteTokenFamily.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteTokenFamily.defaultExpectation.params)
		}
	}

	return mmDeleteTokenFamily
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.DeleteTokenFamily
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockDeleteTokenFamily {
	if mmDeleteTokenFamily.mock.funcDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Set")
	}

	if mmDeleteTokenFamily.defaultExpectation == nil {
		mmDeleteTokenFamily.defaultExpectation = &SessionStorageMockDeleteTokenFamilyExpectation{}
	}

	if mmDeleteTokenFamily.defaultExpectation.params != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Expect")
	}

	if mmDeleteTokenFamily.defaultExpectation.paramPtrs == nil {
		mmDeleteTokenFamily.defaultExpectation.paramPtrs = &SessionStorageMockDeleteTokenFamilyParamPtrs{}
	}
	mmDeleteTokenFamily.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteTokenFamily.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteTokenFamily
}

// ExpectFamilyParam2 sets up expected param family for SessionStorage.DeleteTokenFamily
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) ExpectFamilyParam2(family string) *mSessionStorageMockDeleteTokenFamily {
	if mmDeleteTokenFamily.mock.funcDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Set")
	}

	if mmDeleteTokenFamily.defaultExpectation == nil {
		mmDeleteTokenFamily.defaultExpectation = &SessionStorageMockDeleteTokenFamilyExpectation{}
	}

	if mmDeleteTokenFamily.defaultExpectation.params != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Expect")
	}

	if mmDeleteTokenFamily.defaultExpectation.paramPtrs == nil {
		mmDeleteTokenFamily.defaultExpectation.paramPtrs = &SessionStorageMockDeleteTokenFamilyParamPtrs{}
	}
	mmDeleteTokenFamily.defaultExpectation.paramPtrs.family = &family
	mmDeleteTokenFamily.defaultExpectation.expectationOrigins.originFamily = minimock.CallerInfo(1)

	return mmDeleteTokenFamily
}

// ExpectUserIDParam3 sets up expected param userID for SessionStorage.DeleteTokenFamily
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) ExpectUserIDParam3(userID string) *mSessionStorageMockDeleteTokenFamily {
	if mmDeleteTokenFamily.mock.funcDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Set")
	}

	if mmDeleteTokenFamily.defaultExpectation == nil {
		mmDeleteTokenFamily.defaultExpectation = &SessionStorageMockDeleteTokenFamilyExpectation{}
	}

	if mmDeleteTokenFamily.defaultExpectation.params != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Expect")
	}

	if mmDeleteTokenFamily.defaultExpectation.paramPtrs == nil {
		mmDeleteTokenFamily.defaultExpectation.paramPtrs = &SessionStorageMockDeleteTokenFamilyParamPtrs{}
	}
	mmDeleteTokenFamily.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteTokenFamily.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteTokenFamily
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.DeleteTokenFamily
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Inspect(f func(ctx context.Context, family string, userID string)) *mSessionStorageMockDeleteTokenFamily {
	if mmDeleteTokenFamily.mock.inspectFuncDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.DeleteTokenFamily")
	}

	mmDeleteTokenFamily.mock.inspectFuncDeleteTokenFamily = f

	return mmDeleteTokenFamily
}

// Return sets up results that will be returned by SessionStorage.DeleteTokenFamily
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Return(err error) *SessionStorageMock {
	if mmDeleteTokenFamily.mock.funcDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Set")
	}

	if mmDeleteTokenFamily.defaultExpectation == nil {
		mmDeleteTokenFamily.defaultExpectation = &SessionStorageMockDeleteTokenFamilyExpectation{mock: mmDeleteTokenFamily.mock}
	}
	mmDeleteTokenFamily.defaultExpectation.results = &SessionStorageMockDeleteTokenFamilyResults{err}
	mmDeleteTokenFamily.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteTokenFamily.mock
}

// Set uses given function f to mock the SessionStorage.DeleteTokenFamily method
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Set(f func(ctx context.Context, family string, userID string) (err error)) *SessionStorageMock {
	if mmDeleteTokenFamily.defaultExpectation != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("Default expectation is already set for the SessionStorage.DeleteTokenFamily method")
	}

	if len(mmDeleteTokenFamily.expectations) > 0 {
		mmDeleteTokenFamily.mock.t.Fatalf("Some expectations are already set for the SessionStorage.DeleteTokenFamily method")
	}

	mmDeleteTokenFamily.mock.funcDeleteTokenFamily = f
	mmDeleteTokenFamily.mock.funcDeleteTokenFamilyOrigin = minimock.CallerInfo(1)
	return mmDeleteTokenFamily.mock
}

// When sets expectation for the SessionStorage.DeleteTokenFamily which will trigger the result defined by the following
// Then helper
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) When(ctx context.Context, family string, userID string) *SessionStorageMockDeleteTokenFamilyExpectation {
	if mmDeleteTokenFamily.mock.funcDeleteTokenFamily != nil {
		mmDeleteTokenFamily.mock.t.Fatalf("SessionStorageMock.DeleteTokenFamily mock is already set by Set")
	}

	expectation := &SessionStorageMockDeleteTokenFamilyExpectation{
		mock:               mmDeleteTokenFamily.mock,
		params:             &SessionStorageMockDeleteTokenFamilyParams{ctx, family, userID},
		expectationOrigins: SessionStorageMockDeleteTokenFamilyExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteTokenFamily.expectations = append(mmDeleteTokenFamily.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.DeleteTokenFamily return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockDeleteTokenFamilyExpectation) Then(err error) *SessionStorageMock {
	e.results = &SessionStorageMockDeleteTokenFamilyResults{err}
	return e.mock
}

// Times sets number of times SessionStorage.DeleteTokenFamily should be invoked
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Times(n uint64) *mSessionStorageMockDeleteTokenFamily {
	if n == 0 {
		mmDeleteTokenFamily.mock.t.Fatalf("Times of SessionStorageMock.DeleteTokenFamily mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteTokenFamily.expectedInvocations, n)
	mmDeleteTokenFamily.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteTokenFamily
}

func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) invocationsDone() bool {
	if len(mmDeleteTokenFamily.expectations) == 0 && mmDeleteTokenFamily.defaultExpectation == nil && mmDeleteTokenFamily.mock.funcDeleteTokenFamily == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteTokenFamily.mock.afterDeleteTokenFamilyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteTokenFamily.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteTokenFamily implements mm_auth_service.SessionStorage
func (mmDeleteTokenFamily *SessionStorageMock) DeleteTokenFamily(ctx context.Context, family string, userID string) (err error) {
	mm_atomic.AddUint64(&mmDeleteTokenFamily.beforeDeleteTokenFamilyCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteTokenFamily.afterDeleteTokenFamilyCounter, 1)

	mmDeleteTokenFamily.t.Helper()

	if mmDeleteTokenFamily.inspectFuncDeleteTokenFamily != nil {
		mmDeleteTokenFamily.inspectFuncDeleteTokenFamily(ctx, family, userID)
	}

	mm_params := SessionStorageMockDeleteTokenFamilyParams{ctx, family, userID}

	// Record call args
	mmDeleteTokenFamily.DeleteTokenFamilyMock.mutex.Lock()
	mmDeleteTokenFamily.DeleteTokenFamilyMock.callArgs = append(mmDeleteTokenFamily.DeleteTokenFamilyMock.callArgs, &mm_params)
	mmDeleteTokenFamily.DeleteTokenFamilyMock.mutex.Unlock()

	for _, e := range mmDeleteTokenFamily.DeleteTokenFamilyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockDeleteTokenFamilyParams{ctx, family, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteTokenFamily.t.Errorf("SessionStorageMock.DeleteTokenFamily got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.family != nil && !minimock.Equal(*mm_want_ptrs.family, mm_got.family) {
				mmDeleteTokenFamily.t.Errorf("SessionStorageMock.DeleteTokenFamily got unexpected parameter family, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.expectationOrigins.originFamily, *mm_want_ptrs.family, mm_got.family, minimock.Diff(*mm_want_ptrs.family, mm_got.family))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteTokenFamily.t.Errorf("SessionStorageMock.DeleteTokenFamily got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteTokenFamily.t.Errorf("SessionStorageMock.DeleteTokenFamily got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteTokenFamily.DeleteTokenFamilyMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteTokenFamily.t.Fatal("No results are set for the SessionStorageMock.DeleteTokenFamily")
		}
		return (*mm_results).err
	}
	if mmDeleteTokenFamily.funcDeleteTokenFamily != nil {
		return mmDeleteTokenFamily.funcDeleteTokenFamily(ctx, family, userID)
	}
	mmDeleteTokenFamily.t.Fatalf("Unexpected call to SessionStorageMock.DeleteTokenFamily. %v %v %v", ctx, family, userID)
	return
}

// DeleteTokenFamilyAfterCounter returns a count of finished SessionStorageMock.DeleteTokenFamily invocations
func (mmDeleteTokenFamily *SessionStorageMock) DeleteTokenFamilyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteTokenFamily.afterDeleteTokenFamilyCounter)
}

// DeleteTokenFamilyBeforeCounter returns a count of SessionStorageMock.DeleteTokenFamily invocations
func (mmDeleteTokenFamily *SessionStorageMock) DeleteTokenFamilyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteTokenFamily.beforeDeleteTokenFamilyCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.DeleteTokenFamily.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteTokenFamily *mSessionStorageMockDeleteTokenFamily) Calls() []*SessionStorageMockDeleteTokenFamilyParams {
	mmDeleteTokenFamily.mutex.RLock()

	argCopy := make([]*SessionStorageMockDeleteTokenFamilyParams, len(mmDeleteTokenFamily.callArgs))
	copy(argCopy, mmDeleteTokenFamily.callArgs)

	mmDeleteTokenFamily.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteTokenFamilyDone returns true if the count of the DeleteTokenFamily invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockDeleteTokenFamilyDone() bool {
	if m.DeleteTokenFamilyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteTokenFamilyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteTokenFamilyMock.invocationsDone()
}

// MinimockDeleteTokenFamilyInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockDeleteTokenFamilyInspect() {
	for _, e := range m.DeleteTokenFamilyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteTokenFamily at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteTokenFamilyCounter := mm_atomic.LoadUint64(&m.afterDeleteTokenFamilyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteTokenFamilyMock.defaultExpectation != nil && afterDeleteTokenFamilyCounter < 1 {
		if m.DeleteTokenFamilyMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteTokenFamily at\n%s", m.DeleteTokenFamilyMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteTokenFamily at\n%s with params: %#v", m.DeleteTokenFamilyMock.defaultExpectation.expectationOrigins.origin, *m.DeleteTokenFamilyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteTokenFamily != nil && afterDeleteTokenFamilyCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.DeleteTokenFamily at\n%s", m.funcDeleteTokenFamilyOrigin)
	}

	if !m.DeleteTokenFamilyMock.invocationsDone() && afterDeleteTokenFamilyCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.DeleteTokenFamily at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteTokenFamilyMock.expectedInvocations), m.DeleteTokenFamilyMock.expectedInvocationsOrigin, afterDeleteTokenFamilyCounter)
	}
}

type mSessionStorageMockGetRefreshToken struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockGetRefreshTokenExpectation
	expectations       []*SessionStorageMockGetRefreshTokenExpectation

	callArgs []*SessionStorageMockGetRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockGetRefreshTokenExpectation specifies expectation struct of the SessionStorage.GetRefreshToken
type SessionStorageMockGetRefreshTokenExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockGetRefreshTokenParams
	paramPtrs          *SessionStorageMockGetRefreshTokenParamPtrs
	expectationOrigins SessionStorageMockGetRefreshTokenExpectationOrigins
	results            *SessionStorageMockGetRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockGetRefreshTokenParams contains parameters of the SessionStorage.GetRefreshToken
type SessionStorageMockGetRefreshTokenParams struct {
	ctx context.Context
	jti string
}

// SessionStorageMockGetRefreshTokenParamPtrs contains pointers to parameters of the SessionStorage.GetRefreshToken
type SessionStorageMockGetRefreshTokenParamPtrs struct {
	ctx *context.Context
	jti *string
}

// SessionStorageMockGetRefreshTokenResults contains results of the SessionStorage.GetRefreshToken
type SessionStorageMockGetRefreshTokenResults struct {
	rp1 *domain.RefreshTokenData
	err error
}

// SessionStorageMockGetRefreshTokenOrigins contains origins of expectations of the SessionStorage.GetRefreshToken
type SessionStorageMockGetRefreshTokenExpectationOrigins struct {
	origin    string
	originCtx string
	originJti string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Optional() *mSessionStorageMockGetRefreshToken {
	mmGetRefreshToken.optional = true
	return mmGetRefreshToken
}

// Expect sets up expected params for SessionStorage.GetRefreshToken
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Expect(ctx context.Context, jti string) *mSessionStorageMockGetRefreshToken {
	if mmGetRefreshToken.mock.funcGetRefreshToken != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Set")
	}

	if mmGetRefreshToken.defaultExpectation == nil {
		mmGetRefreshToken.defaultExpectation = &SessionStorageMockGetRefreshTokenExpectation{}
	}

	if mmGetRefreshToken.defaultExpectation.paramPtrs != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by ExpectParams functions")
	}

	mmGetRefreshToken.defaultExpectation.params = &SessionStorageMockGetRefreshTokenParams{ctx, jti}
	mmGetRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetRefreshToken.expectations {
		if minimock.Equal(e.params, mmGetRefreshToken.defaultExpectation.params) {
			mmGetRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRefreshToken.defaultExpectation.params)
		}
	}

	return mmGetRefreshToken
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.GetRefreshToken
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockGetRefreshToken {
	if mmGetRefreshToken.mock.funcGetRefreshToken != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Set")
	}

	if mmGetRefreshToken.defaultExpectation == nil {
		mmGetRefreshToken.defaultExpectation = &SessionStorageMockGetRefreshTokenExpectation{}
	}

	if mmGetRefreshToken.defaultExpectation.params != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Expect")
	}

	if mmGetRefreshToken.defaultExpectation.paramPtrs == nil {
		mmGetRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockGetRefreshTokenParamPtrs{}
	}
	mmGetRefreshToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetRefreshToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetRefreshToken
}

// ExpectJtiParam2 sets up expected param jti for SessionStorage.GetRefreshToken
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) ExpectJtiParam2(jti string) *mSessionStorageMockGetRefreshToken {
	if mmGetRefreshToken.mock.funcGetRefreshToken != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Set")
	}

	if mmGetRefreshToken.defaultExpectation == nil {
		mmGetRefreshToken.defaultExpectation = &SessionStorageMockGetRefreshTokenExpectation{}
	}

	if mmGetRefreshToken.defaultExpectation.params != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Expect")
	}

	if mmGetRefreshToken.defaultExpectation.paramPtrs == nil {
		mmGetRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockGetRefreshTokenParamPtrs{}
	}
	mmGetRefreshToken.defaultExpectation.paramPtrs.jti = &jti
	mmGetRefreshToken.defaultExpectation.expectationOrigins.originJti = minimock.CallerInfo(1)

	return mmGetRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.GetRefreshToken
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Inspect(f func(ctx context.Context, jti string)) *mSessionStorageMockGetRefreshToken {
	if mmGetRefreshToken.mock.inspectFuncGetRefreshToken != nil {
		mmGetRefreshToken.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.GetRefreshToken")
	}

	mmGetRefreshToken.mock.inspectFuncGetRefreshToken = f

	return mmGetRefreshToken
}

// Return sets up results that will be returned by SessionStorage.GetRefreshToken
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Return(rp1 *domain.RefreshTokenData, err error) *SessionStorageMock {
	if mmGetRefreshToken.mock.funcGetRefreshToken != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Set")
	}

	if mmGetRefreshToken.defaultExpectation == nil {
		mmGetRefreshToken.defaultExpectation = &SessionStorageMockGetRefreshTokenExpectation{mock: mmGetRefreshToken.mock}
	}
	mmGetRefreshToken.defaultExpectation.results = &SessionStorageMockGetRefreshTokenResults{rp1, err}
	mmGetRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetRefreshToken.mock
}

// Set uses given function f to mock the SessionStorage.GetRefreshToken method
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Set(f func(ctx context.Context, jti string) (rp1 *domain.RefreshTokenData, err error)) *SessionStorageMock {
	if mmGetRefreshToken.defaultExpectation != nil {
		mmGetRefreshToken.mock.t.Fatalf("Default expectation is already set for the SessionStorage.GetRefreshToken method")
	}

	if len(mmGetRefreshToken.expectations) > 0 {
		mmGetRefreshToken.mock.t.Fatalf("Some expectations are already set for the SessionStorage.GetRefreshToken method")
	}

	mmGetRefreshToken.mock.funcGetRefreshToken = f
	mmGetRefreshToken.mock.funcGetRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmGetRefreshToken.mock
}

// When sets expectation for the SessionStorage.GetRefreshToken which will trigger the result defined by the following
// Then helper
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) When(ctx context.Context, jti string) *SessionStorageMockGetRefreshTokenExpectation {
	if mmGetRefreshToken.mock.funcGetRefreshToken != nil {
		mmGetRefreshToken.mock.t.Fatalf("SessionStorageMock.GetRefreshToken mock is already set by Set")
	}

	expectation := &SessionStorageMockGetRefreshTokenExpectation{
		mock:               mmGetRefreshToken.mock,
		params:             &SessionStorageMockGetRefreshTokenParams{ctx, jti},
		expectationOrigins: SessionStorageMockGetRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetRefreshToken.expectations = append(mmGetRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.GetRefreshToken return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockGetRefreshTokenExpectation) Then(rp1 *domain.RefreshTokenData, err error) *SessionStorageMock {
	e.results = &SessionStorageMockGetRefreshTokenResults{rp1, err}
	return e.mock
}

// Times sets number of times SessionStorage.GetRefreshToken should be invoked
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Times(n uint64) *mSessionStorageMockGetRefreshToken {
	if n == 0 {
		mmGetRefreshToken.mock.t.Fatalf("Times of SessionStorageMock.GetRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetRefreshToken.expectedInvocations, n)
	mmGetRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetRefreshToken
}

func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) invocationsDone() bool {
	if len(mmGetRefreshToken.expectations) == 0 && mmGetRefreshToken.defaultExpectation == nil && mmGetRefreshToken.mock.funcGetRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetRefreshToken.mock.afterGetRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetRefreshToken implements mm_auth_service.SessionStorage
func (mmGetRefreshToken *SessionStorageMock) GetRefreshToken(ctx context.Context, jti string) (rp1 *domain.RefreshTokenData, err error) {
	mm_atomic.AddUint64(&mmGetRefreshToken.beforeGetRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRefreshToken.afterGetRefreshTokenCounter, 1)

	mmGetRefreshToken.t.Helper()

	if mmGetRefreshToken.inspectFuncGetRefreshToken != nil {
		mmGetRefreshToken.inspectFuncGetRefreshToken(ctx, jti)
	}

	mm_params := SessionStorageMockGetRefreshTokenParams{ctx, jti}

	// Record call args
	mmGetRefreshToken.GetRefreshTokenMock.mutex.Lock()
	mmGetRefreshToken.GetRefreshTokenMock.callArgs = append(mmGetRefreshToken.GetRefreshTokenMock.callArgs, &mm_params)
	mmGetRefreshToken.GetRefreshTokenMock.mutex.Unlock()

	for _, e := range mmGetRefreshToken.GetRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockGetRefreshTokenParams{ctx, jti}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetRefreshToken.t.Errorf("SessionStorageMock.GetRefreshToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.jti != nil && !minimock.Equal(*mm_want_ptrs.jti, mm_got.jti) {
				mmGetRefreshToken.t.Errorf("SessionStorageMock.GetRefreshToken got unexpected parameter jti, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.expectationOrigins.originJti, *mm_want_ptrs.jti, mm_got.jti, minimock.Diff(*mm_want_ptrs.jti, mm_got.jti))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRefreshToken.t.Errorf("SessionStorageMock.GetRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRefreshToken.GetRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRefreshToken.t.Fatal("No results are set for the SessionStorageMock.GetRefreshToken")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmGetRefreshToken.funcGetRefreshToken != nil {
		return mmGetRefreshToken.funcGetRefreshToken(ctx, jti)
	}
	mmGetRefreshToken.t.Fatalf("Unexpected call to SessionStorageMock.GetRefreshToken. %v %v", ctx, jti)
	return
}

// GetRefreshTokenAfterCounter returns a count of finished SessionStorageMock.GetRefreshToken invocations
func (mmGetRefreshToken *SessionStorageMock) GetRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRefreshToken.afterGetRefreshTokenCounter)
}

// GetRefreshTokenBeforeCounter returns a count of SessionStorageMock.GetRefreshToken invocations
func (mmGetRefreshToken *SessionStorageMock) GetRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRefreshToken.beforeGetRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.GetRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRefreshToken *mSessionStorageMockGetRefreshToken) Calls() []*SessionStorageMockGetRefreshTokenParams {
	mmGetRefreshToken.mutex.RLock()

	argCopy := make([]*SessionStorageMockGetRefreshTokenParams, len(mmGetRefreshToken.callArgs))
	copy(argCopy, mmGetRefreshToken.callArgs)

	mmGetRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockGetRefreshTokenDone returns true if the count of the GetRefreshToken invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockGetRefreshTokenDone() bool {
	if m.GetRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetRefreshTokenMock.invocationsDone()
}

// MinimockGetRefreshTokenInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockGetRefreshTokenInspect() {
	for _, e := range m.GetRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.GetRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterGetRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetRefreshTokenMock.defaultExpectation != nil && afterGetRefreshTokenCounter < 1 {
		if m.GetRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.GetRefreshToken at\n%s", m.GetRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.GetRefreshToken at\n%s with params: %#v", m.GetRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.GetRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRefreshToken != nil && afterGetRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.GetRefreshToken at\n%s", m.funcGetRefreshTokenOrigin)
	}

	if !m.GetRefreshTokenMock.invocationsDone() && afterGetRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.GetRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetRefreshTokenMock.expectedInvocations), m.GetRefreshTokenMock.expectedInvocationsOrigin, afterGetRefreshTokenCounter)
	}
}

type mSessionStorageMockStoreRefreshToken struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockStoreRefreshTokenExpectation
	expectations       []*SessionStorageMockStoreRefreshTokenExpectation

	callArgs []*SessionStorageMockStoreRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockStoreRefreshTokenExpectation specifies expectation struct of the SessionStorage.StoreRefreshToken
type SessionStorageMockStoreRefreshTokenExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockStoreRefreshTokenParams
	paramPtrs          *SessionStorageMockStoreRefreshTokenParamPtrs
	expectationOrigins SessionStorageMockStoreRefreshTokenExpectationOrigins
	results            *SessionStorageMockStoreRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockStoreRefreshTokenParams contains parameters of the SessionStorage.StoreRefreshToken
type SessionStorageMockStoreRefreshTokenParams struct {
	ctx         context.Context
	jti         string
	userID      string
	tokenFamily string
	ttl         time.Duration
}

// SessionStorageMockStoreRefreshTokenParamPtrs contains pointers to parameters of the SessionStorage.StoreRefreshToken
type SessionStorageMockStoreRefreshTokenParamPtrs struct {
	ctx         *context.Context
	jti         *string
	userID      *string
	tokenFamily *string
	ttl         *time.Duration
}

// SessionStorageMockStoreRefreshTokenResults contains results of the SessionStorage.StoreRefreshToken
type SessionStorageMockStoreRefreshTokenResults struct {
	err error
}

// SessionStorageMockStoreRefreshTokenOrigins contains origins of expectations of the SessionStorage.StoreRefreshToken
type SessionStorageMockStoreRefreshTokenExpectationOrigins struct {
	origin            string
	originCtx         string
	originJti         string
	originUserID      string
	originTokenFamily string
	originTtl         string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Optional() *mSessionStorageMockStoreRefreshToken {
	mmStoreRefreshToken.optional = true
	return mmStoreRefreshToken
}

// Expect sets up expected params for SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Expect(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{}
	}

	if mmStoreRefreshToken.defaultExpectation.paramPtrs != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by ExpectParams functions")
	}

	mmStoreRefreshToken.defaultExpectation.params = &SessionStorageMockStoreRefreshTokenParams{ctx, jti, userID, tokenFamily, ttl}
	mmStoreRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStoreRefreshToken.expectations {
		if minimock.Equal(e.params, mmStoreRefreshToken.defaultExpectation.params) {
			mmStoreRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStoreRefreshToken.defaultExpectation.params)
		}
	}

	return mmStoreRefreshToken
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{}
	}

	if mmStoreRefreshToken.defaultExpectation.params != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Expect")
	}

	if mmStoreRefreshToken.defaultExpectation.paramPtrs == nil {
		mmStoreRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockStoreRefreshTokenParamPtrs{}
	}
	mmStoreRefreshToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmStoreRefreshToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStoreRefreshToken
}

// ExpectJtiParam2 sets up expected param jti for SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) ExpectJtiParam2(jti string) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{}
	}

	if mmStoreRefreshToken.defaultExpectation.params != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Expect")
	}

	if mmStoreRefreshToken.defaultExpectation.paramPtrs == nil {
		mmStoreRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockStoreRefreshTokenParamPtrs{}
	}
	mmStoreRefreshToken.defaultExpectation.paramPtrs.jti = &jti
	mmStoreRefreshToken.defaultExpectation.expectationOrigins.originJti = minimock.CallerInfo(1)

	return mmStoreRefreshToken
}

// ExpectUserIDParam3 sets up expected param userID for SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) ExpectUserIDParam3(userID string) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{}
	}

	if mmStoreRefreshToken.defaultExpectation.params != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Expect")
	}

	if mmStoreRefreshToken.defaultExpectation.paramPtrs == nil {
		mmStoreRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockStoreRefreshTokenParamPtrs{}
	}
	mmStoreRefreshToken.defaultExpectation.paramPtrs.userID = &userID
	mmStoreRefreshToken.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmStoreRefreshToken
}

// ExpectTokenFamilyParam4 sets up expected param tokenFamily for SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) ExpectTokenFamilyParam4(tokenFamily string) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{}
	}

	if mmStoreRefreshToken.defaultExpectation.params != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Expect")
	}

	if mmStoreRefreshToken.defaultExpectation.paramPtrs == nil {
		mmStoreRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockStoreRefreshTokenParamPtrs{}
	}
	mmStoreRefreshToken.defaultExpectation.paramPtrs.tokenFamily = &tokenFamily
	mmStoreRefreshToken.defaultExpectation.expectationOrigins.originTokenFamily = minimock.CallerInfo(1)

	return mmStoreRefreshToken
}

// ExpectTtlParam5 sets up expected param ttl for SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) ExpectTtlParam5(ttl time.Duration) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{}
	}

	if mmStoreRefreshToken.defaultExpectation.params != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Expect")
	}

	if mmStoreRefreshToken.defaultExpectation.paramPtrs == nil {
		mmStoreRefreshToken.defaultExpectation.paramPtrs = &SessionStorageMockStoreRefreshTokenParamPtrs{}
	}
	mmStoreRefreshToken.defaultExpectation.paramPtrs.ttl = &ttl
	mmStoreRefreshToken.defaultExpectation.expectationOrigins.originTtl = minimock.CallerInfo(1)

	return mmStoreRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Inspect(f func(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration)) *mSessionStorageMockStoreRefreshToken {
	if mmStoreRefreshToken.mock.inspectFuncStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.StoreRefreshToken")
	}

	mmStoreRefreshToken.mock.inspectFuncStoreRefreshToken = f

	return mmStoreRefreshToken
}

// Return sets up results that will be returned by SessionStorage.StoreRefreshToken
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Return(err error) *SessionStorageMock {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	if mmStoreRefreshToken.defaultExpectation == nil {
		mmStoreRefreshToken.defaultExpectation = &SessionStorageMockStoreRefreshTokenExpectation{mock: mmStoreRefreshToken.mock}
	}
	mmStoreRefreshToken.defaultExpectation.results = &SessionStorageMockStoreRefreshTokenResults{err}
	mmStoreRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStoreRefreshToken.mock
}

// Set uses given function f to mock the SessionStorage.StoreRefreshToken method
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Set(f func(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration) (err error)) *SessionStorageMock {
	if mmStoreRefreshToken.defaultExpectation != nil {
		mmStoreRefreshToken.mock.t.Fatalf("Default expectation is already set for the SessionStorage.StoreRefreshToken method")
	}

	if len(mmStoreRefreshToken.expectations) > 0 {
		mmStoreRefreshToken.mock.t.Fatalf("Some expectations are already set for the SessionStorage.StoreRefreshToken method")
	}

	mmStoreRefreshToken.mock.funcStoreRefreshToken = f
	mmStoreRefreshToken.mock.funcStoreRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmStoreRefreshToken.mock
}

// When sets expectation for the SessionStorage.StoreRefreshToken which will trigger the result defined by the following
// Then helper
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) When(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration) *SessionStorageMockStoreRefreshTokenExpectation {
	if mmStoreRefreshToken.mock.funcStoreRefreshToken != nil {
		mmStoreRefreshToken.mock.t.Fatalf("SessionStorageMock.StoreRefreshToken mock is already set by Set")
	}

	expectation := &SessionStorageMockStoreRefreshTokenExpectation{
		mock:               mmStoreRefreshToken.mock,
		params:             &SessionStorageMockStoreRefreshTokenParams{ctx, jti, userID, tokenFamily, ttl},
		expectationOrigins: SessionStorageMockStoreRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStoreRefreshToken.expectations = append(mmStoreRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.StoreRefreshToken return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockStoreRefreshTokenExpectation) Then(err error) *SessionStorageMock {
	e.results = &SessionStorageMockStoreRefreshTokenResults{err}
	return e.mock
}

// Times sets number of times SessionStorage.StoreRefreshToken should be invoked
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Times(n uint64) *mSessionStorageMockStoreRefreshToken {
	if n == 0 {
		mmStoreRefreshToken.mock.t.Fatalf("Times of SessionStorageMock.StoreRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStoreRefreshToken.expectedInvocations, n)
	mmStoreRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStoreRefreshToken
}

func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) invocationsDone() bool {
	if len(mmStoreRefreshToken.expectations) == 0 && mmStoreRefreshToken.defaultExpectation == nil && mmStoreRefreshToken.mock.funcStoreRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStoreRefreshToken.mock.afterStoreRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStoreRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StoreRefreshToken implements mm_auth_service.SessionStorage
func (mmStoreRefreshToken *SessionStorageMock) StoreRefreshToken(ctx context.Context, jti string, userID string, tokenFamily string, ttl time.Duration) (err error) {
	mm_atomic.AddUint64(&mmStoreRefreshToken.beforeStoreRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmStoreRefreshToken.afterStoreRefreshTokenCounter, 1)

	mmStoreRefreshToken.t.Helper()

	if mmStoreRefreshToken.inspectFuncStoreRefreshToken != nil {
		mmStoreRefreshToken.inspectFuncStoreRefreshToken(ctx, jti, userID, tokenFamily, ttl)
	}

	mm_params := SessionStorageMockStoreRefreshTokenParams{ctx, jti, userID, tokenFamily, ttl}

	// Record call args
	mmStoreRefreshToken.StoreRefreshTokenMock.mutex.Lock()
	mmStoreRefreshToken.StoreRefreshTokenMock.callArgs = append(mmStoreRefreshToken.StoreRefreshTokenMock.callArgs, &mm_params)
	mmStoreRefreshToken.StoreRefreshTokenMock.mutex.Unlock()

	for _, e := range mmStoreRefreshToken.StoreRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockStoreRefreshTokenParams{ctx, jti, userID, tokenFamily, ttl}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStoreRefreshToken.t.Errorf("SessionStorageMock.StoreRefreshToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.jti != nil && !minimock.Equal(*mm_want_ptrs.jti, mm_got.jti) {
				mmStoreRefreshToken.t.Errorf("SessionStorageMock.StoreRefreshToken got unexpected parameter jti, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.originJti, *mm_want_ptrs.jti, mm_got.jti, minimock.Diff(*mm_want_ptrs.jti, mm_got.jti))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmStoreRefreshToken.t.Errorf("SessionStorageMock.StoreRefreshToken got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.tokenFamily != nil && !minimock.Equal(*mm_want_ptrs.tokenFamily, mm_got.tokenFamily) {
				mmStoreRefreshToken.t.Errorf("SessionStorageMock.StoreRefreshToken got unexpected parameter tokenFamily, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.originTokenFamily, *mm_want_ptrs.tokenFamily, mm_got.tokenFamily, minimock.Diff(*mm_want_ptrs.tokenFamily, mm_got.tokenFamily))
			}

			if mm_want_ptrs.ttl != nil && !minimock.Equal(*mm_want_ptrs.ttl, mm_got.ttl) {
				mmStoreRefreshToken.t.Errorf("SessionStorageMock.StoreRefreshToken got unexpected parameter ttl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.originTtl, *mm_want_ptrs.ttl, mm_got.ttl, minimock.Diff(*mm_want_ptrs.ttl, mm_got.ttl))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStoreRefreshToken.t.Errorf("SessionStorageMock.StoreRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStoreRefreshToken.StoreRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmStoreRefreshToken.t.Fatal("No results are set for the SessionStorageMock.StoreRefreshToken")
		}
		return (*mm_results).err
	}
	if mmStoreRefreshToken.funcStoreRefreshToken != nil {
		return mmStoreRefreshToken.funcStoreRefreshToken(ctx, jti, userID, tokenFamily, ttl)
	}
	mmStoreRefreshToken.t.Fatalf("Unexpected call to SessionStorageMock.StoreRefreshToken. %v %v %v %v %v", ctx, jti, userID, tokenFamily, ttl)
	return
}

// StoreRefreshTokenAfterCounter returns a count of finished SessionStorageMock.StoreRefreshToken invocations
func (mmStoreRefreshToken *SessionStorageMock) StoreRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStoreRefreshToken.afterStoreRefreshTokenCounter)
}

// StoreRefreshTokenBeforeCounter returns a count of SessionStorageMock.StoreRefreshToken invocations
func (mmStoreRefreshToken *SessionStorageMock) StoreRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStoreRefreshToken.beforeStoreRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.StoreRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStoreRefreshToken *mSessionStorageMockStoreRefreshToken) Calls() []*SessionStorageMockStoreRefreshTokenParams {
	mmStoreRefreshToken.mutex.RLock()

	argCopy := make([]*SessionStorageMockStoreRefreshTokenParams, len(mmStoreRefreshToken.callArgs))
	copy(argCopy, mmStoreRefreshToken.callArgs)

	mmStoreRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockStoreRefreshTokenDone returns true if the count of the StoreRefreshToken invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockStoreRefreshTokenDone() bool {
	if m.StoreRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StoreRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StoreRefreshTokenMock.invocationsDone()
}

// MinimockStoreRefreshTokenInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockStoreRefreshTokenInspect() {
	for _, e := range m.StoreRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.StoreRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStoreRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterStoreRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StoreRefreshTokenMock.defaultExpectation != nil && afterStoreRefreshTokenCounter < 1 {
		if m.StoreRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.StoreRefreshToken at\n%s", m.StoreRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.StoreRefreshToken at\n%s with params: %#v", m.StoreRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.StoreRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStoreRefreshToken != nil && afterStoreRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.StoreRefreshToken at\n%s", m.funcStoreRefreshTokenOrigin)
	}

	if !m.StoreRefreshTokenMock.invocationsDone() && afterStoreRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.StoreRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StoreRefreshTokenMock.expectedInvocations), m.StoreRefreshTokenMock.expectedInvocationsOrigin, afterStoreRefreshTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SessionStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteAllUserTokensInspect()

			m.MinimockDeleteRefreshTokenInspect()

			m.MinimockDeleteTokenFamilyInspect()

			m.MinimockGetRefreshTokenInspect()

			m.MinimockStoreRefreshTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SessionStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SessionStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteAllUserTokensDone() &&
		m.MinimockDeleteRefreshTokenDone() &&
		m.MinimockDeleteTokenFamilyDone() &&
		m.MinimockGetRefreshTokenDone() &&
		m.MinimockStoreRefreshTokenDone()
}
