// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mpc_api/mpc_service.proto

package mpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShareIndex    int32                  `protobuf:"varint,2,opt,name=share_index,json=shareIndex,proto3" json:"share_index,omitempty"`
	ShareData     []byte                 `protobuf:"bytes,3,opt,name=share_data,json=shareData,proto3" json:"share_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreShareRequest) Reset() {
	*x = StoreShareRequest{}
	mi := &file_mpc_api_mpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreShareRequest) ProtoMessage() {}

func (x *StoreShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_api_mpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreShareRequest.ProtoReflect.Descriptor instead.
func (*StoreShareRequest) Descriptor() ([]byte, []int) {
	return file_mpc_api_mpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *StoreShareRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreShareRequest) GetShareIndex() int32 {
	if x != nil {
		return x.ShareIndex
	}
	return 0
}

func (x *StoreShareRequest) GetShareData() []byte {
	if x != nil {
		return x.ShareData
	}
	return nil
}

type StoreShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreShareResponse) Reset() {
	*x = StoreShareResponse{}
	mi := &file_mpc_api_mpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreShareResponse) ProtoMessage() {}

func (x *StoreShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_api_mpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreShareResponse.ProtoReflect.Descriptor instead.
func (*StoreShareResponse) Descriptor() ([]byte, []int) {
	return file_mpc_api_mpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *StoreShareResponse) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

type RetrieveShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShareIndex    int32                  `protobuf:"varint,2,opt,name=share_index,json=shareIndex,proto3" json:"share_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveShareRequest) Reset() {
	*x = RetrieveShareRequest{}
	mi := &file_mpc_api_mpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveShareRequest) ProtoMessage() {}

func (x *RetrieveShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_api_mpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveShareRequest.ProtoReflect.Descriptor instead.
func (*RetrieveShareRequest) Descriptor() ([]byte, []int) {
	return file_mpc_api_mpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveShareRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetrieveShareRequest) GetShareIndex() int32 {
	if x != nil {
		return x.ShareIndex
	}
	return 0
}

type RetrieveShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareData     []byte                 `protobuf:"bytes,1,opt,name=share_data,json=shareData,proto3" json:"share_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveShareResponse) Reset() {
	*x = RetrieveShareResponse{}
	mi := &file_mpc_api_mpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveShareResponse) ProtoMessage() {}

func (x *RetrieveShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_api_mpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveShareResponse.ProtoReflect.Descriptor instead.
func (*RetrieveShareResponse) Descriptor() ([]byte, []int) {
	return file_mpc_api_mpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveShareResponse) GetShareData() []byte {
	if x != nil {
		return x.ShareData
	}
	return nil
}

type DeleteShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShareRequest) Reset() {
	*x = DeleteShareRequest{}
	mi := &file_mpc_api_mpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShareRequest) ProtoMessage() {}

func (x *DeleteShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_api_mpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShareRequest.ProtoReflect.Descriptor instead.
func (*DeleteShareRequest) Descriptor() ([]byte, []int) {
	return file_mpc_api_mpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteShareRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShareResponse) Reset() {
	*x = DeleteShareResponse{}
	mi := &file_mpc_api_mpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShareResponse) ProtoMessage() {}

func (x *DeleteShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_api_mpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShareResponse.ProtoReflect.Descriptor instead.
func (*DeleteShareResponse) Descriptor() ([]byte, []int) {
	return file_mpc_api_mpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteShareResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_mpc_api_mpc_service_proto protoreflect.FileDescriptor

const file_mpc_api_mpc_service_proto_rawDesc = "" +
	"\n" +
	"\x19mpc_api/mpc_service.proto\x12\ampc_api\"l\n" +
	"\x11StoreShareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vshare_index\x18\x02 \x01(\x05R\n" +
	"shareIndex\x12\x1d\n" +
	"\n" +
	"share_data\x18\x03 \x01(\fR\tshareData\"/\n" +
	"\x12StoreShareResponse\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\"P\n" +
	"\x14RetrieveShareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vshare_index\x18\x02 \x01(\x05R\n" +
	"shareIndex\"6\n" +
	"\x15RetrieveShareResponse\x12\x1d\n" +
	"\n" +
	"share_data\x18\x01 \x01(\fR\tshareData\"-\n" +
	"\x12DeleteShareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x13DeleteShareResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount2\xf1\x01\n" +
	"\x0eMPCNodeService\x12E\n" +
	"\n" +
	"StoreShare\x12\x1a.mpc_api.StoreShareRequest\x1a\x1b.mpc_api.StoreShareResponse\x12N\n" +
	"\rRetrieveShare\x12\x1d.mpc_api.RetrieveShareRequest\x1a\x1e.mpc_api.RetrieveShareResponse\x12H\n" +
	"\vDeleteShare\x12\x1b.mpc_api.DeleteShareRequest\x1a\x1c.mpc_api.DeleteShareResponseB2Z0github.com/vbncursed/vkr/mpc/internal/pb/mpc_apib\x06proto3"

var (
	file_mpc_api_mpc_service_proto_rawDescOnce sync.Once
	file_mpc_api_mpc_service_proto_rawDescData []byte
)

func file_mpc_api_mpc_service_proto_rawDescGZIP() []byte {
	file_mpc_api_mpc_service_proto_rawDescOnce.Do(func() {
		file_mpc_api_mpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_api_mpc_service_proto_rawDesc), len(file_mpc_api_mpc_service_proto_rawDesc)))
	})
	return file_mpc_api_mpc_service_proto_rawDescData
}

var file_mpc_api_mpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mpc_api_mpc_service_proto_goTypes = []any{
	(*StoreShareRequest)(nil),     // 0: mpc_api.StoreShareRequest
	(*StoreShareResponse)(nil),    // 1: mpc_api.StoreShareResponse
	(*RetrieveShareRequest)(nil),  // 2: mpc_api.RetrieveShareRequest
	(*RetrieveShareResponse)(nil), // 3: mpc_api.RetrieveShareResponse
	(*DeleteShareRequest)(nil),    // 4: mpc_api.DeleteShareRequest
	(*DeleteShareResponse)(nil),   // 5: mpc_api.DeleteShareResponse
}
var file_mpc_api_mpc_service_proto_depIdxs = []int32{
	0, // 0: mpc_api.MPCNodeService.StoreShare:input_type -> mpc_api.StoreShareRequest
	2, // 1: mpc_api.MPCNodeService.RetrieveShare:input_type -> mpc_api.RetrieveShareRequest
	4, // 2: mpc_api.MPCNodeService.DeleteShare:input_type -> mpc_api.DeleteShareRequest
	1, // 3: mpc_api.MPCNodeService.StoreShare:output_type -> mpc_api.StoreShareResponse
	3, // 4: mpc_api.MPCNodeService.RetrieveShare:output_type -> mpc_api.RetrieveShareResponse
	5, // 5: mpc_api.MPCNodeService.DeleteShare:output_type -> mpc_api.DeleteShareResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mpc_api_mpc_service_proto_init() }
func file_mpc_api_mpc_service_proto_init() {
	if File_mpc_api_mpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_api_mpc_service_proto_rawDesc), len(file_mpc_api_mpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpc_api_mpc_service_proto_goTypes,
		DependencyIndexes: file_mpc_api_mpc_service_proto_depIdxs,
		MessageInfos:      file_mpc_api_mpc_service_proto_msgTypes,
	}.Build()
	File_mpc_api_mpc_service_proto = out.File
	file_mpc_api_mpc_service_proto_goTypes = nil
	file_mpc_api_mpc_service_proto_depIdxs = nil
}
