// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: mpc_api/mpc_service.proto

package mpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPCNodeService_StoreShare_FullMethodName    = "/mpc_api.MPCNodeService/StoreShare"
	MPCNodeService_RetrieveShare_FullMethodName = "/mpc_api.MPCNodeService/RetrieveShare"
	MPCNodeService_DeleteShare_FullMethodName   = "/mpc_api.MPCNodeService/DeleteShare"
)

// MPCNodeServiceClient is the client API for MPCNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPCNodeServiceClient interface {
	StoreShare(ctx context.Context, in *StoreShareRequest, opts ...grpc.CallOption) (*StoreShareResponse, error)
	RetrieveShare(ctx context.Context, in *RetrieveShareRequest, opts ...grpc.CallOption) (*RetrieveShareResponse, error)
	DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...grpc.CallOption) (*DeleteShareResponse, error)
}

type mPCNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCNodeServiceClient(cc grpc.ClientConnInterface) MPCNodeServiceClient {
	return &mPCNodeServiceClient{cc}
}

func (c *mPCNodeServiceClient) StoreShare(ctx context.Context, in *StoreShareRequest, opts ...grpc.CallOption) (*StoreShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreShareResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_StoreShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) RetrieveShare(ctx context.Context, in *RetrieveShareRequest, opts ...grpc.CallOption) (*RetrieveShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveShareResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_RetrieveShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...grpc.CallOption) (*DeleteShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShareResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_DeleteShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCNodeServiceServer is the server API for MPCNodeService service.
// All implementations must embed UnimplementedMPCNodeServiceServer
// for forward compatibility.
type MPCNodeServiceServer interface {
	StoreShare(context.Context, *StoreShareRequest) (*StoreShareResponse, error)
	RetrieveShare(context.Context, *RetrieveShareRequest) (*RetrieveShareResponse, error)
	DeleteShare(context.Context, *DeleteShareRequest) (*DeleteShareResponse, error)
	mustEmbedUnimplementedMPCNodeServiceServer()
}

// UnimplementedMPCNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCNodeServiceServer struct{}

func (UnimplementedMPCNodeServiceServer) StoreShare(context.Context, *StoreShareRequest) (*StoreShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreShare not implemented")
}
func (UnimplementedMPCNodeServiceServer) RetrieveShare(context.Context, *RetrieveShareRequest) (*RetrieveShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveShare not implemented")
}
func (UnimplementedMPCNodeServiceServer) DeleteShare(context.Context, *DeleteShareRequest) (*DeleteShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShare not implemented")
}
func (UnimplementedMPCNodeServiceServer) mustEmbedUnimplementedMPCNodeServiceServer() {}
func (UnimplementedMPCNodeServiceServer) testEmbeddedByValue()                        {}

// UnsafeMPCNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCNodeServiceServer will
// result in compilation errors.
type UnsafeMPCNodeServiceServer interface {
	mustEmbedUnimplementedMPCNodeServiceServer()
}

func RegisterMPCNodeServiceServer(s grpc.ServiceRegistrar, srv MPCNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedMPCNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCNodeService_ServiceDesc, srv)
}

func _MPCNodeService_StoreShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).StoreShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_StoreShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).StoreShare(ctx, req.(*StoreShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_RetrieveShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).RetrieveShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_RetrieveShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).RetrieveShare(ctx, req.(*RetrieveShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_DeleteShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).DeleteShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_DeleteShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).DeleteShare(ctx, req.(*DeleteShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCNodeService_ServiceDesc is the grpc.ServiceDesc for MPCNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc_api.MPCNodeService",
	HandlerType: (*MPCNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreShare",
			Handler:    _MPCNodeService_StoreShare_Handler,
		},
		{
			MethodName: "RetrieveShare",
			Handler:    _MPCNodeService_RetrieveShare_Handler,
		},
		{
			MethodName: "DeleteShare",
			Handler:    _MPCNodeService_DeleteShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc_api/mpc_service.proto",
}
