// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: models/models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwoFARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoFARecord) Reset() {
	*x = TwoFARecord{}
	mi := &file_models_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoFARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoFARecord) ProtoMessage() {}

func (x *TwoFARecord) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoFARecord.ProtoReflect.Descriptor instead.
func (*TwoFARecord) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *TwoFARecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TwoFARecord) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *TwoFARecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BackupCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CodeHash      string                 `protobuf:"bytes,3,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	IsUsed        bool                   `protobuf:"varint,4,opt,name=is_used,json=isUsed,proto3" json:"is_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCode) Reset() {
	*x = BackupCode{}
	mi := &file_models_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCode) ProtoMessage() {}

func (x *BackupCode) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCode.ProtoReflect.Descriptor instead.
func (*BackupCode) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{1}
}

func (x *BackupCode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackupCode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BackupCode) GetCodeHash() string {
	if x != nil {
		return x.CodeHash
	}
	return ""
}

func (x *BackupCode) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

var File_models_models_proto protoreflect.FileDescriptor

const file_models_models_proto_rawDesc = "" +
	"\n" +
	"\x13models/models.proto\x12\ftwofa_models\"d\n" +
	"\vTwoFARecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x02 \x01(\bR\tisEnabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"k\n" +
	"\n" +
	"BackupCode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcode_hash\x18\x03 \x01(\tR\bcodeHash\x12\x17\n" +
	"\ais_used\x18\x04 \x01(\bR\x06isUsedB3Z1github.com/vbncursed/vkr/twofa/internal/pb/modelsb\x06proto3"

var (
	file_models_models_proto_rawDescOnce sync.Once
	file_models_models_proto_rawDescData []byte
)

func file_models_models_proto_rawDescGZIP() []byte {
	file_models_models_proto_rawDescOnce.Do(func() {
		file_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_models_proto_rawDesc), len(file_models_models_proto_rawDesc)))
	})
	return file_models_models_proto_rawDescData
}

var file_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_models_proto_goTypes = []any{
	(*TwoFARecord)(nil), // 0: twofa_models.TwoFARecord
	(*BackupCode)(nil),  // 1: twofa_models.BackupCode
}
var file_models_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_models_proto_init() }
func file_models_models_proto_init() {
	if File_models_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_models_proto_rawDesc), len(file_models_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_models_proto_goTypes,
		DependencyIndexes: file_models_models_proto_depIdxs,
		MessageInfos:      file_models_models_proto_msgTypes,
	}.Build()
	File_models_models_proto = out.File
	file_models_models_proto_goTypes = nil
	file_models_models_proto_depIdxs = nil
}
