// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/vkr/mpc/internal/domain"
)

// StorageMock implements mm_mpcService.Storage
type StorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateShare          func(ctx context.Context, share *domain.Share) (err error)
	funcCreateShareOrigin    string
	inspectFuncCreateShare   func(ctx context.Context, share *domain.Share)
	afterCreateShareCounter  uint64
	beforeCreateShareCounter uint64
	CreateShareMock          mStorageMockCreateShare

	funcDeleteSharesByUserID          func(ctx context.Context, userID string) (i1 int64, err error)
	funcDeleteSharesByUserIDOrigin    string
	inspectFuncDeleteSharesByUserID   func(ctx context.Context, userID string)
	afterDeleteSharesByUserIDCounter  uint64
	beforeDeleteSharesByUserIDCounter uint64
	DeleteSharesByUserIDMock          mStorageMockDeleteSharesByUserID

	funcGetShare          func(ctx context.Context, userID string, shareIndex int) (sp1 *domain.Share, err error)
	funcGetShareOrigin    string
	inspectFuncGetShare   func(ctx context.Context, userID string, shareIndex int)
	afterGetShareCounter  uint64
	beforeGetShareCounter uint64
	GetShareMock          mStorageMockGetShare
}

// NewStorageMock returns a mock for mm_mpcService.Storage
func NewStorageMock(t minimock.Tester) *StorageMock {
	m := &StorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateShareMock = mStorageMockCreateShare{mock: m}
	m.CreateShareMock.callArgs = []*StorageMockCreateShareParams{}

	m.DeleteSharesByUserIDMock = mStorageMockDeleteSharesByUserID{mock: m}
	m.DeleteSharesByUserIDMock.callArgs = []*StorageMockDeleteSharesByUserIDParams{}

	m.GetShareMock = mStorageMockGetShare{mock: m}
	m.GetShareMock.callArgs = []*StorageMockGetShareParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStorageMockCreateShare struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockCreateShareExpectation
	expectations       []*StorageMockCreateShareExpectation

	callArgs []*StorageMockCreateShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockCreateShareExpectation specifies expectation struct of the Storage.CreateShare
type StorageMockCreateShareExpectation struct {
	mock               *StorageMock
	params             *StorageMockCreateShareParams
	paramPtrs          *StorageMockCreateShareParamPtrs
	expectationOrigins StorageMockCreateShareExpectationOrigins
	results            *StorageMockCreateShareResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockCreateShareParams contains parameters of the Storage.CreateShare
type StorageMockCreateShareParams struct {
	ctx   context.Context
	share *domain.Share
}

// StorageMockCreateShareParamPtrs contains pointers to parameters of the Storage.CreateShare
type StorageMockCreateShareParamPtrs struct {
	ctx   *context.Context
	share **domain.Share
}

// StorageMockCreateShareResults contains results of the Storage.CreateShare
type StorageMockCreateShareResults struct {
	err error
}

// StorageMockCreateShareOrigins contains origins of expectations of the Storage.CreateShare
type StorageMockCreateShareExpectationOrigins struct {
	origin      string
	originCtx   string
	originShare string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateShare *mStorageMockCreateShare) Optional() *mStorageMockCreateShare {
	mmCreateShare.optional = true
	return mmCreateShare
}

// Expect sets up expected params for Storage.CreateShare
func (mmCreateShare *mStorageMockCreateShare) Expect(ctx context.Context, share *domain.Share) *mStorageMockCreateShare {
	if mmCreateShare.mock.funcCreateShare != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Set")
	}

	if mmCreateShare.defaultExpectation == nil {
		mmCreateShare.defaultExpectation = &StorageMockCreateShareExpectation{}
	}

	if mmCreateShare.defaultExpectation.paramPtrs != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by ExpectParams functions")
	}

	mmCreateShare.defaultExpectation.params = &StorageMockCreateShareParams{ctx, share}
	mmCreateShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateShare.expectations {
		if minimock.Equal(e.params, mmCreateShare.defaultExpectation.params) {
			mmCreateShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateShare.defaultExpectation.params)
		}
	}

	return mmCreateShare
}

// ExpectCtxParam1 sets up expected param ctx for Storage.CreateShare
func (mmCreateShare *mStorageMockCreateShare) ExpectCtxParam1(ctx context.Context) *mStorageMockCreateShare {
	if mmCreateShare.mock.funcCreateShare != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Set")
	}

	if mmCreateShare.defaultExpectation == nil {
		mmCreateShare.defaultExpectation = &StorageMockCreateShareExpectation{}
	}

	if mmCreateShare.defaultExpectation.params != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Expect")
	}

	if mmCreateShare.defaultExpectation.paramPtrs == nil {
		mmCreateShare.defaultExpectation.paramPtrs = &StorageMockCreateShareParamPtrs{}
	}
	mmCreateShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateShare
}

// ExpectShareParam2 sets up expected param share for Storage.CreateShare
func (mmCreateShare *mStorageMockCreateShare) ExpectShareParam2(share *domain.Share) *mStorageMockCreateShare {
	if mmCreateShare.mock.funcCreateShare != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Set")
	}

	if mmCreateShare.defaultExpectation == nil {
		mmCreateShare.defaultExpectation = &StorageMockCreateShareExpectation{}
	}

	if mmCreateShare.defaultExpectation.params != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Expect")
	}

	if mmCreateShare.defaultExpectation.paramPtrs == nil {
		mmCreateShare.defaultExpectation.paramPtrs = &StorageMockCreateShareParamPtrs{}
	}
	mmCreateShare.defaultExpectation.paramPtrs.share = &share
	mmCreateShare.defaultExpectation.expectationOrigins.originShare = minimock.CallerInfo(1)

	return mmCreateShare
}

// Inspect accepts an inspector function that has same arguments as the Storage.CreateShare
func (mmCreateShare *mStorageMockCreateShare) Inspect(f func(ctx context.Context, share *domain.Share)) *mStorageMockCreateShare {
	if mmCreateShare.mock.inspectFuncCreateShare != nil {
		mmCreateShare.mock.t.Fatalf("Inspect function is already set for StorageMock.CreateShare")
	}

	mmCreateShare.mock.inspectFuncCreateShare = f

	return mmCreateShare
}

// Return sets up results that will be returned by Storage.CreateShare
func (mmCreateShare *mStorageMockCreateShare) Return(err error) *StorageMock {
	if mmCreateShare.mock.funcCreateShare != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Set")
	}

	if mmCreateShare.defaultExpectation == nil {
		mmCreateShare.defaultExpectation = &StorageMockCreateShareExpectation{mock: mmCreateShare.mock}
	}
	mmCreateShare.defaultExpectation.results = &StorageMockCreateShareResults{err}
	mmCreateShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateShare.mock
}

// Set uses given function f to mock the Storage.CreateShare method
func (mmCreateShare *mStorageMockCreateShare) Set(f func(ctx context.Context, share *domain.Share) (err error)) *StorageMock {
	if mmCreateShare.defaultExpectation != nil {
		mmCreateShare.mock.t.Fatalf("Default expectation is already set for the Storage.CreateShare method")
	}

	if len(mmCreateShare.expectations) > 0 {
		mmCreateShare.mock.t.Fatalf("Some expectations are already set for the Storage.CreateShare method")
	}

	mmCreateShare.mock.funcCreateShare = f
	mmCreateShare.mock.funcCreateShareOrigin = minimock.CallerInfo(1)
	return mmCreateShare.mock
}

// When sets expectation for the Storage.CreateShare which will trigger the result defined by the following
// Then helper
func (mmCreateShare *mStorageMockCreateShare) When(ctx context.Context, share *domain.Share) *StorageMockCreateShareExpectation {
	if mmCreateShare.mock.funcCreateShare != nil {
		mmCreateShare.mock.t.Fatalf("StorageMock.CreateShare mock is already set by Set")
	}

	expectation := &StorageMockCreateShareExpectation{
		mock:               mmCreateShare.mock,
		params:             &StorageMockCreateShareParams{ctx, share},
		expectationOrigins: StorageMockCreateShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateShare.expectations = append(mmCreateShare.expectations, expectation)
	return expectation
}

// Then sets up Storage.CreateShare return parameters for the expectation previously defined by the When method
func (e *StorageMockCreateShareExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockCreateShareResults{err}
	return e.mock
}

// Times sets number of times Storage.CreateShare should be invoked
func (mmCreateShare *mStorageMockCreateShare) Times(n uint64) *mStorageMockCreateShare {
	if n == 0 {
		mmCreateShare.mock.t.Fatalf("Times of StorageMock.CreateShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateShare.expectedInvocations, n)
	mmCreateShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateShare
}

func (mmCreateShare *mStorageMockCreateShare) invocationsDone() bool {
	if len(mmCreateShare.expectations) == 0 && mmCreateShare.defaultExpectation == nil && mmCreateShare.mock.funcCreateShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateShare.mock.afterCreateShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateShare implements mm_mpcService.Storage
func (mmCreateShare *StorageMock) CreateShare(ctx context.Context, share *domain.Share) (err error) {
	mm_atomic.AddUint64(&mmCreateShare.beforeCreateShareCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateShare.afterCreateShareCounter, 1)

	mmCreateShare.t.Helper()

	if mmCreateShare.inspectFuncCreateShare != nil {
		mmCreateShare.inspectFuncCreateShare(ctx, share)
	}

	mm_params := StorageMockCreateShareParams{ctx, share}

	// Record call args
	mmCreateShare.CreateShareMock.mutex.Lock()
	mmCreateShare.CreateShareMock.callArgs = append(mmCreateShare.CreateShareMock.callArgs, &mm_params)
	mmCreateShare.CreateShareMock.mutex.Unlock()

	for _, e := range mmCreateShare.CreateShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateShare.CreateShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateShare.CreateShareMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateShare.CreateShareMock.defaultExpectation.params
		mm_want_ptrs := mmCreateShare.CreateShareMock.defaultExpectation.paramPtrs

		mm_got := StorageMockCreateShareParams{ctx, share}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateShare.t.Errorf("StorageMock.CreateShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateShare.CreateShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.share != nil && !minimock.Equal(*mm_want_ptrs.share, mm_got.share) {
				mmCreateShare.t.Errorf("StorageMock.CreateShare got unexpected parameter share, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateShare.CreateShareMock.defaultExpectation.expectationOrigins.originShare, *mm_want_ptrs.share, mm_got.share, minimock.Diff(*mm_want_ptrs.share, mm_got.share))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateShare.t.Errorf("StorageMock.CreateShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateShare.CreateShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateShare.CreateShareMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateShare.t.Fatal("No results are set for the StorageMock.CreateShare")
		}
		return (*mm_results).err
	}
	if mmCreateShare.funcCreateShare != nil {
		return mmCreateShare.funcCreateShare(ctx, share)
	}
	mmCreateShare.t.Fatalf("Unexpected call to StorageMock.CreateShare. %v %v", ctx, share)
	return
}

// CreateShareAfterCounter returns a count of finished StorageMock.CreateShare invocations
func (mmCreateShare *StorageMock) CreateShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateShare.afterCreateShareCounter)
}

// CreateShareBeforeCounter returns a count of StorageMock.CreateShare invocations
func (mmCreateShare *StorageMock) CreateShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateShare.beforeCreateShareCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.CreateShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateShare *mStorageMockCreateShare) Calls() []*StorageMockCreateShareParams {
	mmCreateShare.mutex.RLock()

	argCopy := make([]*StorageMockCreateShareParams, len(mmCreateShare.callArgs))
	copy(argCopy, mmCreateShare.callArgs)

	mmCreateShare.mutex.RUnlock()

	return argCopy
}

// MinimockCreateShareDone returns true if the count of the CreateShare invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockCreateShareDone() bool {
	if m.CreateShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateShareMock.invocationsDone()
}

// MinimockCreateShareInspect logs each unmet expectation
func (m *StorageMock) MinimockCreateShareInspect() {
	for _, e := range m.CreateShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.CreateShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateShareCounter := mm_atomic.LoadUint64(&m.afterCreateShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateShareMock.defaultExpectation != nil && afterCreateShareCounter < 1 {
		if m.CreateShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.CreateShare at\n%s", m.CreateShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.CreateShare at\n%s with params: %#v", m.CreateShareMock.defaultExpectation.expectationOrigins.origin, *m.CreateShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateShare != nil && afterCreateShareCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.CreateShare at\n%s", m.funcCreateShareOrigin)
	}

	if !m.CreateShareMock.invocationsDone() && afterCreateShareCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.CreateShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateShareMock.expectedInvocations), m.CreateShareMock.expectedInvocationsOrigin, afterCreateShareCounter)
	}
}

type mStorageMockDeleteSharesByUserID struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockDeleteSharesByUserIDExpectation
	expectations       []*StorageMockDeleteSharesByUserIDExpectation

	callArgs []*StorageMockDeleteSharesByUserIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockDeleteSharesByUserIDExpectation specifies expectation struct of the Storage.DeleteSharesByUserID
type StorageMockDeleteSharesByUserIDExpectation struct {
	mock               *StorageMock
	params             *StorageMockDeleteSharesByUserIDParams
	paramPtrs          *StorageMockDeleteSharesByUserIDParamPtrs
	expectationOrigins StorageMockDeleteSharesByUserIDExpectationOrigins
	results            *StorageMockDeleteSharesByUserIDResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockDeleteSharesByUserIDParams contains parameters of the Storage.DeleteSharesByUserID
type StorageMockDeleteSharesByUserIDParams struct {
	ctx    context.Context
	userID string
}

// StorageMockDeleteSharesByUserIDParamPtrs contains pointers to parameters of the Storage.DeleteSharesByUserID
type StorageMockDeleteSharesByUserIDParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// StorageMockDeleteSharesByUserIDResults contains results of the Storage.DeleteSharesByUserID
type StorageMockDeleteSharesByUserIDResults struct {
	i1  int64
	err error
}

// StorageMockDeleteSharesByUserIDOrigins contains origins of expectations of the Storage.DeleteSharesByUserID
type StorageMockDeleteSharesByUserIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Optional() *mStorageMockDeleteSharesByUserID {
	mmDeleteSharesByUserID.optional = true
	return mmDeleteSharesByUserID
}

// Expect sets up expected params for Storage.DeleteSharesByUserID
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Expect(ctx context.Context, userID string) *mStorageMockDeleteSharesByUserID {
	if mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Set")
	}

	if mmDeleteSharesByUserID.defaultExpectation == nil {
		mmDeleteSharesByUserID.defaultExpectation = &StorageMockDeleteSharesByUserIDExpectation{}
	}

	if mmDeleteSharesByUserID.defaultExpectation.paramPtrs != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by ExpectParams functions")
	}

	mmDeleteSharesByUserID.defaultExpectation.params = &StorageMockDeleteSharesByUserIDParams{ctx, userID}
	mmDeleteSharesByUserID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteSharesByUserID.expectations {
		if minimock.Equal(e.params, mmDeleteSharesByUserID.defaultExpectation.params) {
			mmDeleteSharesByUserID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteSharesByUserID.defaultExpectation.params)
		}
	}

	return mmDeleteSharesByUserID
}

// ExpectCtxParam1 sets up expected param ctx for Storage.DeleteSharesByUserID
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) ExpectCtxParam1(ctx context.Context) *mStorageMockDeleteSharesByUserID {
	if mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Set")
	}

	if mmDeleteSharesByUserID.defaultExpectation == nil {
		mmDeleteSharesByUserID.defaultExpectation = &StorageMockDeleteSharesByUserIDExpectation{}
	}

	if mmDeleteSharesByUserID.defaultExpectation.params != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Expect")
	}

	if mmDeleteSharesByUserID.defaultExpectation.paramPtrs == nil {
		mmDeleteSharesByUserID.defaultExpectation.paramPtrs = &StorageMockDeleteSharesByUserIDParamPtrs{}
	}
	mmDeleteSharesByUserID.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteSharesByUserID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteSharesByUserID
}

// ExpectUserIDParam2 sets up expected param userID for Storage.DeleteSharesByUserID
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) ExpectUserIDParam2(userID string) *mStorageMockDeleteSharesByUserID {
	if mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Set")
	}

	if mmDeleteSharesByUserID.defaultExpectation == nil {
		mmDeleteSharesByUserID.defaultExpectation = &StorageMockDeleteSharesByUserIDExpectation{}
	}

	if mmDeleteSharesByUserID.defaultExpectation.params != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Expect")
	}

	if mmDeleteSharesByUserID.defaultExpectation.paramPtrs == nil {
		mmDeleteSharesByUserID.defaultExpectation.paramPtrs = &StorageMockDeleteSharesByUserIDParamPtrs{}
	}
	mmDeleteSharesByUserID.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteSharesByUserID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteSharesByUserID
}

// Inspect accepts an inspector function that has same arguments as the Storage.DeleteSharesByUserID
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Inspect(f func(ctx context.Context, userID string)) *mStorageMockDeleteSharesByUserID {
	if mmDeleteSharesByUserID.mock.inspectFuncDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("Inspect function is already set for StorageMock.DeleteSharesByUserID")
	}

	mmDeleteSharesByUserID.mock.inspectFuncDeleteSharesByUserID = f

	return mmDeleteSharesByUserID
}

// Return sets up results that will be returned by Storage.DeleteSharesByUserID
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Return(i1 int64, err error) *StorageMock {
	if mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Set")
	}

	if mmDeleteSharesByUserID.defaultExpectation == nil {
		mmDeleteSharesByUserID.defaultExpectation = &StorageMockDeleteSharesByUserIDExpectation{mock: mmDeleteSharesByUserID.mock}
	}
	mmDeleteSharesByUserID.defaultExpectation.results = &StorageMockDeleteSharesByUserIDResults{i1, err}
	mmDeleteSharesByUserID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteSharesByUserID.mock
}

// Set uses given function f to mock the Storage.DeleteSharesByUserID method
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Set(f func(ctx context.Context, userID string) (i1 int64, err error)) *StorageMock {
	if mmDeleteSharesByUserID.defaultExpectation != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("Default expectation is already set for the Storage.DeleteSharesByUserID method")
	}

	if len(mmDeleteSharesByUserID.expectations) > 0 {
		mmDeleteSharesByUserID.mock.t.Fatalf("Some expectations are already set for the Storage.DeleteSharesByUserID method")
	}

	mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID = f
	mmDeleteSharesByUserID.mock.funcDeleteSharesByUserIDOrigin = minimock.CallerInfo(1)
	return mmDeleteSharesByUserID.mock
}

// When sets expectation for the Storage.DeleteSharesByUserID which will trigger the result defined by the following
// Then helper
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) When(ctx context.Context, userID string) *StorageMockDeleteSharesByUserIDExpectation {
	if mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.mock.t.Fatalf("StorageMock.DeleteSharesByUserID mock is already set by Set")
	}

	expectation := &StorageMockDeleteSharesByUserIDExpectation{
		mock:               mmDeleteSharesByUserID.mock,
		params:             &StorageMockDeleteSharesByUserIDParams{ctx, userID},
		expectationOrigins: StorageMockDeleteSharesByUserIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteSharesByUserID.expectations = append(mmDeleteSharesByUserID.expectations, expectation)
	return expectation
}

// Then sets up Storage.DeleteSharesByUserID return parameters for the expectation previously defined by the When method
func (e *StorageMockDeleteSharesByUserIDExpectation) Then(i1 int64, err error) *StorageMock {
	e.results = &StorageMockDeleteSharesByUserIDResults{i1, err}
	return e.mock
}

// Times sets number of times Storage.DeleteSharesByUserID should be invoked
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Times(n uint64) *mStorageMockDeleteSharesByUserID {
	if n == 0 {
		mmDeleteSharesByUserID.mock.t.Fatalf("Times of StorageMock.DeleteSharesByUserID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteSharesByUserID.expectedInvocations, n)
	mmDeleteSharesByUserID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteSharesByUserID
}

func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) invocationsDone() bool {
	if len(mmDeleteSharesByUserID.expectations) == 0 && mmDeleteSharesByUserID.defaultExpectation == nil && mmDeleteSharesByUserID.mock.funcDeleteSharesByUserID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteSharesByUserID.mock.afterDeleteSharesByUserIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteSharesByUserID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteSharesByUserID implements mm_mpcService.Storage
func (mmDeleteSharesByUserID *StorageMock) DeleteSharesByUserID(ctx context.Context, userID string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmDeleteSharesByUserID.beforeDeleteSharesByUserIDCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteSharesByUserID.afterDeleteSharesByUserIDCounter, 1)

	mmDeleteSharesByUserID.t.Helper()

	if mmDeleteSharesByUserID.inspectFuncDeleteSharesByUserID != nil {
		mmDeleteSharesByUserID.inspectFuncDeleteSharesByUserID(ctx, userID)
	}

	mm_params := StorageMockDeleteSharesByUserIDParams{ctx, userID}

	// Record call args
	mmDeleteSharesByUserID.DeleteSharesByUserIDMock.mutex.Lock()
	mmDeleteSharesByUserID.DeleteSharesByUserIDMock.callArgs = append(mmDeleteSharesByUserID.DeleteSharesByUserIDMock.callArgs, &mm_params)
	mmDeleteSharesByUserID.DeleteSharesByUserIDMock.mutex.Unlock()

	for _, e := range mmDeleteSharesByUserID.DeleteSharesByUserIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.paramPtrs

		mm_got := StorageMockDeleteSharesByUserIDParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteSharesByUserID.t.Errorf("StorageMock.DeleteSharesByUserID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteSharesByUserID.t.Errorf("StorageMock.DeleteSharesByUserID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteSharesByUserID.t.Errorf("StorageMock.DeleteSharesByUserID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteSharesByUserID.DeleteSharesByUserIDMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteSharesByUserID.t.Fatal("No results are set for the StorageMock.DeleteSharesByUserID")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmDeleteSharesByUserID.funcDeleteSharesByUserID != nil {
		return mmDeleteSharesByUserID.funcDeleteSharesByUserID(ctx, userID)
	}
	mmDeleteSharesByUserID.t.Fatalf("Unexpected call to StorageMock.DeleteSharesByUserID. %v %v", ctx, userID)
	return
}

// DeleteSharesByUserIDAfterCounter returns a count of finished StorageMock.DeleteSharesByUserID invocations
func (mmDeleteSharesByUserID *StorageMock) DeleteSharesByUserIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteSharesByUserID.afterDeleteSharesByUserIDCounter)
}

// DeleteSharesByUserIDBeforeCounter returns a count of StorageMock.DeleteSharesByUserID invocations
func (mmDeleteSharesByUserID *StorageMock) DeleteSharesByUserIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteSharesByUserID.beforeDeleteSharesByUserIDCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.DeleteSharesByUserID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteSharesByUserID *mStorageMockDeleteSharesByUserID) Calls() []*StorageMockDeleteSharesByUserIDParams {
	mmDeleteSharesByUserID.mutex.RLock()

	argCopy := make([]*StorageMockDeleteSharesByUserIDParams, len(mmDeleteSharesByUserID.callArgs))
	copy(argCopy, mmDeleteSharesByUserID.callArgs)

	mmDeleteSharesByUserID.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteSharesByUserIDDone returns true if the count of the DeleteSharesByUserID invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockDeleteSharesByUserIDDone() bool {
	if m.DeleteSharesByUserIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteSharesByUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteSharesByUserIDMock.invocationsDone()
}

// MinimockDeleteSharesByUserIDInspect logs each unmet expectation
func (m *StorageMock) MinimockDeleteSharesByUserIDInspect() {
	for _, e := range m.DeleteSharesByUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.DeleteSharesByUserID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteSharesByUserIDCounter := mm_atomic.LoadUint64(&m.afterDeleteSharesByUserIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteSharesByUserIDMock.defaultExpectation != nil && afterDeleteSharesByUserIDCounter < 1 {
		if m.DeleteSharesByUserIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.DeleteSharesByUserID at\n%s", m.DeleteSharesByUserIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.DeleteSharesByUserID at\n%s with params: %#v", m.DeleteSharesByUserIDMock.defaultExpectation.expectationOrigins.origin, *m.DeleteSharesByUserIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteSharesByUserID != nil && afterDeleteSharesByUserIDCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.DeleteSharesByUserID at\n%s", m.funcDeleteSharesByUserIDOrigin)
	}

	if !m.DeleteSharesByUserIDMock.invocationsDone() && afterDeleteSharesByUserIDCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.DeleteSharesByUserID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteSharesByUserIDMock.expectedInvocations), m.DeleteSharesByUserIDMock.expectedInvocationsOrigin, afterDeleteSharesByUserIDCounter)
	}
}

type mStorageMockGetShare struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockGetShareExpectation
	expectations       []*StorageMockGetShareExpectation

	callArgs []*StorageMockGetShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockGetShareExpectation specifies expectation struct of the Storage.GetShare
type StorageMockGetShareExpectation struct {
	mock               *StorageMock
	params             *StorageMockGetShareParams
	paramPtrs          *StorageMockGetShareParamPtrs
	expectationOrigins StorageMockGetShareExpectationOrigins
	results            *StorageMockGetShareResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockGetShareParams contains parameters of the Storage.GetShare
type StorageMockGetShareParams struct {
	ctx        context.Context
	userID     string
	shareIndex int
}

// StorageMockGetShareParamPtrs contains pointers to parameters of the Storage.GetShare
type StorageMockGetShareParamPtrs struct {
	ctx        *context.Context
	userID     *string
	shareIndex *int
}

// StorageMockGetShareResults contains results of the Storage.GetShare
type StorageMockGetShareResults struct {
	sp1 *domain.Share
	err error
}

// StorageMockGetShareOrigins contains origins of expectations of the Storage.GetShare
type StorageMockGetShareExpectationOrigins struct {
	origin           string
	originCtx        string
	originUserID     string
	originShareIndex string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetShare *mStorageMockGetShare) Optional() *mStorageMockGetShare {
	mmGetShare.optional = true
	return mmGetShare
}

// Expect sets up expected params for Storage.GetShare
func (mmGetShare *mStorageMockGetShare) Expect(ctx context.Context, userID string, shareIndex int) *mStorageMockGetShare {
	if mmGetShare.mock.funcGetShare != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Set")
	}

	if mmGetShare.defaultExpectation == nil {
		mmGetShare.defaultExpectation = &StorageMockGetShareExpectation{}
	}

	if mmGetShare.defaultExpectation.paramPtrs != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by ExpectParams functions")
	}

	mmGetShare.defaultExpectation.params = &StorageMockGetShareParams{ctx, userID, shareIndex}
	mmGetShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetShare.expectations {
		if minimock.Equal(e.params, mmGetShare.defaultExpectation.params) {
			mmGetShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetShare.defaultExpectation.params)
		}
	}

	return mmGetShare
}

// ExpectCtxParam1 sets up expected param ctx for Storage.GetShare
func (mmGetShare *mStorageMockGetShare) ExpectCtxParam1(ctx context.Context) *mStorageMockGetShare {
	if mmGetShare.mock.funcGetShare != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Set")
	}

	if mmGetShare.defaultExpectation == nil {
		mmGetShare.defaultExpectation = &StorageMockGetShareExpectation{}
	}

	if mmGetShare.defaultExpectation.params != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Expect")
	}

	if mmGetShare.defaultExpectation.paramPtrs == nil {
		mmGetShare.defaultExpectation.paramPtrs = &StorageMockGetShareParamPtrs{}
	}
	mmGetShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetShare
}

// ExpectUserIDParam2 sets up expected param userID for Storage.GetShare
func (mmGetShare *mStorageMockGetShare) ExpectUserIDParam2(userID string) *mStorageMockGetShare {
	if mmGetShare.mock.funcGetShare != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Set")
	}

	if mmGetShare.defaultExpectation == nil {
		mmGetShare.defaultExpectation = &StorageMockGetShareExpectation{}
	}

	if mmGetShare.defaultExpectation.params != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Expect")
	}

	if mmGetShare.defaultExpectation.paramPtrs == nil {
		mmGetShare.defaultExpectation.paramPtrs = &StorageMockGetShareParamPtrs{}
	}
	mmGetShare.defaultExpectation.paramPtrs.userID = &userID
	mmGetShare.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetShare
}

// ExpectShareIndexParam3 sets up expected param shareIndex for Storage.GetShare
func (mmGetShare *mStorageMockGetShare) ExpectShareIndexParam3(shareIndex int) *mStorageMockGetShare {
	if mmGetShare.mock.funcGetShare != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Set")
	}

	if mmGetShare.defaultExpectation == nil {
		mmGetShare.defaultExpectation = &StorageMockGetShareExpectation{}
	}

	if mmGetShare.defaultExpectation.params != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Expect")
	}

	if mmGetShare.defaultExpectation.paramPtrs == nil {
		mmGetShare.defaultExpectation.paramPtrs = &StorageMockGetShareParamPtrs{}
	}
	mmGetShare.defaultExpectation.paramPtrs.shareIndex = &shareIndex
	mmGetShare.defaultExpectation.expectationOrigins.originShareIndex = minimock.CallerInfo(1)

	return mmGetShare
}

// Inspect accepts an inspector function that has same arguments as the Storage.GetShare
func (mmGetShare *mStorageMockGetShare) Inspect(f func(ctx context.Context, userID string, shareIndex int)) *mStorageMockGetShare {
	if mmGetShare.mock.inspectFuncGetShare != nil {
		mmGetShare.mock.t.Fatalf("Inspect function is already set for StorageMock.GetShare")
	}

	mmGetShare.mock.inspectFuncGetShare = f

	return mmGetShare
}

// Return sets up results that will be returned by Storage.GetShare
func (mmGetShare *mStorageMockGetShare) Return(sp1 *domain.Share, err error) *StorageMock {
	if mmGetShare.mock.funcGetShare != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Set")
	}

	if mmGetShare.defaultExpectation == nil {
		mmGetShare.defaultExpectation = &StorageMockGetShareExpectation{mock: mmGetShare.mock}
	}
	mmGetShare.defaultExpectation.results = &StorageMockGetShareResults{sp1, err}
	mmGetShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetShare.mock
}

// Set uses given function f to mock the Storage.GetShare method
func (mmGetShare *mStorageMockGetShare) Set(f func(ctx context.Context, userID string, shareIndex int) (sp1 *domain.Share, err error)) *StorageMock {
	if mmGetShare.defaultExpectation != nil {
		mmGetShare.mock.t.Fatalf("Default expectation is already set for the Storage.GetShare method")
	}

	if len(mmGetShare.expectations) > 0 {
		mmGetShare.mock.t.Fatalf("Some expectations are already set for the Storage.GetShare method")
	}

	mmGetShare.mock.funcGetShare = f
	mmGetShare.mock.funcGetShareOrigin = minimock.CallerInfo(1)
	return mmGetShare.mock
}

// When sets expectation for the Storage.GetShare which will trigger the result defined by the following
// Then helper
func (mmGetShare *mStorageMockGetShare) When(ctx context.Context, userID string, shareIndex int) *StorageMockGetShareExpectation {
	if mmGetShare.mock.funcGetShare != nil {
		mmGetShare.mock.t.Fatalf("StorageMock.GetShare mock is already set by Set")
	}

	expectation := &StorageMockGetShareExpectation{
		mock:               mmGetShare.mock,
		params:             &StorageMockGetShareParams{ctx, userID, shareIndex},
		expectationOrigins: StorageMockGetShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetShare.expectations = append(mmGetShare.expectations, expectation)
	return expectation
}

// Then sets up Storage.GetShare return parameters for the expectation previously defined by the When method
func (e *StorageMockGetShareExpectation) Then(sp1 *domain.Share, err error) *StorageMock {
	e.results = &StorageMockGetShareResults{sp1, err}
	return e.mock
}

// Times sets number of times Storage.GetShare should be invoked
func (mmGetShare *mStorageMockGetShare) Times(n uint64) *mStorageMockGetShare {
	if n == 0 {
		mmGetShare.mock.t.Fatalf("Times of StorageMock.GetShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetShare.expectedInvocations, n)
	mmGetShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetShare
}

func (mmGetShare *mStorageMockGetShare) invocationsDone() bool {
	if len(mmGetShare.expectations) == 0 && mmGetShare.defaultExpectation == nil && mmGetShare.mock.funcGetShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetShare.mock.afterGetShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetShare implements mm_mpcService.Storage
func (mmGetShare *StorageMock) GetShare(ctx context.Context, userID string, shareIndex int) (sp1 *domain.Share, err error) {
	mm_atomic.AddUint64(&mmGetShare.beforeGetShareCounter, 1)
	defer mm_atomic.AddUint64(&mmGetShare.afterGetShareCounter, 1)

	mmGetShare.t.Helper()

	if mmGetShare.inspectFuncGetShare != nil {
		mmGetShare.inspectFuncGetShare(ctx, userID, shareIndex)
	}

	mm_params := StorageMockGetShareParams{ctx, userID, shareIndex}

	// Record call args
	mmGetShare.GetShareMock.mutex.Lock()
	mmGetShare.GetShareMock.callArgs = append(mmGetShare.GetShareMock.callArgs, &mm_params)
	mmGetShare.GetShareMock.mutex.Unlock()

	for _, e := range mmGetShare.GetShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetShare.GetShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetShare.GetShareMock.defaultExpectation.Counter, 1)
		mm_want := mmGetShare.GetShareMock.defaultExpectation.params
		mm_want_ptrs := mmGetShare.GetShareMock.defaultExpectation.paramPtrs

		mm_got := StorageMockGetShareParams{ctx, userID, shareIndex}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetShare.t.Errorf("StorageMock.GetShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShare.GetShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetShare.t.Errorf("StorageMock.GetShare got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShare.GetShareMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.shareIndex != nil && !minimock.Equal(*mm_want_ptrs.shareIndex, mm_got.shareIndex) {
				mmGetShare.t.Errorf("StorageMock.GetShare got unexpected parameter shareIndex, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShare.GetShareMock.defaultExpectation.expectationOrigins.originShareIndex, *mm_want_ptrs.shareIndex, mm_got.shareIndex, minimock.Diff(*mm_want_ptrs.shareIndex, mm_got.shareIndex))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetShare.t.Errorf("StorageMock.GetShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetShare.GetShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetShare.GetShareMock.defaultExpectation.results
		if mm_results == nil {
			mmGetShare.t.Fatal("No results are set for the StorageMock.GetShare")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetShare.funcGetShare != nil {
		return mmGetShare.funcGetShare(ctx, userID, shareIndex)
	}
	mmGetShare.t.Fatalf("Unexpected call to StorageMock.GetShare. %v %v %v", ctx, userID, shareIndex)
	return
}

// GetShareAfterCounter returns a count of finished StorageMock.GetShare invocations
func (mmGetShare *StorageMock) GetShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetShare.afterGetShareCounter)
}

// GetShareBeforeCounter returns a count of StorageMock.GetShare invocations
func (mmGetShare *StorageMock) GetShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetShare.beforeGetShareCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.GetShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetShare *mStorageMockGetShare) Calls() []*StorageMockGetShareParams {
	mmGetShare.mutex.RLock()

	argCopy := make([]*StorageMockGetShareParams, len(mmGetShare.callArgs))
	copy(argCopy, mmGetShare.callArgs)

	mmGetShare.mutex.RUnlock()

	return argCopy
}

// MinimockGetShareDone returns true if the count of the GetShare invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockGetShareDone() bool {
	if m.GetShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetShareMock.invocationsDone()
}

// MinimockGetShareInspect logs each unmet expectation
func (m *StorageMock) MinimockGetShareInspect() {
	for _, e := range m.GetShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.GetShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetShareCounter := mm_atomic.LoadUint64(&m.afterGetShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetShareMock.defaultExpectation != nil && afterGetShareCounter < 1 {
		if m.GetShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.GetShare at\n%s", m.GetShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.GetShare at\n%s with params: %#v", m.GetShareMock.defaultExpectation.expectationOrigins.origin, *m.GetShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetShare != nil && afterGetShareCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.GetShare at\n%s", m.funcGetShareOrigin)
	}

	if !m.GetShareMock.invocationsDone() && afterGetShareCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.GetShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetShareMock.expectedInvocations), m.GetShareMock.expectedInvocationsOrigin, afterGetShareCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateShareInspect()

			m.MinimockDeleteSharesByUserIDInspect()

			m.MinimockGetShareInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateShareDone() &&
		m.MinimockDeleteSharesByUserIDDone() &&
		m.MinimockGetShareDone()
}
