// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/vkr/twofa/internal/services/twofaService.MPCClient -o mpc_client_mock.go -n MPCClientMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vbncursed/vkr/twofa/internal/pb/mpc_api"
	"google.golang.org/grpc"
)

// MPCClientMock implements mm_twofaService.MPCClient
type MPCClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteShare          func(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption) (dp1 *mpc_api.DeleteShareResponse, err error)
	funcDeleteShareOrigin    string
	inspectFuncDeleteShare   func(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption)
	afterDeleteShareCounter  uint64
	beforeDeleteShareCounter uint64
	DeleteShareMock          mMPCClientMockDeleteShare

	funcRetrieveShare          func(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption) (rp1 *mpc_api.RetrieveShareResponse, err error)
	funcRetrieveShareOrigin    string
	inspectFuncRetrieveShare   func(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption)
	afterRetrieveShareCounter  uint64
	beforeRetrieveShareCounter uint64
	RetrieveShareMock          mMPCClientMockRetrieveShare

	funcStoreShare          func(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption) (sp1 *mpc_api.StoreShareResponse, err error)
	funcStoreShareOrigin    string
	inspectFuncStoreShare   func(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption)
	afterStoreShareCounter  uint64
	beforeStoreShareCounter uint64
	StoreShareMock          mMPCClientMockStoreShare
}

// NewMPCClientMock returns a mock for mm_twofaService.MPCClient
func NewMPCClientMock(t minimock.Tester) *MPCClientMock {
	m := &MPCClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteShareMock = mMPCClientMockDeleteShare{mock: m}
	m.DeleteShareMock.callArgs = []*MPCClientMockDeleteShareParams{}

	m.RetrieveShareMock = mMPCClientMockRetrieveShare{mock: m}
	m.RetrieveShareMock.callArgs = []*MPCClientMockRetrieveShareParams{}

	m.StoreShareMock = mMPCClientMockStoreShare{mock: m}
	m.StoreShareMock.callArgs = []*MPCClientMockStoreShareParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMPCClientMockDeleteShare struct {
	optional           bool
	mock               *MPCClientMock
	defaultExpectation *MPCClientMockDeleteShareExpectation
	expectations       []*MPCClientMockDeleteShareExpectation

	callArgs []*MPCClientMockDeleteShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MPCClientMockDeleteShareExpectation specifies expectation struct of the MPCClient.DeleteShare
type MPCClientMockDeleteShareExpectation struct {
	mock               *MPCClientMock
	params             *MPCClientMockDeleteShareParams
	paramPtrs          *MPCClientMockDeleteShareParamPtrs
	expectationOrigins MPCClientMockDeleteShareExpectationOrigins
	results            *MPCClientMockDeleteShareResults
	returnOrigin       string
	Counter            uint64
}

// MPCClientMockDeleteShareParams contains parameters of the MPCClient.DeleteShare
type MPCClientMockDeleteShareParams struct {
	ctx  context.Context
	in   *mpc_api.DeleteShareRequest
	opts []grpc.CallOption
}

// MPCClientMockDeleteShareParamPtrs contains pointers to parameters of the MPCClient.DeleteShare
type MPCClientMockDeleteShareParamPtrs struct {
	ctx  *context.Context
	in   **mpc_api.DeleteShareRequest
	opts *[]grpc.CallOption
}

// MPCClientMockDeleteShareResults contains results of the MPCClient.DeleteShare
type MPCClientMockDeleteShareResults struct {
	dp1 *mpc_api.DeleteShareResponse
	err error
}

// MPCClientMockDeleteShareOrigins contains origins of expectations of the MPCClient.DeleteShare
type MPCClientMockDeleteShareExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteShare *mMPCClientMockDeleteShare) Optional() *mMPCClientMockDeleteShare {
	mmDeleteShare.optional = true
	return mmDeleteShare
}

// Expect sets up expected params for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) Expect(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.paramPtrs != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by ExpectParams functions")
	}

	mmDeleteShare.defaultExpectation.params = &MPCClientMockDeleteShareParams{ctx, in, opts}
	mmDeleteShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteShare.expectations {
		if minimock.Equal(e.params, mmDeleteShare.defaultExpectation.params) {
			mmDeleteShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteShare.defaultExpectation.params)
		}
	}

	return mmDeleteShare
}

// ExpectCtxParam1 sets up expected param ctx for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) ExpectCtxParam1(ctx context.Context) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.params != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Expect")
	}

	if mmDeleteShare.defaultExpectation.paramPtrs == nil {
		mmDeleteShare.defaultExpectation.paramPtrs = &MPCClientMockDeleteShareParamPtrs{}
	}
	mmDeleteShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteShare
}

// ExpectInParam2 sets up expected param in for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) ExpectInParam2(in *mpc_api.DeleteShareRequest) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.params != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Expect")
	}

	if mmDeleteShare.defaultExpectation.paramPtrs == nil {
		mmDeleteShare.defaultExpectation.paramPtrs = &MPCClientMockDeleteShareParamPtrs{}
	}
	mmDeleteShare.defaultExpectation.paramPtrs.in = &in
	mmDeleteShare.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmDeleteShare
}

// ExpectOptsParam3 sets up expected param opts for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) ExpectOptsParam3(opts ...grpc.CallOption) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.params != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Expect")
	}

	if mmDeleteShare.defaultExpectation.paramPtrs == nil {
		mmDeleteShare.defaultExpectation.paramPtrs = &MPCClientMockDeleteShareParamPtrs{}
	}
	mmDeleteShare.defaultExpectation.paramPtrs.opts = &opts
	mmDeleteShare.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmDeleteShare
}

// Inspect accepts an inspector function that has same arguments as the MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) Inspect(f func(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption)) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.inspectFuncDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("Inspect function is already set for MPCClientMock.DeleteShare")
	}

	mmDeleteShare.mock.inspectFuncDeleteShare = f

	return mmDeleteShare
}

// Return sets up results that will be returned by MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) Return(dp1 *mpc_api.DeleteShareResponse, err error) *MPCClientMock {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{mock: mmDeleteShare.mock}
	}
	mmDeleteShare.defaultExpectation.results = &MPCClientMockDeleteShareResults{dp1, err}
	mmDeleteShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteShare.mock
}

// Set uses given function f to mock the MPCClient.DeleteShare method
func (mmDeleteShare *mMPCClientMockDeleteShare) Set(f func(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption) (dp1 *mpc_api.DeleteShareResponse, err error)) *MPCClientMock {
	if mmDeleteShare.defaultExpectation != nil {
		mmDeleteShare.mock.t.Fatalf("Default expectation is already set for the MPCClient.DeleteShare method")
	}

	if len(mmDeleteShare.expectations) > 0 {
		mmDeleteShare.mock.t.Fatalf("Some expectations are already set for the MPCClient.DeleteShare method")
	}

	mmDeleteShare.mock.funcDeleteShare = f
	mmDeleteShare.mock.funcDeleteShareOrigin = minimock.CallerInfo(1)
	return mmDeleteShare.mock
}

// When sets expectation for the MPCClient.DeleteShare which will trigger the result defined by the following
// Then helper
func (mmDeleteShare *mMPCClientMockDeleteShare) When(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption) *MPCClientMockDeleteShareExpectation {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	expectation := &MPCClientMockDeleteShareExpectation{
		mock:               mmDeleteShare.mock,
		params:             &MPCClientMockDeleteShareParams{ctx, in, opts},
		expectationOrigins: MPCClientMockDeleteShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteShare.expectations = append(mmDeleteShare.expectations, expectation)
	return expectation
}

// Then sets up MPCClient.DeleteShare return parameters for the expectation previously defined by the When method
func (e *MPCClientMockDeleteShareExpectation) Then(dp1 *mpc_api.DeleteShareResponse, err error) *MPCClientMock {
	e.results = &MPCClientMockDeleteShareResults{dp1, err}
	return e.mock
}

// Times sets number of times MPCClient.DeleteShare should be invoked
func (mmDeleteShare *mMPCClientMockDeleteShare) Times(n uint64) *mMPCClientMockDeleteShare {
	if n == 0 {
		mmDeleteShare.mock.t.Fatalf("Times of MPCClientMock.DeleteShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteShare.expectedInvocations, n)
	mmDeleteShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteShare
}

func (mmDeleteShare *mMPCClientMockDeleteShare) invocationsDone() bool {
	if len(mmDeleteShare.expectations) == 0 && mmDeleteShare.defaultExpectation == nil && mmDeleteShare.mock.funcDeleteShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteShare.mock.afterDeleteShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteShare implements mm_twofaService.MPCClient
func (mmDeleteShare *MPCClientMock) DeleteShare(ctx context.Context, in *mpc_api.DeleteShareRequest, opts ...grpc.CallOption) (dp1 *mpc_api.DeleteShareResponse, err error) {
	mm_atomic.AddUint64(&mmDeleteShare.beforeDeleteShareCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteShare.afterDeleteShareCounter, 1)

	mmDeleteShare.t.Helper()

	if mmDeleteShare.inspectFuncDeleteShare != nil {
		mmDeleteShare.inspectFuncDeleteShare(ctx, in, opts...)
	}

	mm_params := MPCClientMockDeleteShareParams{ctx, in, opts}

	// Record call args
	mmDeleteShare.DeleteShareMock.mutex.Lock()
	mmDeleteShare.DeleteShareMock.callArgs = append(mmDeleteShare.DeleteShareMock.callArgs, &mm_params)
	mmDeleteShare.DeleteShareMock.mutex.Unlock()

	for _, e := range mmDeleteShare.DeleteShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.dp1, e.results.err
		}
	}

	if mmDeleteShare.DeleteShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteShare.DeleteShareMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteShare.DeleteShareMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteShare.DeleteShareMock.defaultExpectation.paramPtrs

		mm_got := MPCClientMockDeleteShareParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteShare.DeleteShareMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteShare.t.Fatal("No results are set for the MPCClientMock.DeleteShare")
		}
		return (*mm_results).dp1, (*mm_results).err
	}
	if mmDeleteShare.funcDeleteShare != nil {
		return mmDeleteShare.funcDeleteShare(ctx, in, opts...)
	}
	mmDeleteShare.t.Fatalf("Unexpected call to MPCClientMock.DeleteShare. %v %v %v", ctx, in, opts)
	return
}

// DeleteShareAfterCounter returns a count of finished MPCClientMock.DeleteShare invocations
func (mmDeleteShare *MPCClientMock) DeleteShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteShare.afterDeleteShareCounter)
}

// DeleteShareBeforeCounter returns a count of MPCClientMock.DeleteShare invocations
func (mmDeleteShare *MPCClientMock) DeleteShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteShare.beforeDeleteShareCounter)
}

// Calls returns a list of arguments used in each call to MPCClientMock.DeleteShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteShare *mMPCClientMockDeleteShare) Calls() []*MPCClientMockDeleteShareParams {
	mmDeleteShare.mutex.RLock()

	argCopy := make([]*MPCClientMockDeleteShareParams, len(mmDeleteShare.callArgs))
	copy(argCopy, mmDeleteShare.callArgs)

	mmDeleteShare.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteShareDone returns true if the count of the DeleteShare invocations corresponds
// the number of defined expectations
func (m *MPCClientMock) MinimockDeleteShareDone() bool {
	if m.DeleteShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteShareMock.invocationsDone()
}

// MinimockDeleteShareInspect logs each unmet expectation
func (m *MPCClientMock) MinimockDeleteShareInspect() {
	for _, e := range m.DeleteShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteShareCounter := mm_atomic.LoadUint64(&m.afterDeleteShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteShareMock.defaultExpectation != nil && afterDeleteShareCounter < 1 {
		if m.DeleteShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s", m.DeleteShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s with params: %#v", m.DeleteShareMock.defaultExpectation.expectationOrigins.origin, *m.DeleteShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteShare != nil && afterDeleteShareCounter < 1 {
		m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s", m.funcDeleteShareOrigin)
	}

	if !m.DeleteShareMock.invocationsDone() && afterDeleteShareCounter > 0 {
		m.t.Errorf("Expected %d calls to MPCClientMock.DeleteShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteShareMock.expectedInvocations), m.DeleteShareMock.expectedInvocationsOrigin, afterDeleteShareCounter)
	}
}

type mMPCClientMockRetrieveShare struct {
	optional           bool
	mock               *MPCClientMock
	defaultExpectation *MPCClientMockRetrieveShareExpectation
	expectations       []*MPCClientMockRetrieveShareExpectation

	callArgs []*MPCClientMockRetrieveShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MPCClientMockRetrieveShareExpectation specifies expectation struct of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareExpectation struct {
	mock               *MPCClientMock
	params             *MPCClientMockRetrieveShareParams
	paramPtrs          *MPCClientMockRetrieveShareParamPtrs
	expectationOrigins MPCClientMockRetrieveShareExpectationOrigins
	results            *MPCClientMockRetrieveShareResults
	returnOrigin       string
	Counter            uint64
}

// MPCClientMockRetrieveShareParams contains parameters of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareParams struct {
	ctx  context.Context
	in   *mpc_api.RetrieveShareRequest
	opts []grpc.CallOption
}

// MPCClientMockRetrieveShareParamPtrs contains pointers to parameters of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareParamPtrs struct {
	ctx  *context.Context
	in   **mpc_api.RetrieveShareRequest
	opts *[]grpc.CallOption
}

// MPCClientMockRetrieveShareResults contains results of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareResults struct {
	rp1 *mpc_api.RetrieveShareResponse
	err error
}

// MPCClientMockRetrieveShareOrigins contains origins of expectations of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Optional() *mMPCClientMockRetrieveShare {
	mmRetrieveShare.optional = true
	return mmRetrieveShare
}

// Expect sets up expected params for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Expect(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by ExpectParams functions")
	}

	mmRetrieveShare.defaultExpectation.params = &MPCClientMockRetrieveShareParams{ctx, in, opts}
	mmRetrieveShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRetrieveShare.expectations {
		if minimock.Equal(e.params, mmRetrieveShare.defaultExpectation.params) {
			mmRetrieveShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRetrieveShare.defaultExpectation.params)
		}
	}

	return mmRetrieveShare
}

// ExpectCtxParam1 sets up expected param ctx for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) ExpectCtxParam1(ctx context.Context) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.params != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Expect")
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs == nil {
		mmRetrieveShare.defaultExpectation.paramPtrs = &MPCClientMockRetrieveShareParamPtrs{}
	}
	mmRetrieveShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmRetrieveShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRetrieveShare
}

// ExpectInParam2 sets up expected param in for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) ExpectInParam2(in *mpc_api.RetrieveShareRequest) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.params != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Expect")
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs == nil {
		mmRetrieveShare.defaultExpectation.paramPtrs = &MPCClientMockRetrieveShareParamPtrs{}
	}
	mmRetrieveShare.defaultExpectation.paramPtrs.in = &in
	mmRetrieveShare.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmRetrieveShare
}

// ExpectOptsParam3 sets up expected param opts for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) ExpectOptsParam3(opts ...grpc.CallOption) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.params != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Expect")
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs == nil {
		mmRetrieveShare.defaultExpectation.paramPtrs = &MPCClientMockRetrieveShareParamPtrs{}
	}
	mmRetrieveShare.defaultExpectation.paramPtrs.opts = &opts
	mmRetrieveShare.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmRetrieveShare
}

// Inspect accepts an inspector function that has same arguments as the MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Inspect(f func(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption)) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.inspectFuncRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("Inspect function is already set for MPCClientMock.RetrieveShare")
	}

	mmRetrieveShare.mock.inspectFuncRetrieveShare = f

	return mmRetrieveShare
}

// Return sets up results that will be returned by MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Return(rp1 *mpc_api.RetrieveShareResponse, err error) *MPCClientMock {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{mock: mmRetrieveShare.mock}
	}
	mmRetrieveShare.defaultExpectation.results = &MPCClientMockRetrieveShareResults{rp1, err}
	mmRetrieveShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRetrieveShare.mock
}

// Set uses given function f to mock the MPCClient.RetrieveShare method
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Set(f func(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption) (rp1 *mpc_api.RetrieveShareResponse, err error)) *MPCClientMock {
	if mmRetrieveShare.defaultExpectation != nil {
		mmRetrieveShare.mock.t.Fatalf("Default expectation is already set for the MPCClient.RetrieveShare method")
	}

	if len(mmRetrieveShare.expectations) > 0 {
		mmRetrieveShare.mock.t.Fatalf("Some expectations are already set for the MPCClient.RetrieveShare method")
	}

	mmRetrieveShare.mock.funcRetrieveShare = f
	mmRetrieveShare.mock.funcRetrieveShareOrigin = minimock.CallerInfo(1)
	return mmRetrieveShare.mock
}

// When sets expectation for the MPCClient.RetrieveShare which will trigger the result defined by the following
// Then helper
func (mmRetrieveShare *mMPCClientMockRetrieveShare) When(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption) *MPCClientMockRetrieveShareExpectation {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	expectation := &MPCClientMockRetrieveShareExpectation{
		mock:               mmRetrieveShare.mock,
		params:             &MPCClientMockRetrieveShareParams{ctx, in, opts},
		expectationOrigins: MPCClientMockRetrieveShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRetrieveShare.expectations = append(mmRetrieveShare.expectations, expectation)
	return expectation
}

// Then sets up MPCClient.RetrieveShare return parameters for the expectation previously defined by the When method
func (e *MPCClientMockRetrieveShareExpectation) Then(rp1 *mpc_api.RetrieveShareResponse, err error) *MPCClientMock {
	e.results = &MPCClientMockRetrieveShareResults{rp1, err}
	return e.mock
}

// Times sets number of times MPCClient.RetrieveShare should be invoked
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Times(n uint64) *mMPCClientMockRetrieveShare {
	if n == 0 {
		mmRetrieveShare.mock.t.Fatalf("Times of MPCClientMock.RetrieveShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRetrieveShare.expectedInvocations, n)
	mmRetrieveShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRetrieveShare
}

func (mmRetrieveShare *mMPCClientMockRetrieveShare) invocationsDone() bool {
	if len(mmRetrieveShare.expectations) == 0 && mmRetrieveShare.defaultExpectation == nil && mmRetrieveShare.mock.funcRetrieveShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRetrieveShare.mock.afterRetrieveShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRetrieveShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RetrieveShare implements mm_twofaService.MPCClient
func (mmRetrieveShare *MPCClientMock) RetrieveShare(ctx context.Context, in *mpc_api.RetrieveShareRequest, opts ...grpc.CallOption) (rp1 *mpc_api.RetrieveShareResponse, err error) {
	mm_atomic.AddUint64(&mmRetrieveShare.beforeRetrieveShareCounter, 1)
	defer mm_atomic.AddUint64(&mmRetrieveShare.afterRetrieveShareCounter, 1)

	mmRetrieveShare.t.Helper()

	if mmRetrieveShare.inspectFuncRetrieveShare != nil {
		mmRetrieveShare.inspectFuncRetrieveShare(ctx, in, opts...)
	}

	mm_params := MPCClientMockRetrieveShareParams{ctx, in, opts}

	// Record call args
	mmRetrieveShare.RetrieveShareMock.mutex.Lock()
	mmRetrieveShare.RetrieveShareMock.callArgs = append(mmRetrieveShare.RetrieveShareMock.callArgs, &mm_params)
	mmRetrieveShare.RetrieveShareMock.mutex.Unlock()

	for _, e := range mmRetrieveShare.RetrieveShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmRetrieveShare.RetrieveShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRetrieveShare.RetrieveShareMock.defaultExpectation.Counter, 1)
		mm_want := mmRetrieveShare.RetrieveShareMock.defaultExpectation.params
		mm_want_ptrs := mmRetrieveShare.RetrieveShareMock.defaultExpectation.paramPtrs

		mm_got := MPCClientMockRetrieveShareParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRetrieveShare.RetrieveShareMock.defaultExpectation.results
		if mm_results == nil {
			mmRetrieveShare.t.Fatal("No results are set for the MPCClientMock.RetrieveShare")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmRetrieveShare.funcRetrieveShare != nil {
		return mmRetrieveShare.funcRetrieveShare(ctx, in, opts...)
	}
	mmRetrieveShare.t.Fatalf("Unexpected call to MPCClientMock.RetrieveShare. %v %v %v", ctx, in, opts)
	return
}

// RetrieveShareAfterCounter returns a count of finished MPCClientMock.RetrieveShare invocations
func (mmRetrieveShare *MPCClientMock) RetrieveShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRetrieveShare.afterRetrieveShareCounter)
}

// RetrieveShareBeforeCounter returns a count of MPCClientMock.RetrieveShare invocations
func (mmRetrieveShare *MPCClientMock) RetrieveShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRetrieveShare.beforeRetrieveShareCounter)
}

// Calls returns a list of arguments used in each call to MPCClientMock.RetrieveShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Calls() []*MPCClientMockRetrieveShareParams {
	mmRetrieveShare.mutex.RLock()

	argCopy := make([]*MPCClientMockRetrieveShareParams, len(mmRetrieveShare.callArgs))
	copy(argCopy, mmRetrieveShare.callArgs)

	mmRetrieveShare.mutex.RUnlock()

	return argCopy
}

// MinimockRetrieveShareDone returns true if the count of the RetrieveShare invocations corresponds
// the number of defined expectations
func (m *MPCClientMock) MinimockRetrieveShareDone() bool {
	if m.RetrieveShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RetrieveShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RetrieveShareMock.invocationsDone()
}

// MinimockRetrieveShareInspect logs each unmet expectation
func (m *MPCClientMock) MinimockRetrieveShareInspect() {
	for _, e := range m.RetrieveShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRetrieveShareCounter := mm_atomic.LoadUint64(&m.afterRetrieveShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RetrieveShareMock.defaultExpectation != nil && afterRetrieveShareCounter < 1 {
		if m.RetrieveShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s", m.RetrieveShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s with params: %#v", m.RetrieveShareMock.defaultExpectation.expectationOrigins.origin, *m.RetrieveShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRetrieveShare != nil && afterRetrieveShareCounter < 1 {
		m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s", m.funcRetrieveShareOrigin)
	}

	if !m.RetrieveShareMock.invocationsDone() && afterRetrieveShareCounter > 0 {
		m.t.Errorf("Expected %d calls to MPCClientMock.RetrieveShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RetrieveShareMock.expectedInvocations), m.RetrieveShareMock.expectedInvocationsOrigin, afterRetrieveShareCounter)
	}
}

type mMPCClientMockStoreShare struct {
	optional           bool
	mock               *MPCClientMock
	defaultExpectation *MPCClientMockStoreShareExpectation
	expectations       []*MPCClientMockStoreShareExpectation

	callArgs []*MPCClientMockStoreShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MPCClientMockStoreShareExpectation specifies expectation struct of the MPCClient.StoreShare
type MPCClientMockStoreShareExpectation struct {
	mock               *MPCClientMock
	params             *MPCClientMockStoreShareParams
	paramPtrs          *MPCClientMockStoreShareParamPtrs
	expectationOrigins MPCClientMockStoreShareExpectationOrigins
	results            *MPCClientMockStoreShareResults
	returnOrigin       string
	Counter            uint64
}

// MPCClientMockStoreShareParams contains parameters of the MPCClient.StoreShare
type MPCClientMockStoreShareParams struct {
	ctx  context.Context
	in   *mpc_api.StoreShareRequest
	opts []grpc.CallOption
}

// MPCClientMockStoreShareParamPtrs contains pointers to parameters of the MPCClient.StoreShare
type MPCClientMockStoreShareParamPtrs struct {
	ctx  *context.Context
	in   **mpc_api.StoreShareRequest
	opts *[]grpc.CallOption
}

// MPCClientMockStoreShareResults contains results of the MPCClient.StoreShare
type MPCClientMockStoreShareResults struct {
	sp1 *mpc_api.StoreShareResponse
	err error
}

// MPCClientMockStoreShareOrigins contains origins of expectations of the MPCClient.StoreShare
type MPCClientMockStoreShareExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStoreShare *mMPCClientMockStoreShare) Optional() *mMPCClientMockStoreShare {
	mmStoreShare.optional = true
	return mmStoreShare
}

// Expect sets up expected params for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) Expect(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.paramPtrs != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by ExpectParams functions")
	}

	mmStoreShare.defaultExpectation.params = &MPCClientMockStoreShareParams{ctx, in, opts}
	mmStoreShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStoreShare.expectations {
		if minimock.Equal(e.params, mmStoreShare.defaultExpectation.params) {
			mmStoreShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStoreShare.defaultExpectation.params)
		}
	}

	return mmStoreShare
}

// ExpectCtxParam1 sets up expected param ctx for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectCtxParam1(ctx context.Context) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmStoreShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStoreShare
}

// ExpectInParam2 sets up expected param in for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectInParam2(in *mpc_api.StoreShareRequest) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.in = &in
	mmStoreShare.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmStoreShare
}

// ExpectOptsParam3 sets up expected param opts for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectOptsParam3(opts ...grpc.CallOption) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.opts = &opts
	mmStoreShare.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmStoreShare
}

// Inspect accepts an inspector function that has same arguments as the MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) Inspect(f func(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption)) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.inspectFuncStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("Inspect function is already set for MPCClientMock.StoreShare")
	}

	mmStoreShare.mock.inspectFuncStoreShare = f

	return mmStoreShare
}

// Return sets up results that will be returned by MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) Return(sp1 *mpc_api.StoreShareResponse, err error) *MPCClientMock {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{mock: mmStoreShare.mock}
	}
	mmStoreShare.defaultExpectation.results = &MPCClientMockStoreShareResults{sp1, err}
	mmStoreShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStoreShare.mock
}

// Set uses given function f to mock the MPCClient.StoreShare method
func (mmStoreShare *mMPCClientMockStoreShare) Set(f func(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption) (sp1 *mpc_api.StoreShareResponse, err error)) *MPCClientMock {
	if mmStoreShare.defaultExpectation != nil {
		mmStoreShare.mock.t.Fatalf("Default expectation is already set for the MPCClient.StoreShare method")
	}

	if len(mmStoreShare.expectations) > 0 {
		mmStoreShare.mock.t.Fatalf("Some expectations are already set for the MPCClient.StoreShare method")
	}

	mmStoreShare.mock.funcStoreShare = f
	mmStoreShare.mock.funcStoreShareOrigin = minimock.CallerInfo(1)
	return mmStoreShare.mock
}

// When sets expectation for the MPCClient.StoreShare which will trigger the result defined by the following
// Then helper
func (mmStoreShare *mMPCClientMockStoreShare) When(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption) *MPCClientMockStoreShareExpectation {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	expectation := &MPCClientMockStoreShareExpectation{
		mock:               mmStoreShare.mock,
		params:             &MPCClientMockStoreShareParams{ctx, in, opts},
		expectationOrigins: MPCClientMockStoreShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStoreShare.expectations = append(mmStoreShare.expectations, expectation)
	return expectation
}

// Then sets up MPCClient.StoreShare return parameters for the expectation previously defined by the When method
func (e *MPCClientMockStoreShareExpectation) Then(sp1 *mpc_api.StoreShareResponse, err error) *MPCClientMock {
	e.results = &MPCClientMockStoreShareResults{sp1, err}
	return e.mock
}

// Times sets number of times MPCClient.StoreShare should be invoked
func (mmStoreShare *mMPCClientMockStoreShare) Times(n uint64) *mMPCClientMockStoreShare {
	if n == 0 {
		mmStoreShare.mock.t.Fatalf("Times of MPCClientMock.StoreShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStoreShare.expectedInvocations, n)
	mmStoreShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStoreShare
}

func (mmStoreShare *mMPCClientMockStoreShare) invocationsDone() bool {
	if len(mmStoreShare.expectations) == 0 && mmStoreShare.defaultExpectation == nil && mmStoreShare.mock.funcStoreShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStoreShare.mock.afterStoreShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStoreShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StoreShare implements mm_twofaService.MPCClient
func (mmStoreShare *MPCClientMock) StoreShare(ctx context.Context, in *mpc_api.StoreShareRequest, opts ...grpc.CallOption) (sp1 *mpc_api.StoreShareResponse, err error) {
	mm_atomic.AddUint64(&mmStoreShare.beforeStoreShareCounter, 1)
	defer mm_atomic.AddUint64(&mmStoreShare.afterStoreShareCounter, 1)

	mmStoreShare.t.Helper()

	if mmStoreShare.inspectFuncStoreShare != nil {
		mmStoreShare.inspectFuncStoreShare(ctx, in, opts...)
	}

	mm_params := MPCClientMockStoreShareParams{ctx, in, opts}

	// Record call args
	mmStoreShare.StoreShareMock.mutex.Lock()
	mmStoreShare.StoreShareMock.callArgs = append(mmStoreShare.StoreShareMock.callArgs, &mm_params)
	mmStoreShare.StoreShareMock.mutex.Unlock()

	for _, e := range mmStoreShare.StoreShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmStoreShare.StoreShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStoreShare.StoreShareMock.defaultExpectation.Counter, 1)
		mm_want := mmStoreShare.StoreShareMock.defaultExpectation.params
		mm_want_ptrs := mmStoreShare.StoreShareMock.defaultExpectation.paramPtrs

		mm_got := MPCClientMockStoreShareParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStoreShare.StoreShareMock.defaultExpectation.results
		if mm_results == nil {
			mmStoreShare.t.Fatal("No results are set for the MPCClientMock.StoreShare")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmStoreShare.funcStoreShare != nil {
		return mmStoreShare.funcStoreShare(ctx, in, opts...)
	}
	mmStoreShare.t.Fatalf("Unexpected call to MPCClientMock.StoreShare. %v %v %v", ctx, in, opts)
	return
}

// StoreShareAfterCounter returns a count of finished MPCClientMock.StoreShare invocations
func (mmStoreShare *MPCClientMock) StoreShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStoreShare.afterStoreShareCounter)
}

// StoreShareBeforeCounter returns a count of MPCClientMock.StoreShare invocations
func (mmStoreShare *MPCClientMock) StoreShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStoreShare.beforeStoreShareCounter)
}

// Calls returns a list of arguments used in each call to MPCClientMock.StoreShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStoreShare *mMPCClientMockStoreShare) Calls() []*MPCClientMockStoreShareParams {
	mmStoreShare.mutex.RLock()

	argCopy := make([]*MPCClientMockStoreShareParams, len(mmStoreShare.callArgs))
	copy(argCopy, mmStoreShare.callArgs)

	mmStoreShare.mutex.RUnlock()

	return argCopy
}

// MinimockStoreShareDone returns true if the count of the StoreShare invocations corresponds
// the number of defined expectations
func (m *MPCClientMock) MinimockStoreShareDone() bool {
	if m.StoreShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StoreShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StoreShareMock.invocationsDone()
}

// MinimockStoreShareInspect logs each unmet expectation
func (m *MPCClientMock) MinimockStoreShareInspect() {
	for _, e := range m.StoreShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStoreShareCounter := mm_atomic.LoadUint64(&m.afterStoreShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StoreShareMock.defaultExpectation != nil && afterStoreShareCounter < 1 {
		if m.StoreShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s", m.StoreShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s with params: %#v", m.StoreShareMock.defaultExpectation.expectationOrigins.origin, *m.StoreShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStoreShare != nil && afterStoreShareCounter < 1 {
		m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s", m.funcStoreShareOrigin)
	}

	if !m.StoreShareMock.invocationsDone() && afterStoreShareCounter > 0 {
		m.t.Errorf("Expected %d calls to MPCClientMock.StoreShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StoreShareMock.expectedInvocations), m.StoreShareMock.expectedInvocationsOrigin, afterStoreShareCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MPCClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteShareInspect()

			m.MinimockRetrieveShareInspect()

			m.MinimockStoreShareInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MPCClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MPCClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteShareDone() &&
		m.MinimockRetrieveShareDone() &&
		m.MinimockStoreShareDone()
}
