// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/vkr/twofa/internal/services/twofaService.MPCClient -o mpc_client_mock.go -n MPCClientMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// MPCClientMock implements mm_twofaService.MPCClient
type MPCClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteShare          func(ctx context.Context, userID string) (err error)
	funcDeleteShareOrigin    string
	inspectFuncDeleteShare   func(ctx context.Context, userID string)
	afterDeleteShareCounter  uint64
	beforeDeleteShareCounter uint64
	DeleteShareMock          mMPCClientMockDeleteShare

	funcRetrieveShare          func(ctx context.Context, userID string, shareIndex int) (ba1 []byte, err error)
	funcRetrieveShareOrigin    string
	inspectFuncRetrieveShare   func(ctx context.Context, userID string, shareIndex int)
	afterRetrieveShareCounter  uint64
	beforeRetrieveShareCounter uint64
	RetrieveShareMock          mMPCClientMockRetrieveShare

	funcStoreShare          func(ctx context.Context, userID string, shareIndex int, shareData []byte) (err error)
	funcStoreShareOrigin    string
	inspectFuncStoreShare   func(ctx context.Context, userID string, shareIndex int, shareData []byte)
	afterStoreShareCounter  uint64
	beforeStoreShareCounter uint64
	StoreShareMock          mMPCClientMockStoreShare
}

// NewMPCClientMock returns a mock for mm_twofaService.MPCClient
func NewMPCClientMock(t minimock.Tester) *MPCClientMock {
	m := &MPCClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteShareMock = mMPCClientMockDeleteShare{mock: m}
	m.DeleteShareMock.callArgs = []*MPCClientMockDeleteShareParams{}

	m.RetrieveShareMock = mMPCClientMockRetrieveShare{mock: m}
	m.RetrieveShareMock.callArgs = []*MPCClientMockRetrieveShareParams{}

	m.StoreShareMock = mMPCClientMockStoreShare{mock: m}
	m.StoreShareMock.callArgs = []*MPCClientMockStoreShareParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMPCClientMockDeleteShare struct {
	optional           bool
	mock               *MPCClientMock
	defaultExpectation *MPCClientMockDeleteShareExpectation
	expectations       []*MPCClientMockDeleteShareExpectation

	callArgs []*MPCClientMockDeleteShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MPCClientMockDeleteShareExpectation specifies expectation struct of the MPCClient.DeleteShare
type MPCClientMockDeleteShareExpectation struct {
	mock               *MPCClientMock
	params             *MPCClientMockDeleteShareParams
	paramPtrs          *MPCClientMockDeleteShareParamPtrs
	expectationOrigins MPCClientMockDeleteShareExpectationOrigins
	results            *MPCClientMockDeleteShareResults
	returnOrigin       string
	Counter            uint64
}

// MPCClientMockDeleteShareParams contains parameters of the MPCClient.DeleteShare
type MPCClientMockDeleteShareParams struct {
	ctx    context.Context
	userID string
}

// MPCClientMockDeleteShareParamPtrs contains pointers to parameters of the MPCClient.DeleteShare
type MPCClientMockDeleteShareParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// MPCClientMockDeleteShareResults contains results of the MPCClient.DeleteShare
type MPCClientMockDeleteShareResults struct {
	err error
}

// MPCClientMockDeleteShareOrigins contains origins of expectations of the MPCClient.DeleteShare
type MPCClientMockDeleteShareExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteShare *mMPCClientMockDeleteShare) Optional() *mMPCClientMockDeleteShare {
	mmDeleteShare.optional = true
	return mmDeleteShare
}

// Expect sets up expected params for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) Expect(ctx context.Context, userID string) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.paramPtrs != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by ExpectParams functions")
	}

	mmDeleteShare.defaultExpectation.params = &MPCClientMockDeleteShareParams{ctx, userID}
	mmDeleteShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteShare.expectations {
		if minimock.Equal(e.params, mmDeleteShare.defaultExpectation.params) {
			mmDeleteShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteShare.defaultExpectation.params)
		}
	}

	return mmDeleteShare
}

// ExpectCtxParam1 sets up expected param ctx for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) ExpectCtxParam1(ctx context.Context) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.params != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Expect")
	}

	if mmDeleteShare.defaultExpectation.paramPtrs == nil {
		mmDeleteShare.defaultExpectation.paramPtrs = &MPCClientMockDeleteShareParamPtrs{}
	}
	mmDeleteShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteShare
}

// ExpectUserIDParam2 sets up expected param userID for MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) ExpectUserIDParam2(userID string) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{}
	}

	if mmDeleteShare.defaultExpectation.params != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Expect")
	}

	if mmDeleteShare.defaultExpectation.paramPtrs == nil {
		mmDeleteShare.defaultExpectation.paramPtrs = &MPCClientMockDeleteShareParamPtrs{}
	}
	mmDeleteShare.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteShare.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteShare
}

// Inspect accepts an inspector function that has same arguments as the MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) Inspect(f func(ctx context.Context, userID string)) *mMPCClientMockDeleteShare {
	if mmDeleteShare.mock.inspectFuncDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("Inspect function is already set for MPCClientMock.DeleteShare")
	}

	mmDeleteShare.mock.inspectFuncDeleteShare = f

	return mmDeleteShare
}

// Return sets up results that will be returned by MPCClient.DeleteShare
func (mmDeleteShare *mMPCClientMockDeleteShare) Return(err error) *MPCClientMock {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	if mmDeleteShare.defaultExpectation == nil {
		mmDeleteShare.defaultExpectation = &MPCClientMockDeleteShareExpectation{mock: mmDeleteShare.mock}
	}
	mmDeleteShare.defaultExpectation.results = &MPCClientMockDeleteShareResults{err}
	mmDeleteShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteShare.mock
}

// Set uses given function f to mock the MPCClient.DeleteShare method
func (mmDeleteShare *mMPCClientMockDeleteShare) Set(f func(ctx context.Context, userID string) (err error)) *MPCClientMock {
	if mmDeleteShare.defaultExpectation != nil {
		mmDeleteShare.mock.t.Fatalf("Default expectation is already set for the MPCClient.DeleteShare method")
	}

	if len(mmDeleteShare.expectations) > 0 {
		mmDeleteShare.mock.t.Fatalf("Some expectations are already set for the MPCClient.DeleteShare method")
	}

	mmDeleteShare.mock.funcDeleteShare = f
	mmDeleteShare.mock.funcDeleteShareOrigin = minimock.CallerInfo(1)
	return mmDeleteShare.mock
}

// When sets expectation for the MPCClient.DeleteShare which will trigger the result defined by the following
// Then helper
func (mmDeleteShare *mMPCClientMockDeleteShare) When(ctx context.Context, userID string) *MPCClientMockDeleteShareExpectation {
	if mmDeleteShare.mock.funcDeleteShare != nil {
		mmDeleteShare.mock.t.Fatalf("MPCClientMock.DeleteShare mock is already set by Set")
	}

	expectation := &MPCClientMockDeleteShareExpectation{
		mock:               mmDeleteShare.mock,
		params:             &MPCClientMockDeleteShareParams{ctx, userID},
		expectationOrigins: MPCClientMockDeleteShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteShare.expectations = append(mmDeleteShare.expectations, expectation)
	return expectation
}

// Then sets up MPCClient.DeleteShare return parameters for the expectation previously defined by the When method
func (e *MPCClientMockDeleteShareExpectation) Then(err error) *MPCClientMock {
	e.results = &MPCClientMockDeleteShareResults{err}
	return e.mock
}

// Times sets number of times MPCClient.DeleteShare should be invoked
func (mmDeleteShare *mMPCClientMockDeleteShare) Times(n uint64) *mMPCClientMockDeleteShare {
	if n == 0 {
		mmDeleteShare.mock.t.Fatalf("Times of MPCClientMock.DeleteShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteShare.expectedInvocations, n)
	mmDeleteShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteShare
}

func (mmDeleteShare *mMPCClientMockDeleteShare) invocationsDone() bool {
	if len(mmDeleteShare.expectations) == 0 && mmDeleteShare.defaultExpectation == nil && mmDeleteShare.mock.funcDeleteShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteShare.mock.afterDeleteShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteShare implements mm_twofaService.MPCClient
func (mmDeleteShare *MPCClientMock) DeleteShare(ctx context.Context, userID string) (err error) {
	mm_atomic.AddUint64(&mmDeleteShare.beforeDeleteShareCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteShare.afterDeleteShareCounter, 1)

	mmDeleteShare.t.Helper()

	if mmDeleteShare.inspectFuncDeleteShare != nil {
		mmDeleteShare.inspectFuncDeleteShare(ctx, userID)
	}

	mm_params := MPCClientMockDeleteShareParams{ctx, userID}

	// Record call args
	mmDeleteShare.DeleteShareMock.mutex.Lock()
	mmDeleteShare.DeleteShareMock.callArgs = append(mmDeleteShare.DeleteShareMock.callArgs, &mm_params)
	mmDeleteShare.DeleteShareMock.mutex.Unlock()

	for _, e := range mmDeleteShare.DeleteShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteShare.DeleteShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteShare.DeleteShareMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteShare.DeleteShareMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteShare.DeleteShareMock.defaultExpectation.paramPtrs

		mm_got := MPCClientMockDeleteShareParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteShare.t.Errorf("MPCClientMock.DeleteShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteShare.DeleteShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteShare.DeleteShareMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteShare.t.Fatal("No results are set for the MPCClientMock.DeleteShare")
		}
		return (*mm_results).err
	}
	if mmDeleteShare.funcDeleteShare != nil {
		return mmDeleteShare.funcDeleteShare(ctx, userID)
	}
	mmDeleteShare.t.Fatalf("Unexpected call to MPCClientMock.DeleteShare. %v %v", ctx, userID)
	return
}

// DeleteShareAfterCounter returns a count of finished MPCClientMock.DeleteShare invocations
func (mmDeleteShare *MPCClientMock) DeleteShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteShare.afterDeleteShareCounter)
}

// DeleteShareBeforeCounter returns a count of MPCClientMock.DeleteShare invocations
func (mmDeleteShare *MPCClientMock) DeleteShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteShare.beforeDeleteShareCounter)
}

// Calls returns a list of arguments used in each call to MPCClientMock.DeleteShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteShare *mMPCClientMockDeleteShare) Calls() []*MPCClientMockDeleteShareParams {
	mmDeleteShare.mutex.RLock()

	argCopy := make([]*MPCClientMockDeleteShareParams, len(mmDeleteShare.callArgs))
	copy(argCopy, mmDeleteShare.callArgs)

	mmDeleteShare.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteShareDone returns true if the count of the DeleteShare invocations corresponds
// the number of defined expectations
func (m *MPCClientMock) MinimockDeleteShareDone() bool {
	if m.DeleteShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteShareMock.invocationsDone()
}

// MinimockDeleteShareInspect logs each unmet expectation
func (m *MPCClientMock) MinimockDeleteShareInspect() {
	for _, e := range m.DeleteShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteShareCounter := mm_atomic.LoadUint64(&m.afterDeleteShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteShareMock.defaultExpectation != nil && afterDeleteShareCounter < 1 {
		if m.DeleteShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s", m.DeleteShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s with params: %#v", m.DeleteShareMock.defaultExpectation.expectationOrigins.origin, *m.DeleteShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteShare != nil && afterDeleteShareCounter < 1 {
		m.t.Errorf("Expected call to MPCClientMock.DeleteShare at\n%s", m.funcDeleteShareOrigin)
	}

	if !m.DeleteShareMock.invocationsDone() && afterDeleteShareCounter > 0 {
		m.t.Errorf("Expected %d calls to MPCClientMock.DeleteShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteShareMock.expectedInvocations), m.DeleteShareMock.expectedInvocationsOrigin, afterDeleteShareCounter)
	}
}

type mMPCClientMockRetrieveShare struct {
	optional           bool
	mock               *MPCClientMock
	defaultExpectation *MPCClientMockRetrieveShareExpectation
	expectations       []*MPCClientMockRetrieveShareExpectation

	callArgs []*MPCClientMockRetrieveShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MPCClientMockRetrieveShareExpectation specifies expectation struct of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareExpectation struct {
	mock               *MPCClientMock
	params             *MPCClientMockRetrieveShareParams
	paramPtrs          *MPCClientMockRetrieveShareParamPtrs
	expectationOrigins MPCClientMockRetrieveShareExpectationOrigins
	results            *MPCClientMockRetrieveShareResults
	returnOrigin       string
	Counter            uint64
}

// MPCClientMockRetrieveShareParams contains parameters of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareParams struct {
	ctx        context.Context
	userID     string
	shareIndex int
}

// MPCClientMockRetrieveShareParamPtrs contains pointers to parameters of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareParamPtrs struct {
	ctx        *context.Context
	userID     *string
	shareIndex *int
}

// MPCClientMockRetrieveShareResults contains results of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareResults struct {
	ba1 []byte
	err error
}

// MPCClientMockRetrieveShareOrigins contains origins of expectations of the MPCClient.RetrieveShare
type MPCClientMockRetrieveShareExpectationOrigins struct {
	origin           string
	originCtx        string
	originUserID     string
	originShareIndex string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Optional() *mMPCClientMockRetrieveShare {
	mmRetrieveShare.optional = true
	return mmRetrieveShare
}

// Expect sets up expected params for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Expect(ctx context.Context, userID string, shareIndex int) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by ExpectParams functions")
	}

	mmRetrieveShare.defaultExpectation.params = &MPCClientMockRetrieveShareParams{ctx, userID, shareIndex}
	mmRetrieveShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRetrieveShare.expectations {
		if minimock.Equal(e.params, mmRetrieveShare.defaultExpectation.params) {
			mmRetrieveShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRetrieveShare.defaultExpectation.params)
		}
	}

	return mmRetrieveShare
}

// ExpectCtxParam1 sets up expected param ctx for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) ExpectCtxParam1(ctx context.Context) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.params != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Expect")
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs == nil {
		mmRetrieveShare.defaultExpectation.paramPtrs = &MPCClientMockRetrieveShareParamPtrs{}
	}
	mmRetrieveShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmRetrieveShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRetrieveShare
}

// ExpectUserIDParam2 sets up expected param userID for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) ExpectUserIDParam2(userID string) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.params != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Expect")
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs == nil {
		mmRetrieveShare.defaultExpectation.paramPtrs = &MPCClientMockRetrieveShareParamPtrs{}
	}
	mmRetrieveShare.defaultExpectation.paramPtrs.userID = &userID
	mmRetrieveShare.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmRetrieveShare
}

// ExpectShareIndexParam3 sets up expected param shareIndex for MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) ExpectShareIndexParam3(shareIndex int) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{}
	}

	if mmRetrieveShare.defaultExpectation.params != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Expect")
	}

	if mmRetrieveShare.defaultExpectation.paramPtrs == nil {
		mmRetrieveShare.defaultExpectation.paramPtrs = &MPCClientMockRetrieveShareParamPtrs{}
	}
	mmRetrieveShare.defaultExpectation.paramPtrs.shareIndex = &shareIndex
	mmRetrieveShare.defaultExpectation.expectationOrigins.originShareIndex = minimock.CallerInfo(1)

	return mmRetrieveShare
}

// Inspect accepts an inspector function that has same arguments as the MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Inspect(f func(ctx context.Context, userID string, shareIndex int)) *mMPCClientMockRetrieveShare {
	if mmRetrieveShare.mock.inspectFuncRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("Inspect function is already set for MPCClientMock.RetrieveShare")
	}

	mmRetrieveShare.mock.inspectFuncRetrieveShare = f

	return mmRetrieveShare
}

// Return sets up results that will be returned by MPCClient.RetrieveShare
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Return(ba1 []byte, err error) *MPCClientMock {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	if mmRetrieveShare.defaultExpectation == nil {
		mmRetrieveShare.defaultExpectation = &MPCClientMockRetrieveShareExpectation{mock: mmRetrieveShare.mock}
	}
	mmRetrieveShare.defaultExpectation.results = &MPCClientMockRetrieveShareResults{ba1, err}
	mmRetrieveShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRetrieveShare.mock
}

// Set uses given function f to mock the MPCClient.RetrieveShare method
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Set(f func(ctx context.Context, userID string, shareIndex int) (ba1 []byte, err error)) *MPCClientMock {
	if mmRetrieveShare.defaultExpectation != nil {
		mmRetrieveShare.mock.t.Fatalf("Default expectation is already set for the MPCClient.RetrieveShare method")
	}

	if len(mmRetrieveShare.expectations) > 0 {
		mmRetrieveShare.mock.t.Fatalf("Some expectations are already set for the MPCClient.RetrieveShare method")
	}

	mmRetrieveShare.mock.funcRetrieveShare = f
	mmRetrieveShare.mock.funcRetrieveShareOrigin = minimock.CallerInfo(1)
	return mmRetrieveShare.mock
}

// When sets expectation for the MPCClient.RetrieveShare which will trigger the result defined by the following
// Then helper
func (mmRetrieveShare *mMPCClientMockRetrieveShare) When(ctx context.Context, userID string, shareIndex int) *MPCClientMockRetrieveShareExpectation {
	if mmRetrieveShare.mock.funcRetrieveShare != nil {
		mmRetrieveShare.mock.t.Fatalf("MPCClientMock.RetrieveShare mock is already set by Set")
	}

	expectation := &MPCClientMockRetrieveShareExpectation{
		mock:               mmRetrieveShare.mock,
		params:             &MPCClientMockRetrieveShareParams{ctx, userID, shareIndex},
		expectationOrigins: MPCClientMockRetrieveShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRetrieveShare.expectations = append(mmRetrieveShare.expectations, expectation)
	return expectation
}

// Then sets up MPCClient.RetrieveShare return parameters for the expectation previously defined by the When method
func (e *MPCClientMockRetrieveShareExpectation) Then(ba1 []byte, err error) *MPCClientMock {
	e.results = &MPCClientMockRetrieveShareResults{ba1, err}
	return e.mock
}

// Times sets number of times MPCClient.RetrieveShare should be invoked
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Times(n uint64) *mMPCClientMockRetrieveShare {
	if n == 0 {
		mmRetrieveShare.mock.t.Fatalf("Times of MPCClientMock.RetrieveShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRetrieveShare.expectedInvocations, n)
	mmRetrieveShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRetrieveShare
}

func (mmRetrieveShare *mMPCClientMockRetrieveShare) invocationsDone() bool {
	if len(mmRetrieveShare.expectations) == 0 && mmRetrieveShare.defaultExpectation == nil && mmRetrieveShare.mock.funcRetrieveShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRetrieveShare.mock.afterRetrieveShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRetrieveShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RetrieveShare implements mm_twofaService.MPCClient
func (mmRetrieveShare *MPCClientMock) RetrieveShare(ctx context.Context, userID string, shareIndex int) (ba1 []byte, err error) {
	mm_atomic.AddUint64(&mmRetrieveShare.beforeRetrieveShareCounter, 1)
	defer mm_atomic.AddUint64(&mmRetrieveShare.afterRetrieveShareCounter, 1)

	mmRetrieveShare.t.Helper()

	if mmRetrieveShare.inspectFuncRetrieveShare != nil {
		mmRetrieveShare.inspectFuncRetrieveShare(ctx, userID, shareIndex)
	}

	mm_params := MPCClientMockRetrieveShareParams{ctx, userID, shareIndex}

	// Record call args
	mmRetrieveShare.RetrieveShareMock.mutex.Lock()
	mmRetrieveShare.RetrieveShareMock.callArgs = append(mmRetrieveShare.RetrieveShareMock.callArgs, &mm_params)
	mmRetrieveShare.RetrieveShareMock.mutex.Unlock()

	for _, e := range mmRetrieveShare.RetrieveShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmRetrieveShare.RetrieveShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRetrieveShare.RetrieveShareMock.defaultExpectation.Counter, 1)
		mm_want := mmRetrieveShare.RetrieveShareMock.defaultExpectation.params
		mm_want_ptrs := mmRetrieveShare.RetrieveShareMock.defaultExpectation.paramPtrs

		mm_got := MPCClientMockRetrieveShareParams{ctx, userID, shareIndex}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.shareIndex != nil && !minimock.Equal(*mm_want_ptrs.shareIndex, mm_got.shareIndex) {
				mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameter shareIndex, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.originShareIndex, *mm_want_ptrs.shareIndex, mm_got.shareIndex, minimock.Diff(*mm_want_ptrs.shareIndex, mm_got.shareIndex))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRetrieveShare.t.Errorf("MPCClientMock.RetrieveShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRetrieveShare.RetrieveShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRetrieveShare.RetrieveShareMock.defaultExpectation.results
		if mm_results == nil {
			mmRetrieveShare.t.Fatal("No results are set for the MPCClientMock.RetrieveShare")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmRetrieveShare.funcRetrieveShare != nil {
		return mmRetrieveShare.funcRetrieveShare(ctx, userID, shareIndex)
	}
	mmRetrieveShare.t.Fatalf("Unexpected call to MPCClientMock.RetrieveShare. %v %v %v", ctx, userID, shareIndex)
	return
}

// RetrieveShareAfterCounter returns a count of finished MPCClientMock.RetrieveShare invocations
func (mmRetrieveShare *MPCClientMock) RetrieveShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRetrieveShare.afterRetrieveShareCounter)
}

// RetrieveShareBeforeCounter returns a count of MPCClientMock.RetrieveShare invocations
func (mmRetrieveShare *MPCClientMock) RetrieveShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRetrieveShare.beforeRetrieveShareCounter)
}

// Calls returns a list of arguments used in each call to MPCClientMock.RetrieveShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRetrieveShare *mMPCClientMockRetrieveShare) Calls() []*MPCClientMockRetrieveShareParams {
	mmRetrieveShare.mutex.RLock()

	argCopy := make([]*MPCClientMockRetrieveShareParams, len(mmRetrieveShare.callArgs))
	copy(argCopy, mmRetrieveShare.callArgs)

	mmRetrieveShare.mutex.RUnlock()

	return argCopy
}

// MinimockRetrieveShareDone returns true if the count of the RetrieveShare invocations corresponds
// the number of defined expectations
func (m *MPCClientMock) MinimockRetrieveShareDone() bool {
	if m.RetrieveShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RetrieveShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RetrieveShareMock.invocationsDone()
}

// MinimockRetrieveShareInspect logs each unmet expectation
func (m *MPCClientMock) MinimockRetrieveShareInspect() {
	for _, e := range m.RetrieveShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRetrieveShareCounter := mm_atomic.LoadUint64(&m.afterRetrieveShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RetrieveShareMock.defaultExpectation != nil && afterRetrieveShareCounter < 1 {
		if m.RetrieveShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s", m.RetrieveShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s with params: %#v", m.RetrieveShareMock.defaultExpectation.expectationOrigins.origin, *m.RetrieveShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRetrieveShare != nil && afterRetrieveShareCounter < 1 {
		m.t.Errorf("Expected call to MPCClientMock.RetrieveShare at\n%s", m.funcRetrieveShareOrigin)
	}

	if !m.RetrieveShareMock.invocationsDone() && afterRetrieveShareCounter > 0 {
		m.t.Errorf("Expected %d calls to MPCClientMock.RetrieveShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RetrieveShareMock.expectedInvocations), m.RetrieveShareMock.expectedInvocationsOrigin, afterRetrieveShareCounter)
	}
}

type mMPCClientMockStoreShare struct {
	optional           bool
	mock               *MPCClientMock
	defaultExpectation *MPCClientMockStoreShareExpectation
	expectations       []*MPCClientMockStoreShareExpectation

	callArgs []*MPCClientMockStoreShareParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MPCClientMockStoreShareExpectation specifies expectation struct of the MPCClient.StoreShare
type MPCClientMockStoreShareExpectation struct {
	mock               *MPCClientMock
	params             *MPCClientMockStoreShareParams
	paramPtrs          *MPCClientMockStoreShareParamPtrs
	expectationOrigins MPCClientMockStoreShareExpectationOrigins
	results            *MPCClientMockStoreShareResults
	returnOrigin       string
	Counter            uint64
}

// MPCClientMockStoreShareParams contains parameters of the MPCClient.StoreShare
type MPCClientMockStoreShareParams struct {
	ctx        context.Context
	userID     string
	shareIndex int
	shareData  []byte
}

// MPCClientMockStoreShareParamPtrs contains pointers to parameters of the MPCClient.StoreShare
type MPCClientMockStoreShareParamPtrs struct {
	ctx        *context.Context
	userID     *string
	shareIndex *int
	shareData  *[]byte
}

// MPCClientMockStoreShareResults contains results of the MPCClient.StoreShare
type MPCClientMockStoreShareResults struct {
	err error
}

// MPCClientMockStoreShareOrigins contains origins of expectations of the MPCClient.StoreShare
type MPCClientMockStoreShareExpectationOrigins struct {
	origin           string
	originCtx        string
	originUserID     string
	originShareIndex string
	originShareData  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStoreShare *mMPCClientMockStoreShare) Optional() *mMPCClientMockStoreShare {
	mmStoreShare.optional = true
	return mmStoreShare
}

// Expect sets up expected params for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) Expect(ctx context.Context, userID string, shareIndex int, shareData []byte) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.paramPtrs != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by ExpectParams functions")
	}

	mmStoreShare.defaultExpectation.params = &MPCClientMockStoreShareParams{ctx, userID, shareIndex, shareData}
	mmStoreShare.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStoreShare.expectations {
		if minimock.Equal(e.params, mmStoreShare.defaultExpectation.params) {
			mmStoreShare.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStoreShare.defaultExpectation.params)
		}
	}

	return mmStoreShare
}

// ExpectCtxParam1 sets up expected param ctx for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectCtxParam1(ctx context.Context) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.ctx = &ctx
	mmStoreShare.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStoreShare
}

// ExpectUserIDParam2 sets up expected param userID for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectUserIDParam2(userID string) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.userID = &userID
	mmStoreShare.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmStoreShare
}

// ExpectShareIndexParam3 sets up expected param shareIndex for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectShareIndexParam3(shareIndex int) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.shareIndex = &shareIndex
	mmStoreShare.defaultExpectation.expectationOrigins.originShareIndex = minimock.CallerInfo(1)

	return mmStoreShare
}

// ExpectShareDataParam4 sets up expected param shareData for MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) ExpectShareDataParam4(shareData []byte) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{}
	}

	if mmStoreShare.defaultExpectation.params != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Expect")
	}

	if mmStoreShare.defaultExpectation.paramPtrs == nil {
		mmStoreShare.defaultExpectation.paramPtrs = &MPCClientMockStoreShareParamPtrs{}
	}
	mmStoreShare.defaultExpectation.paramPtrs.shareData = &shareData
	mmStoreShare.defaultExpectation.expectationOrigins.originShareData = minimock.CallerInfo(1)

	return mmStoreShare
}

// Inspect accepts an inspector function that has same arguments as the MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) Inspect(f func(ctx context.Context, userID string, shareIndex int, shareData []byte)) *mMPCClientMockStoreShare {
	if mmStoreShare.mock.inspectFuncStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("Inspect function is already set for MPCClientMock.StoreShare")
	}

	mmStoreShare.mock.inspectFuncStoreShare = f

	return mmStoreShare
}

// Return sets up results that will be returned by MPCClient.StoreShare
func (mmStoreShare *mMPCClientMockStoreShare) Return(err error) *MPCClientMock {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	if mmStoreShare.defaultExpectation == nil {
		mmStoreShare.defaultExpectation = &MPCClientMockStoreShareExpectation{mock: mmStoreShare.mock}
	}
	mmStoreShare.defaultExpectation.results = &MPCClientMockStoreShareResults{err}
	mmStoreShare.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStoreShare.mock
}

// Set uses given function f to mock the MPCClient.StoreShare method
func (mmStoreShare *mMPCClientMockStoreShare) Set(f func(ctx context.Context, userID string, shareIndex int, shareData []byte) (err error)) *MPCClientMock {
	if mmStoreShare.defaultExpectation != nil {
		mmStoreShare.mock.t.Fatalf("Default expectation is already set for the MPCClient.StoreShare method")
	}

	if len(mmStoreShare.expectations) > 0 {
		mmStoreShare.mock.t.Fatalf("Some expectations are already set for the MPCClient.StoreShare method")
	}

	mmStoreShare.mock.funcStoreShare = f
	mmStoreShare.mock.funcStoreShareOrigin = minimock.CallerInfo(1)
	return mmStoreShare.mock
}

// When sets expectation for the MPCClient.StoreShare which will trigger the result defined by the following
// Then helper
func (mmStoreShare *mMPCClientMockStoreShare) When(ctx context.Context, userID string, shareIndex int, shareData []byte) *MPCClientMockStoreShareExpectation {
	if mmStoreShare.mock.funcStoreShare != nil {
		mmStoreShare.mock.t.Fatalf("MPCClientMock.StoreShare mock is already set by Set")
	}

	expectation := &MPCClientMockStoreShareExpectation{
		mock:               mmStoreShare.mock,
		params:             &MPCClientMockStoreShareParams{ctx, userID, shareIndex, shareData},
		expectationOrigins: MPCClientMockStoreShareExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStoreShare.expectations = append(mmStoreShare.expectations, expectation)
	return expectation
}

// Then sets up MPCClient.StoreShare return parameters for the expectation previously defined by the When method
func (e *MPCClientMockStoreShareExpectation) Then(err error) *MPCClientMock {
	e.results = &MPCClientMockStoreShareResults{err}
	return e.mock
}

// Times sets number of times MPCClient.StoreShare should be invoked
func (mmStoreShare *mMPCClientMockStoreShare) Times(n uint64) *mMPCClientMockStoreShare {
	if n == 0 {
		mmStoreShare.mock.t.Fatalf("Times of MPCClientMock.StoreShare mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStoreShare.expectedInvocations, n)
	mmStoreShare.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStoreShare
}

func (mmStoreShare *mMPCClientMockStoreShare) invocationsDone() bool {
	if len(mmStoreShare.expectations) == 0 && mmStoreShare.defaultExpectation == nil && mmStoreShare.mock.funcStoreShare == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStoreShare.mock.afterStoreShareCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStoreShare.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StoreShare implements mm_twofaService.MPCClient
func (mmStoreShare *MPCClientMock) StoreShare(ctx context.Context, userID string, shareIndex int, shareData []byte) (err error) {
	mm_atomic.AddUint64(&mmStoreShare.beforeStoreShareCounter, 1)
	defer mm_atomic.AddUint64(&mmStoreShare.afterStoreShareCounter, 1)

	mmStoreShare.t.Helper()

	if mmStoreShare.inspectFuncStoreShare != nil {
		mmStoreShare.inspectFuncStoreShare(ctx, userID, shareIndex, shareData)
	}

	mm_params := MPCClientMockStoreShareParams{ctx, userID, shareIndex, shareData}

	// Record call args
	mmStoreShare.StoreShareMock.mutex.Lock()
	mmStoreShare.StoreShareMock.callArgs = append(mmStoreShare.StoreShareMock.callArgs, &mm_params)
	mmStoreShare.StoreShareMock.mutex.Unlock()

	for _, e := range mmStoreShare.StoreShareMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmStoreShare.StoreShareMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStoreShare.StoreShareMock.defaultExpectation.Counter, 1)
		mm_want := mmStoreShare.StoreShareMock.defaultExpectation.params
		mm_want_ptrs := mmStoreShare.StoreShareMock.defaultExpectation.paramPtrs

		mm_got := MPCClientMockStoreShareParams{ctx, userID, shareIndex, shareData}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.shareIndex != nil && !minimock.Equal(*mm_want_ptrs.shareIndex, mm_got.shareIndex) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter shareIndex, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originShareIndex, *mm_want_ptrs.shareIndex, mm_got.shareIndex, minimock.Diff(*mm_want_ptrs.shareIndex, mm_got.shareIndex))
			}

			if mm_want_ptrs.shareData != nil && !minimock.Equal(*mm_want_ptrs.shareData, mm_got.shareData) {
				mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameter shareData, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.originShareData, *mm_want_ptrs.shareData, mm_got.shareData, minimock.Diff(*mm_want_ptrs.shareData, mm_got.shareData))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStoreShare.t.Errorf("MPCClientMock.StoreShare got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStoreShare.StoreShareMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStoreShare.StoreShareMock.defaultExpectation.results
		if mm_results == nil {
			mmStoreShare.t.Fatal("No results are set for the MPCClientMock.StoreShare")
		}
		return (*mm_results).err
	}
	if mmStoreShare.funcStoreShare != nil {
		return mmStoreShare.funcStoreShare(ctx, userID, shareIndex, shareData)
	}
	mmStoreShare.t.Fatalf("Unexpected call to MPCClientMock.StoreShare. %v %v %v %v", ctx, userID, shareIndex, shareData)
	return
}

// StoreShareAfterCounter returns a count of finished MPCClientMock.StoreShare invocations
func (mmStoreShare *MPCClientMock) StoreShareAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStoreShare.afterStoreShareCounter)
}

// StoreShareBeforeCounter returns a count of MPCClientMock.StoreShare invocations
func (mmStoreShare *MPCClientMock) StoreShareBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStoreShare.beforeStoreShareCounter)
}

// Calls returns a list of arguments used in each call to MPCClientMock.StoreShare.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStoreShare *mMPCClientMockStoreShare) Calls() []*MPCClientMockStoreShareParams {
	mmStoreShare.mutex.RLock()

	argCopy := make([]*MPCClientMockStoreShareParams, len(mmStoreShare.callArgs))
	copy(argCopy, mmStoreShare.callArgs)

	mmStoreShare.mutex.RUnlock()

	return argCopy
}

// MinimockStoreShareDone returns true if the count of the StoreShare invocations corresponds
// the number of defined expectations
func (m *MPCClientMock) MinimockStoreShareDone() bool {
	if m.StoreShareMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StoreShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StoreShareMock.invocationsDone()
}

// MinimockStoreShareInspect logs each unmet expectation
func (m *MPCClientMock) MinimockStoreShareInspect() {
	for _, e := range m.StoreShareMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStoreShareCounter := mm_atomic.LoadUint64(&m.afterStoreShareCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StoreShareMock.defaultExpectation != nil && afterStoreShareCounter < 1 {
		if m.StoreShareMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s", m.StoreShareMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s with params: %#v", m.StoreShareMock.defaultExpectation.expectationOrigins.origin, *m.StoreShareMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStoreShare != nil && afterStoreShareCounter < 1 {
		m.t.Errorf("Expected call to MPCClientMock.StoreShare at\n%s", m.funcStoreShareOrigin)
	}

	if !m.StoreShareMock.invocationsDone() && afterStoreShareCounter > 0 {
		m.t.Errorf("Expected %d calls to MPCClientMock.StoreShare at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StoreShareMock.expectedInvocations), m.StoreShareMock.expectedInvocationsOrigin, afterStoreShareCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MPCClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteShareInspect()

			m.MinimockRetrieveShareInspect()

			m.MinimockStoreShareInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MPCClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MPCClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteShareDone() &&
		m.MinimockRetrieveShareDone() &&
		m.MinimockStoreShareDone()
}
