// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/vbncursed/vkr/twofa/internal/services/twofaService.SessionStorage -o session_storage_mock.go -n SessionStorageMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// SessionStorageMock implements mm_twofaService.SessionStorage
type SessionStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteKeys          func(ctx context.Context, keys ...string) (err error)
	funcDeleteKeysOrigin    string
	inspectFuncDeleteKeys   func(ctx context.Context, keys ...string)
	afterDeleteKeysCounter  uint64
	beforeDeleteKeysCounter uint64
	DeleteKeysMock          mSessionStorageMockDeleteKeys

	funcGetRateLimit          func(ctx context.Context, key string) (i1 int64, err error)
	funcGetRateLimitOrigin    string
	inspectFuncGetRateLimit   func(ctx context.Context, key string)
	afterGetRateLimitCounter  uint64
	beforeGetRateLimitCounter uint64
	GetRateLimitMock          mSessionStorageMockGetRateLimit

	funcGetUsedOTPCounter          func(ctx context.Context, userID string) (i1 int64, err error)
	funcGetUsedOTPCounterOrigin    string
	inspectFuncGetUsedOTPCounter   func(ctx context.Context, userID string)
	afterGetUsedOTPCounterCounter  uint64
	beforeGetUsedOTPCounterCounter uint64
	GetUsedOTPCounterMock          mSessionStorageMockGetUsedOTPCounter

	funcIncrementRateLimit          func(ctx context.Context, key string, ttl time.Duration) (i1 int64, err error)
	funcIncrementRateLimitOrigin    string
	inspectFuncIncrementRateLimit   func(ctx context.Context, key string, ttl time.Duration)
	afterIncrementRateLimitCounter  uint64
	beforeIncrementRateLimitCounter uint64
	IncrementRateLimitMock          mSessionStorageMockIncrementRateLimit

	funcSetUsedOTPCounter          func(ctx context.Context, userID string, counter int64, ttl time.Duration) (err error)
	funcSetUsedOTPCounterOrigin    string
	inspectFuncSetUsedOTPCounter   func(ctx context.Context, userID string, counter int64, ttl time.Duration)
	afterSetUsedOTPCounterCounter  uint64
	beforeSetUsedOTPCounterCounter uint64
	SetUsedOTPCounterMock          mSessionStorageMockSetUsedOTPCounter
}

// NewSessionStorageMock returns a mock for mm_twofaService.SessionStorage
func NewSessionStorageMock(t minimock.Tester) *SessionStorageMock {
	m := &SessionStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteKeysMock = mSessionStorageMockDeleteKeys{mock: m}
	m.DeleteKeysMock.callArgs = []*SessionStorageMockDeleteKeysParams{}

	m.GetRateLimitMock = mSessionStorageMockGetRateLimit{mock: m}
	m.GetRateLimitMock.callArgs = []*SessionStorageMockGetRateLimitParams{}

	m.GetUsedOTPCounterMock = mSessionStorageMockGetUsedOTPCounter{mock: m}
	m.GetUsedOTPCounterMock.callArgs = []*SessionStorageMockGetUsedOTPCounterParams{}

	m.IncrementRateLimitMock = mSessionStorageMockIncrementRateLimit{mock: m}
	m.IncrementRateLimitMock.callArgs = []*SessionStorageMockIncrementRateLimitParams{}

	m.SetUsedOTPCounterMock = mSessionStorageMockSetUsedOTPCounter{mock: m}
	m.SetUsedOTPCounterMock.callArgs = []*SessionStorageMockSetUsedOTPCounterParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSessionStorageMockDeleteKeys struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockDeleteKeysExpectation
	expectations       []*SessionStorageMockDeleteKeysExpectation

	callArgs []*SessionStorageMockDeleteKeysParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockDeleteKeysExpectation specifies expectation struct of the SessionStorage.DeleteKeys
type SessionStorageMockDeleteKeysExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockDeleteKeysParams
	paramPtrs          *SessionStorageMockDeleteKeysParamPtrs
	expectationOrigins SessionStorageMockDeleteKeysExpectationOrigins
	results            *SessionStorageMockDeleteKeysResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockDeleteKeysParams contains parameters of the SessionStorage.DeleteKeys
type SessionStorageMockDeleteKeysParams struct {
	ctx  context.Context
	keys []string
}

// SessionStorageMockDeleteKeysParamPtrs contains pointers to parameters of the SessionStorage.DeleteKeys
type SessionStorageMockDeleteKeysParamPtrs struct {
	ctx  *context.Context
	keys *[]string
}

// SessionStorageMockDeleteKeysResults contains results of the SessionStorage.DeleteKeys
type SessionStorageMockDeleteKeysResults struct {
	err error
}

// SessionStorageMockDeleteKeysOrigins contains origins of expectations of the SessionStorage.DeleteKeys
type SessionStorageMockDeleteKeysExpectationOrigins struct {
	origin     string
	originCtx  string
	originKeys string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Optional() *mSessionStorageMockDeleteKeys {
	mmDeleteKeys.optional = true
	return mmDeleteKeys
}

// Expect sets up expected params for SessionStorage.DeleteKeys
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Expect(ctx context.Context, keys ...string) *mSessionStorageMockDeleteKeys {
	if mmDeleteKeys.mock.funcDeleteKeys != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Set")
	}

	if mmDeleteKeys.defaultExpectation == nil {
		mmDeleteKeys.defaultExpectation = &SessionStorageMockDeleteKeysExpectation{}
	}

	if mmDeleteKeys.defaultExpectation.paramPtrs != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by ExpectParams functions")
	}

	mmDeleteKeys.defaultExpectation.params = &SessionStorageMockDeleteKeysParams{ctx, keys}
	mmDeleteKeys.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteKeys.expectations {
		if minimock.Equal(e.params, mmDeleteKeys.defaultExpectation.params) {
			mmDeleteKeys.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteKeys.defaultExpectation.params)
		}
	}

	return mmDeleteKeys
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.DeleteKeys
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockDeleteKeys {
	if mmDeleteKeys.mock.funcDeleteKeys != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Set")
	}

	if mmDeleteKeys.defaultExpectation == nil {
		mmDeleteKeys.defaultExpectation = &SessionStorageMockDeleteKeysExpectation{}
	}

	if mmDeleteKeys.defaultExpectation.params != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Expect")
	}

	if mmDeleteKeys.defaultExpectation.paramPtrs == nil {
		mmDeleteKeys.defaultExpectation.paramPtrs = &SessionStorageMockDeleteKeysParamPtrs{}
	}
	mmDeleteKeys.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteKeys.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteKeys
}

// ExpectKeysParam2 sets up expected param keys for SessionStorage.DeleteKeys
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) ExpectKeysParam2(keys ...string) *mSessionStorageMockDeleteKeys {
	if mmDeleteKeys.mock.funcDeleteKeys != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Set")
	}

	if mmDeleteKeys.defaultExpectation == nil {
		mmDeleteKeys.defaultExpectation = &SessionStorageMockDeleteKeysExpectation{}
	}

	if mmDeleteKeys.defaultExpectation.params != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Expect")
	}

	if mmDeleteKeys.defaultExpectation.paramPtrs == nil {
		mmDeleteKeys.defaultExpectation.paramPtrs = &SessionStorageMockDeleteKeysParamPtrs{}
	}
	mmDeleteKeys.defaultExpectation.paramPtrs.keys = &keys
	mmDeleteKeys.defaultExpectation.expectationOrigins.originKeys = minimock.CallerInfo(1)

	return mmDeleteKeys
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.DeleteKeys
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Inspect(f func(ctx context.Context, keys ...string)) *mSessionStorageMockDeleteKeys {
	if mmDeleteKeys.mock.inspectFuncDeleteKeys != nil {
		mmDeleteKeys.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.DeleteKeys")
	}

	mmDeleteKeys.mock.inspectFuncDeleteKeys = f

	return mmDeleteKeys
}

// Return sets up results that will be returned by SessionStorage.DeleteKeys
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Return(err error) *SessionStorageMock {
	if mmDeleteKeys.mock.funcDeleteKeys != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Set")
	}

	if mmDeleteKeys.defaultExpectation == nil {
		mmDeleteKeys.defaultExpectation = &SessionStorageMockDeleteKeysExpectation{mock: mmDeleteKeys.mock}
	}
	mmDeleteKeys.defaultExpectation.results = &SessionStorageMockDeleteKeysResults{err}
	mmDeleteKeys.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteKeys.mock
}

// Set uses given function f to mock the SessionStorage.DeleteKeys method
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Set(f func(ctx context.Context, keys ...string) (err error)) *SessionStorageMock {
	if mmDeleteKeys.defaultExpectation != nil {
		mmDeleteKeys.mock.t.Fatalf("Default expectation is already set for the SessionStorage.DeleteKeys method")
	}

	if len(mmDeleteKeys.expectations) > 0 {
		mmDeleteKeys.mock.t.Fatalf("Some expectations are already set for the SessionStorage.DeleteKeys method")
	}

	mmDeleteKeys.mock.funcDeleteKeys = f
	mmDeleteKeys.mock.funcDeleteKeysOrigin = minimock.CallerInfo(1)
	return mmDeleteKeys.mock
}

// When sets expectation for the SessionStorage.DeleteKeys which will trigger the result defined by the following
// Then helper
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) When(ctx context.Context, keys ...string) *SessionStorageMockDeleteKeysExpectation {
	if mmDeleteKeys.mock.funcDeleteKeys != nil {
		mmDeleteKeys.mock.t.Fatalf("SessionStorageMock.DeleteKeys mock is already set by Set")
	}

	expectation := &SessionStorageMockDeleteKeysExpectation{
		mock:               mmDeleteKeys.mock,
		params:             &SessionStorageMockDeleteKeysParams{ctx, keys},
		expectationOrigins: SessionStorageMockDeleteKeysExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteKeys.expectations = append(mmDeleteKeys.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.DeleteKeys return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockDeleteKeysExpectation) Then(err error) *SessionStorageMock {
	e.results = &SessionStorageMockDeleteKeysResults{err}
	return e.mock
}

// Times sets number of times SessionStorage.DeleteKeys should be invoked
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Times(n uint64) *mSessionStorageMockDeleteKeys {
	if n == 0 {
		mmDeleteKeys.mock.t.Fatalf("Times of SessionStorageMock.DeleteKeys mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteKeys.expectedInvocations, n)
	mmDeleteKeys.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteKeys
}

func (mmDeleteKeys *mSessionStorageMockDeleteKeys) invocationsDone() bool {
	if len(mmDeleteKeys.expectations) == 0 && mmDeleteKeys.defaultExpectation == nil && mmDeleteKeys.mock.funcDeleteKeys == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteKeys.mock.afterDeleteKeysCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteKeys.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteKeys implements mm_twofaService.SessionStorage
func (mmDeleteKeys *SessionStorageMock) DeleteKeys(ctx context.Context, keys ...string) (err error) {
	mm_atomic.AddUint64(&mmDeleteKeys.beforeDeleteKeysCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteKeys.afterDeleteKeysCounter, 1)

	mmDeleteKeys.t.Helper()

	if mmDeleteKeys.inspectFuncDeleteKeys != nil {
		mmDeleteKeys.inspectFuncDeleteKeys(ctx, keys...)
	}

	mm_params := SessionStorageMockDeleteKeysParams{ctx, keys}

	// Record call args
	mmDeleteKeys.DeleteKeysMock.mutex.Lock()
	mmDeleteKeys.DeleteKeysMock.callArgs = append(mmDeleteKeys.DeleteKeysMock.callArgs, &mm_params)
	mmDeleteKeys.DeleteKeysMock.mutex.Unlock()

	for _, e := range mmDeleteKeys.DeleteKeysMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteKeys.DeleteKeysMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteKeys.DeleteKeysMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteKeys.DeleteKeysMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteKeys.DeleteKeysMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockDeleteKeysParams{ctx, keys}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteKeys.t.Errorf("SessionStorageMock.DeleteKeys got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteKeys.DeleteKeysMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.keys != nil && !minimock.Equal(*mm_want_ptrs.keys, mm_got.keys) {
				mmDeleteKeys.t.Errorf("SessionStorageMock.DeleteKeys got unexpected parameter keys, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteKeys.DeleteKeysMock.defaultExpectation.expectationOrigins.originKeys, *mm_want_ptrs.keys, mm_got.keys, minimock.Diff(*mm_want_ptrs.keys, mm_got.keys))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteKeys.t.Errorf("SessionStorageMock.DeleteKeys got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteKeys.DeleteKeysMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteKeys.DeleteKeysMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteKeys.t.Fatal("No results are set for the SessionStorageMock.DeleteKeys")
		}
		return (*mm_results).err
	}
	if mmDeleteKeys.funcDeleteKeys != nil {
		return mmDeleteKeys.funcDeleteKeys(ctx, keys...)
	}
	mmDeleteKeys.t.Fatalf("Unexpected call to SessionStorageMock.DeleteKeys. %v %v", ctx, keys)
	return
}

// DeleteKeysAfterCounter returns a count of finished SessionStorageMock.DeleteKeys invocations
func (mmDeleteKeys *SessionStorageMock) DeleteKeysAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteKeys.afterDeleteKeysCounter)
}

// DeleteKeysBeforeCounter returns a count of SessionStorageMock.DeleteKeys invocations
func (mmDeleteKeys *SessionStorageMock) DeleteKeysBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteKeys.beforeDeleteKeysCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.DeleteKeys.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteKeys *mSessionStorageMockDeleteKeys) Calls() []*SessionStorageMockDeleteKeysParams {
	mmDeleteKeys.mutex.RLock()

	argCopy := make([]*SessionStorageMockDeleteKeysParams, len(mmDeleteKeys.callArgs))
	copy(argCopy, mmDeleteKeys.callArgs)

	mmDeleteKeys.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteKeysDone returns true if the count of the DeleteKeys invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockDeleteKeysDone() bool {
	if m.DeleteKeysMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteKeysMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteKeysMock.invocationsDone()
}

// MinimockDeleteKeysInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockDeleteKeysInspect() {
	for _, e := range m.DeleteKeysMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteKeys at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteKeysCounter := mm_atomic.LoadUint64(&m.afterDeleteKeysCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteKeysMock.defaultExpectation != nil && afterDeleteKeysCounter < 1 {
		if m.DeleteKeysMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteKeys at\n%s", m.DeleteKeysMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.DeleteKeys at\n%s with params: %#v", m.DeleteKeysMock.defaultExpectation.expectationOrigins.origin, *m.DeleteKeysMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteKeys != nil && afterDeleteKeysCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.DeleteKeys at\n%s", m.funcDeleteKeysOrigin)
	}

	if !m.DeleteKeysMock.invocationsDone() && afterDeleteKeysCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.DeleteKeys at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteKeysMock.expectedInvocations), m.DeleteKeysMock.expectedInvocationsOrigin, afterDeleteKeysCounter)
	}
}

type mSessionStorageMockGetRateLimit struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockGetRateLimitExpectation
	expectations       []*SessionStorageMockGetRateLimitExpectation

	callArgs []*SessionStorageMockGetRateLimitParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockGetRateLimitExpectation specifies expectation struct of the SessionStorage.GetRateLimit
type SessionStorageMockGetRateLimitExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockGetRateLimitParams
	paramPtrs          *SessionStorageMockGetRateLimitParamPtrs
	expectationOrigins SessionStorageMockGetRateLimitExpectationOrigins
	results            *SessionStorageMockGetRateLimitResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockGetRateLimitParams contains parameters of the SessionStorage.GetRateLimit
type SessionStorageMockGetRateLimitParams struct {
	ctx context.Context
	key string
}

// SessionStorageMockGetRateLimitParamPtrs contains pointers to parameters of the SessionStorage.GetRateLimit
type SessionStorageMockGetRateLimitParamPtrs struct {
	ctx *context.Context
	key *string
}

// SessionStorageMockGetRateLimitResults contains results of the SessionStorage.GetRateLimit
type SessionStorageMockGetRateLimitResults struct {
	i1  int64
	err error
}

// SessionStorageMockGetRateLimitOrigins contains origins of expectations of the SessionStorage.GetRateLimit
type SessionStorageMockGetRateLimitExpectationOrigins struct {
	origin    string
	originCtx string
	originKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Optional() *mSessionStorageMockGetRateLimit {
	mmGetRateLimit.optional = true
	return mmGetRateLimit
}

// Expect sets up expected params for SessionStorage.GetRateLimit
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Expect(ctx context.Context, key string) *mSessionStorageMockGetRateLimit {
	if mmGetRateLimit.mock.funcGetRateLimit != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Set")
	}

	if mmGetRateLimit.defaultExpectation == nil {
		mmGetRateLimit.defaultExpectation = &SessionStorageMockGetRateLimitExpectation{}
	}

	if mmGetRateLimit.defaultExpectation.paramPtrs != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by ExpectParams functions")
	}

	mmGetRateLimit.defaultExpectation.params = &SessionStorageMockGetRateLimitParams{ctx, key}
	mmGetRateLimit.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetRateLimit.expectations {
		if minimock.Equal(e.params, mmGetRateLimit.defaultExpectation.params) {
			mmGetRateLimit.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRateLimit.defaultExpectation.params)
		}
	}

	return mmGetRateLimit
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.GetRateLimit
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockGetRateLimit {
	if mmGetRateLimit.mock.funcGetRateLimit != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Set")
	}

	if mmGetRateLimit.defaultExpectation == nil {
		mmGetRateLimit.defaultExpectation = &SessionStorageMockGetRateLimitExpectation{}
	}

	if mmGetRateLimit.defaultExpectation.params != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Expect")
	}

	if mmGetRateLimit.defaultExpectation.paramPtrs == nil {
		mmGetRateLimit.defaultExpectation.paramPtrs = &SessionStorageMockGetRateLimitParamPtrs{}
	}
	mmGetRateLimit.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetRateLimit.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetRateLimit
}

// ExpectKeyParam2 sets up expected param key for SessionStorage.GetRateLimit
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) ExpectKeyParam2(key string) *mSessionStorageMockGetRateLimit {
	if mmGetRateLimit.mock.funcGetRateLimit != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Set")
	}

	if mmGetRateLimit.defaultExpectation == nil {
		mmGetRateLimit.defaultExpectation = &SessionStorageMockGetRateLimitExpectation{}
	}

	if mmGetRateLimit.defaultExpectation.params != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Expect")
	}

	if mmGetRateLimit.defaultExpectation.paramPtrs == nil {
		mmGetRateLimit.defaultExpectation.paramPtrs = &SessionStorageMockGetRateLimitParamPtrs{}
	}
	mmGetRateLimit.defaultExpectation.paramPtrs.key = &key
	mmGetRateLimit.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmGetRateLimit
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.GetRateLimit
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Inspect(f func(ctx context.Context, key string)) *mSessionStorageMockGetRateLimit {
	if mmGetRateLimit.mock.inspectFuncGetRateLimit != nil {
		mmGetRateLimit.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.GetRateLimit")
	}

	mmGetRateLimit.mock.inspectFuncGetRateLimit = f

	return mmGetRateLimit
}

// Return sets up results that will be returned by SessionStorage.GetRateLimit
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Return(i1 int64, err error) *SessionStorageMock {
	if mmGetRateLimit.mock.funcGetRateLimit != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Set")
	}

	if mmGetRateLimit.defaultExpectation == nil {
		mmGetRateLimit.defaultExpectation = &SessionStorageMockGetRateLimitExpectation{mock: mmGetRateLimit.mock}
	}
	mmGetRateLimit.defaultExpectation.results = &SessionStorageMockGetRateLimitResults{i1, err}
	mmGetRateLimit.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetRateLimit.mock
}

// Set uses given function f to mock the SessionStorage.GetRateLimit method
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Set(f func(ctx context.Context, key string) (i1 int64, err error)) *SessionStorageMock {
	if mmGetRateLimit.defaultExpectation != nil {
		mmGetRateLimit.mock.t.Fatalf("Default expectation is already set for the SessionStorage.GetRateLimit method")
	}

	if len(mmGetRateLimit.expectations) > 0 {
		mmGetRateLimit.mock.t.Fatalf("Some expectations are already set for the SessionStorage.GetRateLimit method")
	}

	mmGetRateLimit.mock.funcGetRateLimit = f
	mmGetRateLimit.mock.funcGetRateLimitOrigin = minimock.CallerInfo(1)
	return mmGetRateLimit.mock
}

// When sets expectation for the SessionStorage.GetRateLimit which will trigger the result defined by the following
// Then helper
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) When(ctx context.Context, key string) *SessionStorageMockGetRateLimitExpectation {
	if mmGetRateLimit.mock.funcGetRateLimit != nil {
		mmGetRateLimit.mock.t.Fatalf("SessionStorageMock.GetRateLimit mock is already set by Set")
	}

	expectation := &SessionStorageMockGetRateLimitExpectation{
		mock:               mmGetRateLimit.mock,
		params:             &SessionStorageMockGetRateLimitParams{ctx, key},
		expectationOrigins: SessionStorageMockGetRateLimitExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetRateLimit.expectations = append(mmGetRateLimit.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.GetRateLimit return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockGetRateLimitExpectation) Then(i1 int64, err error) *SessionStorageMock {
	e.results = &SessionStorageMockGetRateLimitResults{i1, err}
	return e.mock
}

// Times sets number of times SessionStorage.GetRateLimit should be invoked
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Times(n uint64) *mSessionStorageMockGetRateLimit {
	if n == 0 {
		mmGetRateLimit.mock.t.Fatalf("Times of SessionStorageMock.GetRateLimit mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetRateLimit.expectedInvocations, n)
	mmGetRateLimit.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetRateLimit
}

func (mmGetRateLimit *mSessionStorageMockGetRateLimit) invocationsDone() bool {
	if len(mmGetRateLimit.expectations) == 0 && mmGetRateLimit.defaultExpectation == nil && mmGetRateLimit.mock.funcGetRateLimit == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetRateLimit.mock.afterGetRateLimitCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetRateLimit.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetRateLimit implements mm_twofaService.SessionStorage
func (mmGetRateLimit *SessionStorageMock) GetRateLimit(ctx context.Context, key string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmGetRateLimit.beforeGetRateLimitCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRateLimit.afterGetRateLimitCounter, 1)

	mmGetRateLimit.t.Helper()

	if mmGetRateLimit.inspectFuncGetRateLimit != nil {
		mmGetRateLimit.inspectFuncGetRateLimit(ctx, key)
	}

	mm_params := SessionStorageMockGetRateLimitParams{ctx, key}

	// Record call args
	mmGetRateLimit.GetRateLimitMock.mutex.Lock()
	mmGetRateLimit.GetRateLimitMock.callArgs = append(mmGetRateLimit.GetRateLimitMock.callArgs, &mm_params)
	mmGetRateLimit.GetRateLimitMock.mutex.Unlock()

	for _, e := range mmGetRateLimit.GetRateLimitMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmGetRateLimit.GetRateLimitMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRateLimit.GetRateLimitMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRateLimit.GetRateLimitMock.defaultExpectation.params
		mm_want_ptrs := mmGetRateLimit.GetRateLimitMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockGetRateLimitParams{ctx, key}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetRateLimit.t.Errorf("SessionStorageMock.GetRateLimit got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRateLimit.GetRateLimitMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmGetRateLimit.t.Errorf("SessionStorageMock.GetRateLimit got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRateLimit.GetRateLimitMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRateLimit.t.Errorf("SessionStorageMock.GetRateLimit got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetRateLimit.GetRateLimitMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRateLimit.GetRateLimitMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRateLimit.t.Fatal("No results are set for the SessionStorageMock.GetRateLimit")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmGetRateLimit.funcGetRateLimit != nil {
		return mmGetRateLimit.funcGetRateLimit(ctx, key)
	}
	mmGetRateLimit.t.Fatalf("Unexpected call to SessionStorageMock.GetRateLimit. %v %v", ctx, key)
	return
}

// GetRateLimitAfterCounter returns a count of finished SessionStorageMock.GetRateLimit invocations
func (mmGetRateLimit *SessionStorageMock) GetRateLimitAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRateLimit.afterGetRateLimitCounter)
}

// GetRateLimitBeforeCounter returns a count of SessionStorageMock.GetRateLimit invocations
func (mmGetRateLimit *SessionStorageMock) GetRateLimitBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRateLimit.beforeGetRateLimitCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.GetRateLimit.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRateLimit *mSessionStorageMockGetRateLimit) Calls() []*SessionStorageMockGetRateLimitParams {
	mmGetRateLimit.mutex.RLock()

	argCopy := make([]*SessionStorageMockGetRateLimitParams, len(mmGetRateLimit.callArgs))
	copy(argCopy, mmGetRateLimit.callArgs)

	mmGetRateLimit.mutex.RUnlock()

	return argCopy
}

// MinimockGetRateLimitDone returns true if the count of the GetRateLimit invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockGetRateLimitDone() bool {
	if m.GetRateLimitMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetRateLimitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetRateLimitMock.invocationsDone()
}

// MinimockGetRateLimitInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockGetRateLimitInspect() {
	for _, e := range m.GetRateLimitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.GetRateLimit at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetRateLimitCounter := mm_atomic.LoadUint64(&m.afterGetRateLimitCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetRateLimitMock.defaultExpectation != nil && afterGetRateLimitCounter < 1 {
		if m.GetRateLimitMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.GetRateLimit at\n%s", m.GetRateLimitMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.GetRateLimit at\n%s with params: %#v", m.GetRateLimitMock.defaultExpectation.expectationOrigins.origin, *m.GetRateLimitMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRateLimit != nil && afterGetRateLimitCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.GetRateLimit at\n%s", m.funcGetRateLimitOrigin)
	}

	if !m.GetRateLimitMock.invocationsDone() && afterGetRateLimitCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.GetRateLimit at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetRateLimitMock.expectedInvocations), m.GetRateLimitMock.expectedInvocationsOrigin, afterGetRateLimitCounter)
	}
}

type mSessionStorageMockGetUsedOTPCounter struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockGetUsedOTPCounterExpectation
	expectations       []*SessionStorageMockGetUsedOTPCounterExpectation

	callArgs []*SessionStorageMockGetUsedOTPCounterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockGetUsedOTPCounterExpectation specifies expectation struct of the SessionStorage.GetUsedOTPCounter
type SessionStorageMockGetUsedOTPCounterExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockGetUsedOTPCounterParams
	paramPtrs          *SessionStorageMockGetUsedOTPCounterParamPtrs
	expectationOrigins SessionStorageMockGetUsedOTPCounterExpectationOrigins
	results            *SessionStorageMockGetUsedOTPCounterResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockGetUsedOTPCounterParams contains parameters of the SessionStorage.GetUsedOTPCounter
type SessionStorageMockGetUsedOTPCounterParams struct {
	ctx    context.Context
	userID string
}

// SessionStorageMockGetUsedOTPCounterParamPtrs contains pointers to parameters of the SessionStorage.GetUsedOTPCounter
type SessionStorageMockGetUsedOTPCounterParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// SessionStorageMockGetUsedOTPCounterResults contains results of the SessionStorage.GetUsedOTPCounter
type SessionStorageMockGetUsedOTPCounterResults struct {
	i1  int64
	err error
}

// SessionStorageMockGetUsedOTPCounterOrigins contains origins of expectations of the SessionStorage.GetUsedOTPCounter
type SessionStorageMockGetUsedOTPCounterExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Optional() *mSessionStorageMockGetUsedOTPCounter {
	mmGetUsedOTPCounter.optional = true
	return mmGetUsedOTPCounter
}

// Expect sets up expected params for SessionStorage.GetUsedOTPCounter
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Expect(ctx context.Context, userID string) *mSessionStorageMockGetUsedOTPCounter {
	if mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Set")
	}

	if mmGetUsedOTPCounter.defaultExpectation == nil {
		mmGetUsedOTPCounter.defaultExpectation = &SessionStorageMockGetUsedOTPCounterExpectation{}
	}

	if mmGetUsedOTPCounter.defaultExpectation.paramPtrs != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by ExpectParams functions")
	}

	mmGetUsedOTPCounter.defaultExpectation.params = &SessionStorageMockGetUsedOTPCounterParams{ctx, userID}
	mmGetUsedOTPCounter.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUsedOTPCounter.expectations {
		if minimock.Equal(e.params, mmGetUsedOTPCounter.defaultExpectation.params) {
			mmGetUsedOTPCounter.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUsedOTPCounter.defaultExpectation.params)
		}
	}

	return mmGetUsedOTPCounter
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.GetUsedOTPCounter
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockGetUsedOTPCounter {
	if mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Set")
	}

	if mmGetUsedOTPCounter.defaultExpectation == nil {
		mmGetUsedOTPCounter.defaultExpectation = &SessionStorageMockGetUsedOTPCounterExpectation{}
	}

	if mmGetUsedOTPCounter.defaultExpectation.params != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Expect")
	}

	if mmGetUsedOTPCounter.defaultExpectation.paramPtrs == nil {
		mmGetUsedOTPCounter.defaultExpectation.paramPtrs = &SessionStorageMockGetUsedOTPCounterParamPtrs{}
	}
	mmGetUsedOTPCounter.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUsedOTPCounter.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUsedOTPCounter
}

// ExpectUserIDParam2 sets up expected param userID for SessionStorage.GetUsedOTPCounter
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) ExpectUserIDParam2(userID string) *mSessionStorageMockGetUsedOTPCounter {
	if mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Set")
	}

	if mmGetUsedOTPCounter.defaultExpectation == nil {
		mmGetUsedOTPCounter.defaultExpectation = &SessionStorageMockGetUsedOTPCounterExpectation{}
	}

	if mmGetUsedOTPCounter.defaultExpectation.params != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Expect")
	}

	if mmGetUsedOTPCounter.defaultExpectation.paramPtrs == nil {
		mmGetUsedOTPCounter.defaultExpectation.paramPtrs = &SessionStorageMockGetUsedOTPCounterParamPtrs{}
	}
	mmGetUsedOTPCounter.defaultExpectation.paramPtrs.userID = &userID
	mmGetUsedOTPCounter.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetUsedOTPCounter
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.GetUsedOTPCounter
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Inspect(f func(ctx context.Context, userID string)) *mSessionStorageMockGetUsedOTPCounter {
	if mmGetUsedOTPCounter.mock.inspectFuncGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.GetUsedOTPCounter")
	}

	mmGetUsedOTPCounter.mock.inspectFuncGetUsedOTPCounter = f

	return mmGetUsedOTPCounter
}

// Return sets up results that will be returned by SessionStorage.GetUsedOTPCounter
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Return(i1 int64, err error) *SessionStorageMock {
	if mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Set")
	}

	if mmGetUsedOTPCounter.defaultExpectation == nil {
		mmGetUsedOTPCounter.defaultExpectation = &SessionStorageMockGetUsedOTPCounterExpectation{mock: mmGetUsedOTPCounter.mock}
	}
	mmGetUsedOTPCounter.defaultExpectation.results = &SessionStorageMockGetUsedOTPCounterResults{i1, err}
	mmGetUsedOTPCounter.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUsedOTPCounter.mock
}

// Set uses given function f to mock the SessionStorage.GetUsedOTPCounter method
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Set(f func(ctx context.Context, userID string) (i1 int64, err error)) *SessionStorageMock {
	if mmGetUsedOTPCounter.defaultExpectation != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("Default expectation is already set for the SessionStorage.GetUsedOTPCounter method")
	}

	if len(mmGetUsedOTPCounter.expectations) > 0 {
		mmGetUsedOTPCounter.mock.t.Fatalf("Some expectations are already set for the SessionStorage.GetUsedOTPCounter method")
	}

	mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter = f
	mmGetUsedOTPCounter.mock.funcGetUsedOTPCounterOrigin = minimock.CallerInfo(1)
	return mmGetUsedOTPCounter.mock
}

// When sets expectation for the SessionStorage.GetUsedOTPCounter which will trigger the result defined by the following
// Then helper
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) When(ctx context.Context, userID string) *SessionStorageMockGetUsedOTPCounterExpectation {
	if mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.GetUsedOTPCounter mock is already set by Set")
	}

	expectation := &SessionStorageMockGetUsedOTPCounterExpectation{
		mock:               mmGetUsedOTPCounter.mock,
		params:             &SessionStorageMockGetUsedOTPCounterParams{ctx, userID},
		expectationOrigins: SessionStorageMockGetUsedOTPCounterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUsedOTPCounter.expectations = append(mmGetUsedOTPCounter.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.GetUsedOTPCounter return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockGetUsedOTPCounterExpectation) Then(i1 int64, err error) *SessionStorageMock {
	e.results = &SessionStorageMockGetUsedOTPCounterResults{i1, err}
	return e.mock
}

// Times sets number of times SessionStorage.GetUsedOTPCounter should be invoked
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Times(n uint64) *mSessionStorageMockGetUsedOTPCounter {
	if n == 0 {
		mmGetUsedOTPCounter.mock.t.Fatalf("Times of SessionStorageMock.GetUsedOTPCounter mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUsedOTPCounter.expectedInvocations, n)
	mmGetUsedOTPCounter.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUsedOTPCounter
}

func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) invocationsDone() bool {
	if len(mmGetUsedOTPCounter.expectations) == 0 && mmGetUsedOTPCounter.defaultExpectation == nil && mmGetUsedOTPCounter.mock.funcGetUsedOTPCounter == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUsedOTPCounter.mock.afterGetUsedOTPCounterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUsedOTPCounter.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUsedOTPCounter implements mm_twofaService.SessionStorage
func (mmGetUsedOTPCounter *SessionStorageMock) GetUsedOTPCounter(ctx context.Context, userID string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmGetUsedOTPCounter.beforeGetUsedOTPCounterCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUsedOTPCounter.afterGetUsedOTPCounterCounter, 1)

	mmGetUsedOTPCounter.t.Helper()

	if mmGetUsedOTPCounter.inspectFuncGetUsedOTPCounter != nil {
		mmGetUsedOTPCounter.inspectFuncGetUsedOTPCounter(ctx, userID)
	}

	mm_params := SessionStorageMockGetUsedOTPCounterParams{ctx, userID}

	// Record call args
	mmGetUsedOTPCounter.GetUsedOTPCounterMock.mutex.Lock()
	mmGetUsedOTPCounter.GetUsedOTPCounterMock.callArgs = append(mmGetUsedOTPCounter.GetUsedOTPCounterMock.callArgs, &mm_params)
	mmGetUsedOTPCounter.GetUsedOTPCounterMock.mutex.Unlock()

	for _, e := range mmGetUsedOTPCounter.GetUsedOTPCounterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.params
		mm_want_ptrs := mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockGetUsedOTPCounterParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUsedOTPCounter.t.Errorf("SessionStorageMock.GetUsedOTPCounter got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetUsedOTPCounter.t.Errorf("SessionStorageMock.GetUsedOTPCounter got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUsedOTPCounter.t.Errorf("SessionStorageMock.GetUsedOTPCounter got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUsedOTPCounter.GetUsedOTPCounterMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUsedOTPCounter.t.Fatal("No results are set for the SessionStorageMock.GetUsedOTPCounter")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmGetUsedOTPCounter.funcGetUsedOTPCounter != nil {
		return mmGetUsedOTPCounter.funcGetUsedOTPCounter(ctx, userID)
	}
	mmGetUsedOTPCounter.t.Fatalf("Unexpected call to SessionStorageMock.GetUsedOTPCounter. %v %v", ctx, userID)
	return
}

// GetUsedOTPCounterAfterCounter returns a count of finished SessionStorageMock.GetUsedOTPCounter invocations
func (mmGetUsedOTPCounter *SessionStorageMock) GetUsedOTPCounterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUsedOTPCounter.afterGetUsedOTPCounterCounter)
}

// GetUsedOTPCounterBeforeCounter returns a count of SessionStorageMock.GetUsedOTPCounter invocations
func (mmGetUsedOTPCounter *SessionStorageMock) GetUsedOTPCounterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUsedOTPCounter.beforeGetUsedOTPCounterCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.GetUsedOTPCounter.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUsedOTPCounter *mSessionStorageMockGetUsedOTPCounter) Calls() []*SessionStorageMockGetUsedOTPCounterParams {
	mmGetUsedOTPCounter.mutex.RLock()

	argCopy := make([]*SessionStorageMockGetUsedOTPCounterParams, len(mmGetUsedOTPCounter.callArgs))
	copy(argCopy, mmGetUsedOTPCounter.callArgs)

	mmGetUsedOTPCounter.mutex.RUnlock()

	return argCopy
}

// MinimockGetUsedOTPCounterDone returns true if the count of the GetUsedOTPCounter invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockGetUsedOTPCounterDone() bool {
	if m.GetUsedOTPCounterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUsedOTPCounterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUsedOTPCounterMock.invocationsDone()
}

// MinimockGetUsedOTPCounterInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockGetUsedOTPCounterInspect() {
	for _, e := range m.GetUsedOTPCounterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.GetUsedOTPCounter at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUsedOTPCounterCounter := mm_atomic.LoadUint64(&m.afterGetUsedOTPCounterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUsedOTPCounterMock.defaultExpectation != nil && afterGetUsedOTPCounterCounter < 1 {
		if m.GetUsedOTPCounterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.GetUsedOTPCounter at\n%s", m.GetUsedOTPCounterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.GetUsedOTPCounter at\n%s with params: %#v", m.GetUsedOTPCounterMock.defaultExpectation.expectationOrigins.origin, *m.GetUsedOTPCounterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUsedOTPCounter != nil && afterGetUsedOTPCounterCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.GetUsedOTPCounter at\n%s", m.funcGetUsedOTPCounterOrigin)
	}

	if !m.GetUsedOTPCounterMock.invocationsDone() && afterGetUsedOTPCounterCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.GetUsedOTPCounter at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUsedOTPCounterMock.expectedInvocations), m.GetUsedOTPCounterMock.expectedInvocationsOrigin, afterGetUsedOTPCounterCounter)
	}
}

type mSessionStorageMockIncrementRateLimit struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockIncrementRateLimitExpectation
	expectations       []*SessionStorageMockIncrementRateLimitExpectation

	callArgs []*SessionStorageMockIncrementRateLimitParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockIncrementRateLimitExpectation specifies expectation struct of the SessionStorage.IncrementRateLimit
type SessionStorageMockIncrementRateLimitExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockIncrementRateLimitParams
	paramPtrs          *SessionStorageMockIncrementRateLimitParamPtrs
	expectationOrigins SessionStorageMockIncrementRateLimitExpectationOrigins
	results            *SessionStorageMockIncrementRateLimitResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockIncrementRateLimitParams contains parameters of the SessionStorage.IncrementRateLimit
type SessionStorageMockIncrementRateLimitParams struct {
	ctx context.Context
	key string
	ttl time.Duration
}

// SessionStorageMockIncrementRateLimitParamPtrs contains pointers to parameters of the SessionStorage.IncrementRateLimit
type SessionStorageMockIncrementRateLimitParamPtrs struct {
	ctx *context.Context
	key *string
	ttl *time.Duration
}

// SessionStorageMockIncrementRateLimitResults contains results of the SessionStorage.IncrementRateLimit
type SessionStorageMockIncrementRateLimitResults struct {
	i1  int64
	err error
}

// SessionStorageMockIncrementRateLimitOrigins contains origins of expectations of the SessionStorage.IncrementRateLimit
type SessionStorageMockIncrementRateLimitExpectationOrigins struct {
	origin    string
	originCtx string
	originKey string
	originTtl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Optional() *mSessionStorageMockIncrementRateLimit {
	mmIncrementRateLimit.optional = true
	return mmIncrementRateLimit
}

// Expect sets up expected params for SessionStorage.IncrementRateLimit
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Expect(ctx context.Context, key string, ttl time.Duration) *mSessionStorageMockIncrementRateLimit {
	if mmIncrementRateLimit.mock.funcIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Set")
	}

	if mmIncrementRateLimit.defaultExpectation == nil {
		mmIncrementRateLimit.defaultExpectation = &SessionStorageMockIncrementRateLimitExpectation{}
	}

	if mmIncrementRateLimit.defaultExpectation.paramPtrs != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by ExpectParams functions")
	}

	mmIncrementRateLimit.defaultExpectation.params = &SessionStorageMockIncrementRateLimitParams{ctx, key, ttl}
	mmIncrementRateLimit.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmIncrementRateLimit.expectations {
		if minimock.Equal(e.params, mmIncrementRateLimit.defaultExpectation.params) {
			mmIncrementRateLimit.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIncrementRateLimit.defaultExpectation.params)
		}
	}

	return mmIncrementRateLimit
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.IncrementRateLimit
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockIncrementRateLimit {
	if mmIncrementRateLimit.mock.funcIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Set")
	}

	if mmIncrementRateLimit.defaultExpectation == nil {
		mmIncrementRateLimit.defaultExpectation = &SessionStorageMockIncrementRateLimitExpectation{}
	}

	if mmIncrementRateLimit.defaultExpectation.params != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Expect")
	}

	if mmIncrementRateLimit.defaultExpectation.paramPtrs == nil {
		mmIncrementRateLimit.defaultExpectation.paramPtrs = &SessionStorageMockIncrementRateLimitParamPtrs{}
	}
	mmIncrementRateLimit.defaultExpectation.paramPtrs.ctx = &ctx
	mmIncrementRateLimit.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmIncrementRateLimit
}

// ExpectKeyParam2 sets up expected param key for SessionStorage.IncrementRateLimit
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) ExpectKeyParam2(key string) *mSessionStorageMockIncrementRateLimit {
	if mmIncrementRateLimit.mock.funcIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Set")
	}

	if mmIncrementRateLimit.defaultExpectation == nil {
		mmIncrementRateLimit.defaultExpectation = &SessionStorageMockIncrementRateLimitExpectation{}
	}

	if mmIncrementRateLimit.defaultExpectation.params != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Expect")
	}

	if mmIncrementRateLimit.defaultExpectation.paramPtrs == nil {
		mmIncrementRateLimit.defaultExpectation.paramPtrs = &SessionStorageMockIncrementRateLimitParamPtrs{}
	}
	mmIncrementRateLimit.defaultExpectation.paramPtrs.key = &key
	mmIncrementRateLimit.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmIncrementRateLimit
}

// ExpectTtlParam3 sets up expected param ttl for SessionStorage.IncrementRateLimit
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) ExpectTtlParam3(ttl time.Duration) *mSessionStorageMockIncrementRateLimit {
	if mmIncrementRateLimit.mock.funcIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Set")
	}

	if mmIncrementRateLimit.defaultExpectation == nil {
		mmIncrementRateLimit.defaultExpectation = &SessionStorageMockIncrementRateLimitExpectation{}
	}

	if mmIncrementRateLimit.defaultExpectation.params != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Expect")
	}

	if mmIncrementRateLimit.defaultExpectation.paramPtrs == nil {
		mmIncrementRateLimit.defaultExpectation.paramPtrs = &SessionStorageMockIncrementRateLimitParamPtrs{}
	}
	mmIncrementRateLimit.defaultExpectation.paramPtrs.ttl = &ttl
	mmIncrementRateLimit.defaultExpectation.expectationOrigins.originTtl = minimock.CallerInfo(1)

	return mmIncrementRateLimit
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.IncrementRateLimit
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Inspect(f func(ctx context.Context, key string, ttl time.Duration)) *mSessionStorageMockIncrementRateLimit {
	if mmIncrementRateLimit.mock.inspectFuncIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.IncrementRateLimit")
	}

	mmIncrementRateLimit.mock.inspectFuncIncrementRateLimit = f

	return mmIncrementRateLimit
}

// Return sets up results that will be returned by SessionStorage.IncrementRateLimit
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Return(i1 int64, err error) *SessionStorageMock {
	if mmIncrementRateLimit.mock.funcIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Set")
	}

	if mmIncrementRateLimit.defaultExpectation == nil {
		mmIncrementRateLimit.defaultExpectation = &SessionStorageMockIncrementRateLimitExpectation{mock: mmIncrementRateLimit.mock}
	}
	mmIncrementRateLimit.defaultExpectation.results = &SessionStorageMockIncrementRateLimitResults{i1, err}
	mmIncrementRateLimit.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIncrementRateLimit.mock
}

// Set uses given function f to mock the SessionStorage.IncrementRateLimit method
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Set(f func(ctx context.Context, key string, ttl time.Duration) (i1 int64, err error)) *SessionStorageMock {
	if mmIncrementRateLimit.defaultExpectation != nil {
		mmIncrementRateLimit.mock.t.Fatalf("Default expectation is already set for the SessionStorage.IncrementRateLimit method")
	}

	if len(mmIncrementRateLimit.expectations) > 0 {
		mmIncrementRateLimit.mock.t.Fatalf("Some expectations are already set for the SessionStorage.IncrementRateLimit method")
	}

	mmIncrementRateLimit.mock.funcIncrementRateLimit = f
	mmIncrementRateLimit.mock.funcIncrementRateLimitOrigin = minimock.CallerInfo(1)
	return mmIncrementRateLimit.mock
}

// When sets expectation for the SessionStorage.IncrementRateLimit which will trigger the result defined by the following
// Then helper
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) When(ctx context.Context, key string, ttl time.Duration) *SessionStorageMockIncrementRateLimitExpectation {
	if mmIncrementRateLimit.mock.funcIncrementRateLimit != nil {
		mmIncrementRateLimit.mock.t.Fatalf("SessionStorageMock.IncrementRateLimit mock is already set by Set")
	}

	expectation := &SessionStorageMockIncrementRateLimitExpectation{
		mock:               mmIncrementRateLimit.mock,
		params:             &SessionStorageMockIncrementRateLimitParams{ctx, key, ttl},
		expectationOrigins: SessionStorageMockIncrementRateLimitExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmIncrementRateLimit.expectations = append(mmIncrementRateLimit.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.IncrementRateLimit return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockIncrementRateLimitExpectation) Then(i1 int64, err error) *SessionStorageMock {
	e.results = &SessionStorageMockIncrementRateLimitResults{i1, err}
	return e.mock
}

// Times sets number of times SessionStorage.IncrementRateLimit should be invoked
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Times(n uint64) *mSessionStorageMockIncrementRateLimit {
	if n == 0 {
		mmIncrementRateLimit.mock.t.Fatalf("Times of SessionStorageMock.IncrementRateLimit mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIncrementRateLimit.expectedInvocations, n)
	mmIncrementRateLimit.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIncrementRateLimit
}

func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) invocationsDone() bool {
	if len(mmIncrementRateLimit.expectations) == 0 && mmIncrementRateLimit.defaultExpectation == nil && mmIncrementRateLimit.mock.funcIncrementRateLimit == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIncrementRateLimit.mock.afterIncrementRateLimitCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIncrementRateLimit.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// IncrementRateLimit implements mm_twofaService.SessionStorage
func (mmIncrementRateLimit *SessionStorageMock) IncrementRateLimit(ctx context.Context, key string, ttl time.Duration) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmIncrementRateLimit.beforeIncrementRateLimitCounter, 1)
	defer mm_atomic.AddUint64(&mmIncrementRateLimit.afterIncrementRateLimitCounter, 1)

	mmIncrementRateLimit.t.Helper()

	if mmIncrementRateLimit.inspectFuncIncrementRateLimit != nil {
		mmIncrementRateLimit.inspectFuncIncrementRateLimit(ctx, key, ttl)
	}

	mm_params := SessionStorageMockIncrementRateLimitParams{ctx, key, ttl}

	// Record call args
	mmIncrementRateLimit.IncrementRateLimitMock.mutex.Lock()
	mmIncrementRateLimit.IncrementRateLimitMock.callArgs = append(mmIncrementRateLimit.IncrementRateLimitMock.callArgs, &mm_params)
	mmIncrementRateLimit.IncrementRateLimitMock.mutex.Unlock()

	for _, e := range mmIncrementRateLimit.IncrementRateLimitMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.Counter, 1)
		mm_want := mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.params
		mm_want_ptrs := mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockIncrementRateLimitParams{ctx, key, ttl}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmIncrementRateLimit.t.Errorf("SessionStorageMock.IncrementRateLimit got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmIncrementRateLimit.t.Errorf("SessionStorageMock.IncrementRateLimit got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.ttl != nil && !minimock.Equal(*mm_want_ptrs.ttl, mm_got.ttl) {
				mmIncrementRateLimit.t.Errorf("SessionStorageMock.IncrementRateLimit got unexpected parameter ttl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.expectationOrigins.originTtl, *mm_want_ptrs.ttl, mm_got.ttl, minimock.Diff(*mm_want_ptrs.ttl, mm_got.ttl))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIncrementRateLimit.t.Errorf("SessionStorageMock.IncrementRateLimit got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIncrementRateLimit.IncrementRateLimitMock.defaultExpectation.results
		if mm_results == nil {
			mmIncrementRateLimit.t.Fatal("No results are set for the SessionStorageMock.IncrementRateLimit")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmIncrementRateLimit.funcIncrementRateLimit != nil {
		return mmIncrementRateLimit.funcIncrementRateLimit(ctx, key, ttl)
	}
	mmIncrementRateLimit.t.Fatalf("Unexpected call to SessionStorageMock.IncrementRateLimit. %v %v %v", ctx, key, ttl)
	return
}

// IncrementRateLimitAfterCounter returns a count of finished SessionStorageMock.IncrementRateLimit invocations
func (mmIncrementRateLimit *SessionStorageMock) IncrementRateLimitAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIncrementRateLimit.afterIncrementRateLimitCounter)
}

// IncrementRateLimitBeforeCounter returns a count of SessionStorageMock.IncrementRateLimit invocations
func (mmIncrementRateLimit *SessionStorageMock) IncrementRateLimitBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIncrementRateLimit.beforeIncrementRateLimitCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.IncrementRateLimit.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIncrementRateLimit *mSessionStorageMockIncrementRateLimit) Calls() []*SessionStorageMockIncrementRateLimitParams {
	mmIncrementRateLimit.mutex.RLock()

	argCopy := make([]*SessionStorageMockIncrementRateLimitParams, len(mmIncrementRateLimit.callArgs))
	copy(argCopy, mmIncrementRateLimit.callArgs)

	mmIncrementRateLimit.mutex.RUnlock()

	return argCopy
}

// MinimockIncrementRateLimitDone returns true if the count of the IncrementRateLimit invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockIncrementRateLimitDone() bool {
	if m.IncrementRateLimitMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IncrementRateLimitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IncrementRateLimitMock.invocationsDone()
}

// MinimockIncrementRateLimitInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockIncrementRateLimitInspect() {
	for _, e := range m.IncrementRateLimitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.IncrementRateLimit at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterIncrementRateLimitCounter := mm_atomic.LoadUint64(&m.afterIncrementRateLimitCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IncrementRateLimitMock.defaultExpectation != nil && afterIncrementRateLimitCounter < 1 {
		if m.IncrementRateLimitMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.IncrementRateLimit at\n%s", m.IncrementRateLimitMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.IncrementRateLimit at\n%s with params: %#v", m.IncrementRateLimitMock.defaultExpectation.expectationOrigins.origin, *m.IncrementRateLimitMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIncrementRateLimit != nil && afterIncrementRateLimitCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.IncrementRateLimit at\n%s", m.funcIncrementRateLimitOrigin)
	}

	if !m.IncrementRateLimitMock.invocationsDone() && afterIncrementRateLimitCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.IncrementRateLimit at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IncrementRateLimitMock.expectedInvocations), m.IncrementRateLimitMock.expectedInvocationsOrigin, afterIncrementRateLimitCounter)
	}
}

type mSessionStorageMockSetUsedOTPCounter struct {
	optional           bool
	mock               *SessionStorageMock
	defaultExpectation *SessionStorageMockSetUsedOTPCounterExpectation
	expectations       []*SessionStorageMockSetUsedOTPCounterExpectation

	callArgs []*SessionStorageMockSetUsedOTPCounterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionStorageMockSetUsedOTPCounterExpectation specifies expectation struct of the SessionStorage.SetUsedOTPCounter
type SessionStorageMockSetUsedOTPCounterExpectation struct {
	mock               *SessionStorageMock
	params             *SessionStorageMockSetUsedOTPCounterParams
	paramPtrs          *SessionStorageMockSetUsedOTPCounterParamPtrs
	expectationOrigins SessionStorageMockSetUsedOTPCounterExpectationOrigins
	results            *SessionStorageMockSetUsedOTPCounterResults
	returnOrigin       string
	Counter            uint64
}

// SessionStorageMockSetUsedOTPCounterParams contains parameters of the SessionStorage.SetUsedOTPCounter
type SessionStorageMockSetUsedOTPCounterParams struct {
	ctx     context.Context
	userID  string
	counter int64
	ttl     time.Duration
}

// SessionStorageMockSetUsedOTPCounterParamPtrs contains pointers to parameters of the SessionStorage.SetUsedOTPCounter
type SessionStorageMockSetUsedOTPCounterParamPtrs struct {
	ctx     *context.Context
	userID  *string
	counter *int64
	ttl     *time.Duration
}

// SessionStorageMockSetUsedOTPCounterResults contains results of the SessionStorage.SetUsedOTPCounter
type SessionStorageMockSetUsedOTPCounterResults struct {
	err error
}

// SessionStorageMockSetUsedOTPCounterOrigins contains origins of expectations of the SessionStorage.SetUsedOTPCounter
type SessionStorageMockSetUsedOTPCounterExpectationOrigins struct {
	origin        string
	originCtx     string
	originUserID  string
	originCounter string
	originTtl     string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Optional() *mSessionStorageMockSetUsedOTPCounter {
	mmSetUsedOTPCounter.optional = true
	return mmSetUsedOTPCounter
}

// Expect sets up expected params for SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Expect(ctx context.Context, userID string, counter int64, ttl time.Duration) *mSessionStorageMockSetUsedOTPCounter {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	if mmSetUsedOTPCounter.defaultExpectation == nil {
		mmSetUsedOTPCounter.defaultExpectation = &SessionStorageMockSetUsedOTPCounterExpectation{}
	}

	if mmSetUsedOTPCounter.defaultExpectation.paramPtrs != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by ExpectParams functions")
	}

	mmSetUsedOTPCounter.defaultExpectation.params = &SessionStorageMockSetUsedOTPCounterParams{ctx, userID, counter, ttl}
	mmSetUsedOTPCounter.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetUsedOTPCounter.expectations {
		if minimock.Equal(e.params, mmSetUsedOTPCounter.defaultExpectation.params) {
			mmSetUsedOTPCounter.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetUsedOTPCounter.defaultExpectation.params)
		}
	}

	return mmSetUsedOTPCounter
}

// ExpectCtxParam1 sets up expected param ctx for SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) ExpectCtxParam1(ctx context.Context) *mSessionStorageMockSetUsedOTPCounter {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	if mmSetUsedOTPCounter.defaultExpectation == nil {
		mmSetUsedOTPCounter.defaultExpectation = &SessionStorageMockSetUsedOTPCounterExpectation{}
	}

	if mmSetUsedOTPCounter.defaultExpectation.params != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Expect")
	}

	if mmSetUsedOTPCounter.defaultExpectation.paramPtrs == nil {
		mmSetUsedOTPCounter.defaultExpectation.paramPtrs = &SessionStorageMockSetUsedOTPCounterParamPtrs{}
	}
	mmSetUsedOTPCounter.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetUsedOTPCounter.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetUsedOTPCounter
}

// ExpectUserIDParam2 sets up expected param userID for SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) ExpectUserIDParam2(userID string) *mSessionStorageMockSetUsedOTPCounter {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	if mmSetUsedOTPCounter.defaultExpectation == nil {
		mmSetUsedOTPCounter.defaultExpectation = &SessionStorageMockSetUsedOTPCounterExpectation{}
	}

	if mmSetUsedOTPCounter.defaultExpectation.params != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Expect")
	}

	if mmSetUsedOTPCounter.defaultExpectation.paramPtrs == nil {
		mmSetUsedOTPCounter.defaultExpectation.paramPtrs = &SessionStorageMockSetUsedOTPCounterParamPtrs{}
	}
	mmSetUsedOTPCounter.defaultExpectation.paramPtrs.userID = &userID
	mmSetUsedOTPCounter.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmSetUsedOTPCounter
}

// ExpectCounterParam3 sets up expected param counter for SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) ExpectCounterParam3(counter int64) *mSessionStorageMockSetUsedOTPCounter {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	if mmSetUsedOTPCounter.defaultExpectation == nil {
		mmSetUsedOTPCounter.defaultExpectation = &SessionStorageMockSetUsedOTPCounterExpectation{}
	}

	if mmSetUsedOTPCounter.defaultExpectation.params != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Expect")
	}

	if mmSetUsedOTPCounter.defaultExpectation.paramPtrs == nil {
		mmSetUsedOTPCounter.defaultExpectation.paramPtrs = &SessionStorageMockSetUsedOTPCounterParamPtrs{}
	}
	mmSetUsedOTPCounter.defaultExpectation.paramPtrs.counter = &counter
	mmSetUsedOTPCounter.defaultExpectation.expectationOrigins.originCounter = minimock.CallerInfo(1)

	return mmSetUsedOTPCounter
}

// ExpectTtlParam4 sets up expected param ttl for SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) ExpectTtlParam4(ttl time.Duration) *mSessionStorageMockSetUsedOTPCounter {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	if mmSetUsedOTPCounter.defaultExpectation == nil {
		mmSetUsedOTPCounter.defaultExpectation = &SessionStorageMockSetUsedOTPCounterExpectation{}
	}

	if mmSetUsedOTPCounter.defaultExpectation.params != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Expect")
	}

	if mmSetUsedOTPCounter.defaultExpectation.paramPtrs == nil {
		mmSetUsedOTPCounter.defaultExpectation.paramPtrs = &SessionStorageMockSetUsedOTPCounterParamPtrs{}
	}
	mmSetUsedOTPCounter.defaultExpectation.paramPtrs.ttl = &ttl
	mmSetUsedOTPCounter.defaultExpectation.expectationOrigins.originTtl = minimock.CallerInfo(1)

	return mmSetUsedOTPCounter
}

// Inspect accepts an inspector function that has same arguments as the SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Inspect(f func(ctx context.Context, userID string, counter int64, ttl time.Duration)) *mSessionStorageMockSetUsedOTPCounter {
	if mmSetUsedOTPCounter.mock.inspectFuncSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("Inspect function is already set for SessionStorageMock.SetUsedOTPCounter")
	}

	mmSetUsedOTPCounter.mock.inspectFuncSetUsedOTPCounter = f

	return mmSetUsedOTPCounter
}

// Return sets up results that will be returned by SessionStorage.SetUsedOTPCounter
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Return(err error) *SessionStorageMock {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	if mmSetUsedOTPCounter.defaultExpectation == nil {
		mmSetUsedOTPCounter.defaultExpectation = &SessionStorageMockSetUsedOTPCounterExpectation{mock: mmSetUsedOTPCounter.mock}
	}
	mmSetUsedOTPCounter.defaultExpectation.results = &SessionStorageMockSetUsedOTPCounterResults{err}
	mmSetUsedOTPCounter.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetUsedOTPCounter.mock
}

// Set uses given function f to mock the SessionStorage.SetUsedOTPCounter method
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Set(f func(ctx context.Context, userID string, counter int64, ttl time.Duration) (err error)) *SessionStorageMock {
	if mmSetUsedOTPCounter.defaultExpectation != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("Default expectation is already set for the SessionStorage.SetUsedOTPCounter method")
	}

	if len(mmSetUsedOTPCounter.expectations) > 0 {
		mmSetUsedOTPCounter.mock.t.Fatalf("Some expectations are already set for the SessionStorage.SetUsedOTPCounter method")
	}

	mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter = f
	mmSetUsedOTPCounter.mock.funcSetUsedOTPCounterOrigin = minimock.CallerInfo(1)
	return mmSetUsedOTPCounter.mock
}

// When sets expectation for the SessionStorage.SetUsedOTPCounter which will trigger the result defined by the following
// Then helper
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) When(ctx context.Context, userID string, counter int64, ttl time.Duration) *SessionStorageMockSetUsedOTPCounterExpectation {
	if mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.mock.t.Fatalf("SessionStorageMock.SetUsedOTPCounter mock is already set by Set")
	}

	expectation := &SessionStorageMockSetUsedOTPCounterExpectation{
		mock:               mmSetUsedOTPCounter.mock,
		params:             &SessionStorageMockSetUsedOTPCounterParams{ctx, userID, counter, ttl},
		expectationOrigins: SessionStorageMockSetUsedOTPCounterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetUsedOTPCounter.expectations = append(mmSetUsedOTPCounter.expectations, expectation)
	return expectation
}

// Then sets up SessionStorage.SetUsedOTPCounter return parameters for the expectation previously defined by the When method
func (e *SessionStorageMockSetUsedOTPCounterExpectation) Then(err error) *SessionStorageMock {
	e.results = &SessionStorageMockSetUsedOTPCounterResults{err}
	return e.mock
}

// Times sets number of times SessionStorage.SetUsedOTPCounter should be invoked
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Times(n uint64) *mSessionStorageMockSetUsedOTPCounter {
	if n == 0 {
		mmSetUsedOTPCounter.mock.t.Fatalf("Times of SessionStorageMock.SetUsedOTPCounter mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetUsedOTPCounter.expectedInvocations, n)
	mmSetUsedOTPCounter.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetUsedOTPCounter
}

func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) invocationsDone() bool {
	if len(mmSetUsedOTPCounter.expectations) == 0 && mmSetUsedOTPCounter.defaultExpectation == nil && mmSetUsedOTPCounter.mock.funcSetUsedOTPCounter == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetUsedOTPCounter.mock.afterSetUsedOTPCounterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetUsedOTPCounter.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetUsedOTPCounter implements mm_twofaService.SessionStorage
func (mmSetUsedOTPCounter *SessionStorageMock) SetUsedOTPCounter(ctx context.Context, userID string, counter int64, ttl time.Duration) (err error) {
	mm_atomic.AddUint64(&mmSetUsedOTPCounter.beforeSetUsedOTPCounterCounter, 1)
	defer mm_atomic.AddUint64(&mmSetUsedOTPCounter.afterSetUsedOTPCounterCounter, 1)

	mmSetUsedOTPCounter.t.Helper()

	if mmSetUsedOTPCounter.inspectFuncSetUsedOTPCounter != nil {
		mmSetUsedOTPCounter.inspectFuncSetUsedOTPCounter(ctx, userID, counter, ttl)
	}

	mm_params := SessionStorageMockSetUsedOTPCounterParams{ctx, userID, counter, ttl}

	// Record call args
	mmSetUsedOTPCounter.SetUsedOTPCounterMock.mutex.Lock()
	mmSetUsedOTPCounter.SetUsedOTPCounterMock.callArgs = append(mmSetUsedOTPCounter.SetUsedOTPCounterMock.callArgs, &mm_params)
	mmSetUsedOTPCounter.SetUsedOTPCounterMock.mutex.Unlock()

	for _, e := range mmSetUsedOTPCounter.SetUsedOTPCounterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.Counter, 1)
		mm_want := mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.params
		mm_want_ptrs := mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.paramPtrs

		mm_got := SessionStorageMockSetUsedOTPCounterParams{ctx, userID, counter, ttl}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetUsedOTPCounter.t.Errorf("SessionStorageMock.SetUsedOTPCounter got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmSetUsedOTPCounter.t.Errorf("SessionStorageMock.SetUsedOTPCounter got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.counter != nil && !minimock.Equal(*mm_want_ptrs.counter, mm_got.counter) {
				mmSetUsedOTPCounter.t.Errorf("SessionStorageMock.SetUsedOTPCounter got unexpected parameter counter, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.expectationOrigins.originCounter, *mm_want_ptrs.counter, mm_got.counter, minimock.Diff(*mm_want_ptrs.counter, mm_got.counter))
			}

			if mm_want_ptrs.ttl != nil && !minimock.Equal(*mm_want_ptrs.ttl, mm_got.ttl) {
				mmSetUsedOTPCounter.t.Errorf("SessionStorageMock.SetUsedOTPCounter got unexpected parameter ttl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.expectationOrigins.originTtl, *mm_want_ptrs.ttl, mm_got.ttl, minimock.Diff(*mm_want_ptrs.ttl, mm_got.ttl))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetUsedOTPCounter.t.Errorf("SessionStorageMock.SetUsedOTPCounter got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSetUsedOTPCounter.SetUsedOTPCounterMock.defaultExpectation.results
		if mm_results == nil {
			mmSetUsedOTPCounter.t.Fatal("No results are set for the SessionStorageMock.SetUsedOTPCounter")
		}
		return (*mm_results).err
	}
	if mmSetUsedOTPCounter.funcSetUsedOTPCounter != nil {
		return mmSetUsedOTPCounter.funcSetUsedOTPCounter(ctx, userID, counter, ttl)
	}
	mmSetUsedOTPCounter.t.Fatalf("Unexpected call to SessionStorageMock.SetUsedOTPCounter. %v %v %v %v", ctx, userID, counter, ttl)
	return
}

// SetUsedOTPCounterAfterCounter returns a count of finished SessionStorageMock.SetUsedOTPCounter invocations
func (mmSetUsedOTPCounter *SessionStorageMock) SetUsedOTPCounterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUsedOTPCounter.afterSetUsedOTPCounterCounter)
}

// SetUsedOTPCounterBeforeCounter returns a count of SessionStorageMock.SetUsedOTPCounter invocations
func (mmSetUsedOTPCounter *SessionStorageMock) SetUsedOTPCounterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUsedOTPCounter.beforeSetUsedOTPCounterCounter)
}

// Calls returns a list of arguments used in each call to SessionStorageMock.SetUsedOTPCounter.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetUsedOTPCounter *mSessionStorageMockSetUsedOTPCounter) Calls() []*SessionStorageMockSetUsedOTPCounterParams {
	mmSetUsedOTPCounter.mutex.RLock()

	argCopy := make([]*SessionStorageMockSetUsedOTPCounterParams, len(mmSetUsedOTPCounter.callArgs))
	copy(argCopy, mmSetUsedOTPCounter.callArgs)

	mmSetUsedOTPCounter.mutex.RUnlock()

	return argCopy
}

// MinimockSetUsedOTPCounterDone returns true if the count of the SetUsedOTPCounter invocations corresponds
// the number of defined expectations
func (m *SessionStorageMock) MinimockSetUsedOTPCounterDone() bool {
	if m.SetUsedOTPCounterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetUsedOTPCounterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetUsedOTPCounterMock.invocationsDone()
}

// MinimockSetUsedOTPCounterInspect logs each unmet expectation
func (m *SessionStorageMock) MinimockSetUsedOTPCounterInspect() {
	for _, e := range m.SetUsedOTPCounterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionStorageMock.SetUsedOTPCounter at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetUsedOTPCounterCounter := mm_atomic.LoadUint64(&m.afterSetUsedOTPCounterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetUsedOTPCounterMock.defaultExpectation != nil && afterSetUsedOTPCounterCounter < 1 {
		if m.SetUsedOTPCounterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionStorageMock.SetUsedOTPCounter at\n%s", m.SetUsedOTPCounterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionStorageMock.SetUsedOTPCounter at\n%s with params: %#v", m.SetUsedOTPCounterMock.defaultExpectation.expectationOrigins.origin, *m.SetUsedOTPCounterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetUsedOTPCounter != nil && afterSetUsedOTPCounterCounter < 1 {
		m.t.Errorf("Expected call to SessionStorageMock.SetUsedOTPCounter at\n%s", m.funcSetUsedOTPCounterOrigin)
	}

	if !m.SetUsedOTPCounterMock.invocationsDone() && afterSetUsedOTPCounterCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionStorageMock.SetUsedOTPCounter at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetUsedOTPCounterMock.expectedInvocations), m.SetUsedOTPCounterMock.expectedInvocationsOrigin, afterSetUsedOTPCounterCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SessionStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteKeysInspect()

			m.MinimockGetRateLimitInspect()

			m.MinimockGetUsedOTPCounterInspect()

			m.MinimockIncrementRateLimitInspect()

			m.MinimockSetUsedOTPCounterInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SessionStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SessionStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteKeysDone() &&
		m.MinimockGetRateLimitDone() &&
		m.MinimockGetUsedOTPCounterDone() &&
		m.MinimockIncrementRateLimitDone() &&
		m.MinimockSetUsedOTPCounterDone()
}
