// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: twofa_api/twofa_service.proto

package twofa_api

import (
	_ "github.com/vbncursed/vkr/twofa/internal/pb/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Setup2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setup2FARequest) Reset() {
	*x = Setup2FARequest{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setup2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setup2FARequest) ProtoMessage() {}

func (x *Setup2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setup2FARequest.ProtoReflect.Descriptor instead.
func (*Setup2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{0}
}

func (x *Setup2FARequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Setup2FAResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProvisioningUri string                 `protobuf:"bytes,1,opt,name=provisioning_uri,json=provisioningUri,proto3" json:"provisioning_uri,omitempty"`
	BackupCodes     []string               `protobuf:"bytes,2,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Setup2FAResponse) Reset() {
	*x = Setup2FAResponse{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setup2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setup2FAResponse) ProtoMessage() {}

func (x *Setup2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setup2FAResponse.ProtoReflect.Descriptor instead.
func (*Setup2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{1}
}

func (x *Setup2FAResponse) GetProvisioningUri() string {
	if x != nil {
		return x.ProvisioningUri
	}
	return ""
}

func (x *Setup2FAResponse) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

type Verify2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FARequest) Reset() {
	*x = Verify2FARequest{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FARequest) ProtoMessage() {}

func (x *Verify2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FARequest.ProtoReflect.Descriptor instead.
func (*Verify2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{2}
}

func (x *Verify2FARequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Verify2FARequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type Verify2FAResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valid          bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	IsNewlyEnabled bool                   `protobuf:"varint,2,opt,name=is_newly_enabled,json=isNewlyEnabled,proto3" json:"is_newly_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Verify2FAResponse) Reset() {
	*x = Verify2FAResponse{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FAResponse) ProtoMessage() {}

func (x *Verify2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FAResponse.ProtoReflect.Descriptor instead.
func (*Verify2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{3}
}

func (x *Verify2FAResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Verify2FAResponse) GetIsNewlyEnabled() bool {
	if x != nil {
		return x.IsNewlyEnabled
	}
	return false
}

type Disable2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FARequest) Reset() {
	*x = Disable2FARequest{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FARequest) ProtoMessage() {}

func (x *Disable2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FARequest.ProtoReflect.Descriptor instead.
func (*Disable2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{4}
}

func (x *Disable2FARequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Disable2FARequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type Disable2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FAResponse) Reset() {
	*x = Disable2FAResponse{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FAResponse) ProtoMessage() {}

func (x *Disable2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FAResponse.ProtoReflect.Descriptor instead.
func (*Disable2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{5}
}

type Get2FAStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get2FAStatusRequest) Reset() {
	*x = Get2FAStatusRequest{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get2FAStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get2FAStatusRequest) ProtoMessage() {}

func (x *Get2FAStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get2FAStatusRequest.ProtoReflect.Descriptor instead.
func (*Get2FAStatusRequest) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{6}
}

func (x *Get2FAStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Get2FAStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get2FAStatusResponse) Reset() {
	*x = Get2FAStatusResponse{}
	mi := &file_twofa_api_twofa_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get2FAStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get2FAStatusResponse) ProtoMessage() {}

func (x *Get2FAStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_api_twofa_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get2FAStatusResponse.ProtoReflect.Descriptor instead.
func (*Get2FAStatusResponse) Descriptor() ([]byte, []int) {
	return file_twofa_api_twofa_service_proto_rawDescGZIP(), []int{7}
}

func (x *Get2FAStatusResponse) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *Get2FAStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_twofa_api_twofa_service_proto protoreflect.FileDescriptor

const file_twofa_api_twofa_service_proto_rawDesc = "" +
	"\n" +
	"\x1dtwofa_api/twofa_service.proto\x12\ttwofa_api\x1a\x13models/models.proto\"*\n" +
	"\x0fSetup2FARequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"`\n" +
	"\x10Setup2FAResponse\x12)\n" +
	"\x10provisioning_uri\x18\x01 \x01(\tR\x0fprovisioningUri\x12!\n" +
	"\fbackup_codes\x18\x02 \x03(\tR\vbackupCodes\"F\n" +
	"\x10Verify2FARequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"S\n" +
	"\x11Verify2FAResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12(\n" +
	"\x10is_newly_enabled\x18\x02 \x01(\bR\x0eisNewlyEnabled\"G\n" +
	"\x11Disable2FARequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"\x14\n" +
	"\x12Disable2FAResponse\".\n" +
	"\x13Get2FAStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	"\x14Get2FAStatusResponse\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x01 \x01(\bR\tisEnabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt2\xb7\x02\n" +
	"\fTwoFAService\x12C\n" +
	"\bSetup2FA\x12\x1a.twofa_api.Setup2FARequest\x1a\x1b.twofa_api.Setup2FAResponse\x12F\n" +
	"\tVerify2FA\x12\x1b.twofa_api.Verify2FARequest\x1a\x1c.twofa_api.Verify2FAResponse\x12I\n" +
	"\n" +
	"Disable2FA\x12\x1c.twofa_api.Disable2FARequest\x1a\x1d.twofa_api.Disable2FAResponse\x12O\n" +
	"\fGet2FAStatus\x12\x1e.twofa_api.Get2FAStatusRequest\x1a\x1f.twofa_api.Get2FAStatusResponseB6Z4github.com/vbncursed/vkr/twofa/internal/pb/twofa_apib\x06proto3"

var (
	file_twofa_api_twofa_service_proto_rawDescOnce sync.Once
	file_twofa_api_twofa_service_proto_rawDescData []byte
)

func file_twofa_api_twofa_service_proto_rawDescGZIP() []byte {
	file_twofa_api_twofa_service_proto_rawDescOnce.Do(func() {
		file_twofa_api_twofa_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_twofa_api_twofa_service_proto_rawDesc), len(file_twofa_api_twofa_service_proto_rawDesc)))
	})
	return file_twofa_api_twofa_service_proto_rawDescData
}

var file_twofa_api_twofa_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_twofa_api_twofa_service_proto_goTypes = []any{
	(*Setup2FARequest)(nil),      // 0: twofa_api.Setup2FARequest
	(*Setup2FAResponse)(nil),     // 1: twofa_api.Setup2FAResponse
	(*Verify2FARequest)(nil),     // 2: twofa_api.Verify2FARequest
	(*Verify2FAResponse)(nil),    // 3: twofa_api.Verify2FAResponse
	(*Disable2FARequest)(nil),    // 4: twofa_api.Disable2FARequest
	(*Disable2FAResponse)(nil),   // 5: twofa_api.Disable2FAResponse
	(*Get2FAStatusRequest)(nil),  // 6: twofa_api.Get2FAStatusRequest
	(*Get2FAStatusResponse)(nil), // 7: twofa_api.Get2FAStatusResponse
}
var file_twofa_api_twofa_service_proto_depIdxs = []int32{
	0, // 0: twofa_api.TwoFAService.Setup2FA:input_type -> twofa_api.Setup2FARequest
	2, // 1: twofa_api.TwoFAService.Verify2FA:input_type -> twofa_api.Verify2FARequest
	4, // 2: twofa_api.TwoFAService.Disable2FA:input_type -> twofa_api.Disable2FARequest
	6, // 3: twofa_api.TwoFAService.Get2FAStatus:input_type -> twofa_api.Get2FAStatusRequest
	1, // 4: twofa_api.TwoFAService.Setup2FA:output_type -> twofa_api.Setup2FAResponse
	3, // 5: twofa_api.TwoFAService.Verify2FA:output_type -> twofa_api.Verify2FAResponse
	5, // 6: twofa_api.TwoFAService.Disable2FA:output_type -> twofa_api.Disable2FAResponse
	7, // 7: twofa_api.TwoFAService.Get2FAStatus:output_type -> twofa_api.Get2FAStatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_twofa_api_twofa_service_proto_init() }
func file_twofa_api_twofa_service_proto_init() {
	if File_twofa_api_twofa_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_twofa_api_twofa_service_proto_rawDesc), len(file_twofa_api_twofa_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_twofa_api_twofa_service_proto_goTypes,
		DependencyIndexes: file_twofa_api_twofa_service_proto_depIdxs,
		MessageInfos:      file_twofa_api_twofa_service_proto_msgTypes,
	}.Build()
	File_twofa_api_twofa_service_proto = out.File
	file_twofa_api_twofa_service_proto_goTypes = nil
	file_twofa_api_twofa_service_proto_depIdxs = nil
}
